/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminCreateInstaller200Response,
  AdminGetCic200Response,
  AdminListCics200Response,
  AdminListInstallers200Response,
  CompleteCommissioning200Response,
  CreateUpdateInstaller,
  ErrorResponse,
  UpdateAdminCic,
} from '../models';
import {
    AdminCreateInstaller200ResponseFromJSON,
    AdminCreateInstaller200ResponseToJSON,
    AdminGetCic200ResponseFromJSON,
    AdminGetCic200ResponseToJSON,
    AdminListCics200ResponseFromJSON,
    AdminListCics200ResponseToJSON,
    AdminListInstallers200ResponseFromJSON,
    AdminListInstallers200ResponseToJSON,
    CompleteCommissioning200ResponseFromJSON,
    CompleteCommissioning200ResponseToJSON,
    CreateUpdateInstallerFromJSON,
    CreateUpdateInstallerToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    UpdateAdminCicFromJSON,
    UpdateAdminCicToJSON,
} from '../models';

export interface AdminCicCicIdOptionsRequest {
    cicId: string;
}

export interface AdminCreateInstallerRequest {
    createUpdateInstaller?: CreateUpdateInstaller;
}

export interface AdminDeleteInstallerRequest {
    installerId: string;
}

export interface AdminGetCicRequest {
    cicId: string;
}

export interface AdminGetInstallerRequest {
    installerId: string;
}

export interface AdminUpdateCicRequest {
    cicId: string;
    updateAdminCic?: UpdateAdminCic;
}

export interface AdminUpdateInstallerRequest {
    installerId: string;
    createUpdateInstaller?: CreateUpdateInstaller;
}

/**
 * 
 */
export class SupportDashboardApi extends runtime.BaseAPI {

    /**
     */
    async adminCicCicIdOptionsRaw(requestParameters: AdminCicCicIdOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.cicId === null || requestParameters.cicId === undefined) {
            throw new runtime.RequiredError('cicId','Required parameter requestParameters.cicId was null or undefined when calling adminCicCicIdOptions.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/admin/cic/{cicId}`.replace(`{${"cicId"}}`, encodeURIComponent(String(requestParameters.cicId))),
            method: 'OPTIONS',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async adminCicCicIdOptions(requestParameters: AdminCicCicIdOptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminCicCicIdOptionsRaw(requestParameters, initOverrides);
    }

    /**
     */
    async adminCicListOptionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/admin/cic/list`,
            method: 'OPTIONS',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async adminCicListOptions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminCicListOptionsRaw(initOverrides);
    }

    /**
     * Create installer
     */
    async adminCreateInstallerRaw(requestParameters: AdminCreateInstallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminCreateInstaller200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/installer`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUpdateInstallerToJSON(requestParameters.createUpdateInstaller),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminCreateInstaller200ResponseFromJSON(jsonValue));
    }

    /**
     * Create installer
     */
    async adminCreateInstaller(requestParameters: AdminCreateInstallerRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminCreateInstaller200Response> {
        const response = await this.adminCreateInstallerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete installer
     */
    async adminDeleteInstallerRaw(requestParameters: AdminDeleteInstallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompleteCommissioning200Response>> {
        if (requestParameters.installerId === null || requestParameters.installerId === undefined) {
            throw new runtime.RequiredError('installerId','Required parameter requestParameters.installerId was null or undefined when calling adminDeleteInstaller.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/installer/{installerId}`.replace(`{${"installerId"}}`, encodeURIComponent(String(requestParameters.installerId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompleteCommissioning200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete installer
     */
    async adminDeleteInstaller(requestParameters: AdminDeleteInstallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompleteCommissioning200Response> {
        const response = await this.adminDeleteInstallerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get cic
     */
    async adminGetCicRaw(requestParameters: AdminGetCicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminGetCic200Response>> {
        if (requestParameters.cicId === null || requestParameters.cicId === undefined) {
            throw new runtime.RequiredError('cicId','Required parameter requestParameters.cicId was null or undefined when calling adminGetCic.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/cic/{cicId}`.replace(`{${"cicId"}}`, encodeURIComponent(String(requestParameters.cicId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminGetCic200ResponseFromJSON(jsonValue));
    }

    /**
     * Get cic
     */
    async adminGetCic(requestParameters: AdminGetCicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminGetCic200Response> {
        const response = await this.adminGetCicRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get installer
     */
    async adminGetInstallerRaw(requestParameters: AdminGetInstallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminCreateInstaller200Response>> {
        if (requestParameters.installerId === null || requestParameters.installerId === undefined) {
            throw new runtime.RequiredError('installerId','Required parameter requestParameters.installerId was null or undefined when calling adminGetInstaller.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/installer/{installerId}`.replace(`{${"installerId"}}`, encodeURIComponent(String(requestParameters.installerId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminCreateInstaller200ResponseFromJSON(jsonValue));
    }

    /**
     * Get installer
     */
    async adminGetInstaller(requestParameters: AdminGetInstallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminCreateInstaller200Response> {
        const response = await this.adminGetInstallerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async adminInstallerInstallerIdOptionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/admin/installer/{installerId}`,
            method: 'OPTIONS',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async adminInstallerInstallerIdOptions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminInstallerInstallerIdOptionsRaw(initOverrides);
    }

    /**
     */
    async adminInstallerListOptionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/admin/installer/list`,
            method: 'OPTIONS',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async adminInstallerListOptions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminInstallerListOptionsRaw(initOverrides);
    }

    /**
     */
    async adminInstallerOptionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/admin/installer`,
            method: 'OPTIONS',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async adminInstallerOptions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminInstallerOptionsRaw(initOverrides);
    }

    /**
     * List cics
     */
    async adminListCicsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminListCics200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/cic/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminListCics200ResponseFromJSON(jsonValue));
    }

    /**
     * List cics
     */
    async adminListCics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminListCics200Response> {
        const response = await this.adminListCicsRaw(initOverrides);
        return await response.value();
    }

    /**
     * List installers
     */
    async adminListInstallersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminListInstallers200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/installer/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminListInstallers200ResponseFromJSON(jsonValue));
    }

    /**
     * List installers
     */
    async adminListInstallers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminListInstallers200Response> {
        const response = await this.adminListInstallersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update cic
     */
    async adminUpdateCicRaw(requestParameters: AdminUpdateCicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminGetCic200Response>> {
        if (requestParameters.cicId === null || requestParameters.cicId === undefined) {
            throw new runtime.RequiredError('cicId','Required parameter requestParameters.cicId was null or undefined when calling adminUpdateCic.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/cic/{cicId}`.replace(`{${"cicId"}}`, encodeURIComponent(String(requestParameters.cicId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAdminCicToJSON(requestParameters.updateAdminCic),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminGetCic200ResponseFromJSON(jsonValue));
    }

    /**
     * Update cic
     */
    async adminUpdateCic(requestParameters: AdminUpdateCicRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminGetCic200Response> {
        const response = await this.adminUpdateCicRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update installer
     */
    async adminUpdateInstallerRaw(requestParameters: AdminUpdateInstallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminCreateInstaller200Response>> {
        if (requestParameters.installerId === null || requestParameters.installerId === undefined) {
            throw new runtime.RequiredError('installerId','Required parameter requestParameters.installerId was null or undefined when calling adminUpdateInstaller.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin/installer/{installerId}`.replace(`{${"installerId"}}`, encodeURIComponent(String(requestParameters.installerId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUpdateInstallerToJSON(requestParameters.createUpdateInstaller),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminCreateInstaller200ResponseFromJSON(jsonValue));
    }

    /**
     * Update installer
     */
    async adminUpdateInstaller(requestParameters: AdminUpdateInstallerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminCreateInstaller200Response> {
        const response = await this.adminUpdateInstallerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
