/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AdminCicCreateInstallation409ResponseAllOfResult } from "./AdminCicCreateInstallation409ResponseAllOfResult";
import {
  AdminCicCreateInstallation409ResponseAllOfResultFromJSON,
  AdminCicCreateInstallation409ResponseAllOfResultFromJSONTyped,
  AdminCicCreateInstallation409ResponseAllOfResultToJSON,
} from "./AdminCicCreateInstallation409ResponseAllOfResult";
import type { CreateTariff409ResponseAllOfMeta } from "./CreateTariff409ResponseAllOfMeta";
import {
  CreateTariff409ResponseAllOfMetaFromJSON,
  CreateTariff409ResponseAllOfMetaFromJSONTyped,
  CreateTariff409ResponseAllOfMetaToJSON,
} from "./CreateTariff409ResponseAllOfMeta";

/**
 *
 * @export
 * @interface AdminCicCreateInstallation409Response
 */
export interface AdminCicCreateInstallation409Response {
  /**
   *
   * @type {CreateTariff409ResponseAllOfMeta}
   * @memberof AdminCicCreateInstallation409Response
   */
  meta: CreateTariff409ResponseAllOfMeta;
  /**
   *
   * @type {AdminCicCreateInstallation409ResponseAllOfResult}
   * @memberof AdminCicCreateInstallation409Response
   */
  result: AdminCicCreateInstallation409ResponseAllOfResult;
}

/**
 * Check if a given object implements the AdminCicCreateInstallation409Response interface.
 */
export function instanceOfAdminCicCreateInstallation409Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function AdminCicCreateInstallation409ResponseFromJSON(
  json: any,
): AdminCicCreateInstallation409Response {
  return AdminCicCreateInstallation409ResponseFromJSONTyped(json, false);
}

export function AdminCicCreateInstallation409ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminCicCreateInstallation409Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: CreateTariff409ResponseAllOfMetaFromJSON(json["meta"]),
    result: AdminCicCreateInstallation409ResponseAllOfResultFromJSON(
      json["result"],
    ),
  };
}

export function AdminCicCreateInstallation409ResponseToJSON(
  value?: AdminCicCreateInstallation409Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: CreateTariff409ResponseAllOfMetaToJSON(value.meta),
    result: AdminCicCreateInstallation409ResponseAllOfResultToJSON(
      value.result,
    ),
  };
}
