/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminCicDeviceStream400ResponseAllOfResult
 */
export interface AdminCicDeviceStream400ResponseAllOfResult {
  /**
   *
   * @type {string}
   * @memberof AdminCicDeviceStream400ResponseAllOfResult
   */
  errorCode?: AdminCicDeviceStream400ResponseAllOfResultErrorCodeEnum;
}

/**
 * @export
 */
export const AdminCicDeviceStream400ResponseAllOfResultErrorCodeEnum = {
  MissingCicId: "MISSING_CIC_ID",
} as const;
export type AdminCicDeviceStream400ResponseAllOfResultErrorCodeEnum =
  (typeof AdminCicDeviceStream400ResponseAllOfResultErrorCodeEnum)[keyof typeof AdminCicDeviceStream400ResponseAllOfResultErrorCodeEnum];

/**
 * Check if a given object implements the AdminCicDeviceStream400ResponseAllOfResult interface.
 */
export function instanceOfAdminCicDeviceStream400ResponseAllOfResult(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function AdminCicDeviceStream400ResponseAllOfResultFromJSON(
  json: any,
): AdminCicDeviceStream400ResponseAllOfResult {
  return AdminCicDeviceStream400ResponseAllOfResultFromJSONTyped(json, false);
}

export function AdminCicDeviceStream400ResponseAllOfResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminCicDeviceStream400ResponseAllOfResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    errorCode: !exists(json, "errorCode") ? undefined : json["errorCode"],
  };
}

export function AdminCicDeviceStream400ResponseAllOfResultToJSON(
  value?: AdminCicDeviceStream400ResponseAllOfResult | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    errorCode: value.errorCode,
  };
}
