/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminReplaceChillInterfaceBoard400ResponseAllOfResult
 */
export interface AdminReplaceChillInterfaceBoard400ResponseAllOfResult {
  /**
   *
   * @type {string}
   * @memberof AdminReplaceChillInterfaceBoard400ResponseAllOfResult
   */
  errorCode?: AdminReplaceChillInterfaceBoard400ResponseAllOfResultErrorCodeEnum;
}

/**
 * @export
 */
export const AdminReplaceChillInterfaceBoard400ResponseAllOfResultErrorCodeEnum =
  {
    DeviceIsNotChill: "DEVICE_IS_NOT_CHILL",
    ChillInterfaceBoardAlreadyDeactivated:
      "CHILL_INTERFACE_BOARD_ALREADY_DEACTIVATED",
    ChillInterfaceBoardNotActive: "CHILL_INTERFACE_BOARD_NOT_ACTIVE",
    ChillInterfaceBoardAlreadyAssigned:
      "CHILL_INTERFACE_BOARD_ALREADY_ASSIGNED",
    ChillInterfaceBoardNotBelongToInstallation:
      "CHILL_INTERFACE_BOARD_NOT_BELONG_TO_INSTALLATION",
  } as const;
export type AdminReplaceChillInterfaceBoard400ResponseAllOfResultErrorCodeEnum =
  (typeof AdminReplaceChillInterfaceBoard400ResponseAllOfResultErrorCodeEnum)[keyof typeof AdminReplaceChillInterfaceBoard400ResponseAllOfResultErrorCodeEnum];

/**
 * Check if a given object implements the AdminReplaceChillInterfaceBoard400ResponseAllOfResult interface.
 */
export function instanceOfAdminReplaceChillInterfaceBoard400ResponseAllOfResult(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function AdminReplaceChillInterfaceBoard400ResponseAllOfResultFromJSON(
  json: any,
): AdminReplaceChillInterfaceBoard400ResponseAllOfResult {
  return AdminReplaceChillInterfaceBoard400ResponseAllOfResultFromJSONTyped(
    json,
    false,
  );
}

export function AdminReplaceChillInterfaceBoard400ResponseAllOfResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminReplaceChillInterfaceBoard400ResponseAllOfResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    errorCode: !exists(json, "errorCode") ? undefined : json["errorCode"],
  };
}

export function AdminReplaceChillInterfaceBoard400ResponseAllOfResultToJSON(
  value?: AdminReplaceChillInterfaceBoard400ResponseAllOfResult | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    errorCode: value.errorCode,
  };
}
