/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { BoilerType } from "./BoilerType";
import {
  BoilerTypeFromJSON,
  BoilerTypeFromJSONTyped,
  BoilerTypeToJSON,
} from "./BoilerType";
import type { CicAvailableWifiNetworksInner } from "./CicAvailableWifiNetworksInner";
import {
  CicAvailableWifiNetworksInnerFromJSON,
  CicAvailableWifiNetworksInnerFromJSONTyped,
  CicAvailableWifiNetworksInnerToJSON,
} from "./CicAvailableWifiNetworksInner";
import type { CicStatus } from "./CicStatus";
import {
  CicStatusFromJSON,
  CicStatusFromJSONTyped,
  CicStatusToJSON,
} from "./CicStatus";
import type { ConnectionStatus } from "./ConnectionStatus";
import {
  ConnectionStatusFromJSON,
  ConnectionStatusFromJSONTyped,
  ConnectionStatusToJSON,
} from "./ConnectionStatus";
import type { HeatDeliverySystem } from "./HeatDeliverySystem";
import {
  HeatDeliverySystemFromJSON,
  HeatDeliverySystemFromJSONTyped,
  HeatDeliverySystemToJSON,
} from "./HeatDeliverySystem";
import type { HeatPump } from "./HeatPump";
import {
  HeatPumpFromJSON,
  HeatPumpFromJSONTyped,
  HeatPumpToJSON,
} from "./HeatPump";
import type { InstallerCicAllOfLastCommissioning } from "./InstallerCicAllOfLastCommissioning";
import {
  InstallerCicAllOfLastCommissioningFromJSON,
  InstallerCicAllOfLastCommissioningFromJSONTyped,
  InstallerCicAllOfLastCommissioningToJSON,
} from "./InstallerCicAllOfLastCommissioning";
import type { SilentMode } from "./SilentMode";
import {
  SilentModeFromJSON,
  SilentModeFromJSONTyped,
  SilentModeToJSON,
} from "./SilentMode";
import type { ThermostatType } from "./ThermostatType";
import {
  ThermostatTypeFromJSON,
  ThermostatTypeFromJSONTyped,
  ThermostatTypeToJSON,
} from "./ThermostatType";

/**
 *
 * @export
 * @interface AdminCic
 */
export interface AdminCic {
  /**
   *
   * @type {string}
   * @memberof AdminCic
   */
  id: string;
  /**
   *
   * @type {ConnectionStatus}
   * @memberof AdminCic
   */
  lteConnectionStatus: ConnectionStatus | null;
  /**
   *
   * @type {ConnectionStatus}
   * @memberof AdminCic
   */
  cableConnectionStatus: ConnectionStatus | null;
  /**
   *
   * @type {ConnectionStatus}
   * @memberof AdminCic
   */
  wifiConnectionStatus: ConnectionStatus | null;
  /**
   * The SSID of the WiFi network the CIC is connected to. (human readable)
   * @type {string}
   * @memberof AdminCic
   */
  wifiSSID: string | null;
  /**
   *
   * @type {Array<CicAvailableWifiNetworksInner>}
   * @memberof AdminCic
   */
  availableWifiNetworks: Array<CicAvailableWifiNetworksInner> | null;
  /**
   *
   * @type {Date}
   * @memberof AdminCic
   */
  lastScannedForWifi: Date | null;
  /**
   *
   * @type {boolean}
   * @memberof AdminCic
   */
  isScanningForWifi: boolean;
  /**
   *
   * @type {string}
   * @memberof AdminCic
   */
  updateStatus: AdminCicUpdateStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof AdminCic
   */
  updateUntil: Date | null;
  /**
   *
   * @type {string}
   * @memberof AdminCic
   */
  boilerDemand: AdminCicBoilerDemandEnum;
  /**
   * Amount of power in watt
   * @type {number}
   * @memberof AdminCic
   */
  boilerPower: number | null;
  /**
   * Temperature in degrees celcius of the water flowing out
   * @type {number}
   * @memberof AdminCic
   */
  boilerWaterTemperatureIn: number | null;
  /**
   * Temperature in degrees celcius of the water flowing out
   * @type {number}
   * @memberof AdminCic
   */
  boilerWaterTemperatureOut: number | null;
  /**
   * Boiler pressure in bar
   * @type {number}
   * @memberof AdminCic
   */
  boilerPressure: number | null;
  /**
   *
   * @type {string}
   * @memberof AdminCic
   */
  thermostatDemand: AdminCicThermostatDemandEnum;
  /**
   * Temperature in degrees celcius of the room
   * @type {number}
   * @memberof AdminCic
   */
  thermostatRoomTemperature: number | null;
  /**
   * Temperature in degrees celcius set point of the room
   * @type {number}
   * @memberof AdminCic
   */
  thermostatRoomTemperatureSetPoint: number | null;
  /**
   * If the flame symbol is on on the thermostat
   * @type {boolean}
   * @memberof AdminCic
   */
  thermostatFlameOn: boolean | null;
  /**
   * If the live temperature is shown on the app
   * @type {boolean}
   * @memberof AdminCic
   */
  showThermostatTemperatures: boolean | null;
  /**
   * If the boiler is on
   * @type {boolean}
   * @memberof AdminCic
   */
  boilerOn: boolean;
  /**
   * Temperature in degrees celcius set point of the control
   * @type {number}
   * @memberof AdminCic
   */
  thermostatControlTemperatureSetPoint: number | null;
  /**
   * Temperature in degrees celcius of supply
   * @type {number}
   * @memberof AdminCic
   */
  supplyTemperature: number | null;
  /**
   *
   * @type {CicStatus}
   * @memberof AdminCic
   */
  status: CicStatus;
  /**
   * The cic serial number
   * @type {string}
   * @memberof AdminCic
   */
  serial: string | null;
  /**
   *
   * @type {number}
   * @memberof AdminCic
   */
  numberOfHeatPumps: number | null;
  /**
   * The amount (liter) of water flowing per hour
   * @type {number}
   * @memberof AdminCic
   */
  flowRate: number | null;
  /**
   * Electricity price for single tariff
   * @type {number}
   * @memberof AdminCic
   */
  electricityPrice: number | null;
  /**
   * Day electricity price for double tariff
   * @type {number}
   * @memberof AdminCic
   */
  dayElectricityPrice: number | null;
  /**
   * Night electricity price for double tariff
   * @type {number}
   * @memberof AdminCic
   */
  nightElectricityPrice: number | null;
  /**
   * Gas price
   * @type {number}
   * @memberof AdminCic
   */
  gasPrice: number | null;
  /**
   * When false, send default prices to not limit the heat pump
   * @type {boolean}
   * @memberof AdminCic
   */
  usePricingToLimitHeatPump: boolean;
  /**
   *
   * @type {SilentMode}
   * @memberof AdminCic
   */
  silentMode: SilentMode;
  /**
   *
   * @type {Array<HeatPump>}
   * @memberof AdminCic
   */
  heatPumps: Array<HeatPump>;
  /**
   *
   * @type {number}
   * @memberof AdminCic
   */
  supervisoryControlMode?: number | null;
  /**
   *
   * @type {boolean}
   * @memberof AdminCic
   */
  isHp1Connected?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof AdminCic
   */
  isHp2Connected?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof AdminCic
   */
  isThermostatConnected?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof AdminCic
   */
  isBoilerConnected?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof AdminCic
   */
  isTemperatureSensorConnected?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof AdminCic
   */
  isControllerAlive?: boolean | null;
  /**
   * The name of the CIC/house
   * @type {string}
   * @memberof AdminCic
   */
  name: string | null;
  /**
   *
   * @type {string}
   * @memberof AdminCic
   */
  zipCode: string | null;
  /**
   *
   * @type {string}
   * @memberof AdminCic
   */
  orderNumber: string | null;
  /**
   *
   * @type {boolean}
   * @memberof AdminCic
   */
  wifiEnabled: boolean;
  /**
   *
   * @type {string}
   * @memberof AdminCic
   */
  addressStreet: string | null;
  /**
   *
   * @type {string}
   * @memberof AdminCic
   */
  addressNumber?: string | null;
  /**
   *
   * @type {Array<HeatDeliverySystem>}
   * @memberof AdminCic
   */
  heatDeliverySystems: Array<HeatDeliverySystem> | null;
  /**
   *
   * @type {ThermostatType}
   * @memberof AdminCic
   */
  thermostatType: ThermostatType | null;
  /**
   *
   * @type {BoilerType}
   * @memberof AdminCic
   */
  boilerType: BoilerType | null;
  /**
   * The image version of the cic
   * @type {string}
   * @memberof AdminCic
   */
  quattBuild: string | null;
  /**
   * The minimal image version the CIC needs to be updated to to install
   * @type {string}
   * @memberof AdminCic
   */
  quattBuildRequired: string | null;
  /**
   * If the cic needs an update, null if unknown
   * @type {boolean}
   * @memberof AdminCic
   */
  needsUpdate: boolean | null;
  /**
   * The state of the mender update
   * @type {string}
   * @memberof AdminCic
   */
  menderUpdateState: AdminCicMenderUpdateStateEnum;
  /**
   * Rated maximum house power in watt
   * @type {number}
   * @memberof AdminCic
   */
  ratedMaximumHousePower: number | null;
  /**
   * Temperature in degrees celcius
   * @type {number}
   * @memberof AdminCic
   */
  maximumHeatingOutdoorTemperature: number | null;
  /**
   *
   * @type {InstallerCicAllOfLastCommissioning}
   * @memberof AdminCic
   */
  lastCommissioning: InstallerCicAllOfLastCommissioning;
  /**
   *
   * @type {string}
   * @memberof AdminCic
   */
  menderId: string | null;
  /**
   *
   * @type {Date}
   * @memberof AdminCic
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof AdminCic
   */
  lastConnectionStatusUpdatedAt: Date | null;
}

/**
 * @export
 */
export const AdminCicUpdateStatusEnum = {
  UpToDate: "up_to_date",
  Updating: "updating",
} as const;
export type AdminCicUpdateStatusEnum =
  (typeof AdminCicUpdateStatusEnum)[keyof typeof AdminCicUpdateStatusEnum];

/**
 * @export
 */
export const AdminCicBoilerDemandEnum = {
  Heat: "heat",
} as const;
export type AdminCicBoilerDemandEnum =
  (typeof AdminCicBoilerDemandEnum)[keyof typeof AdminCicBoilerDemandEnum];

/**
 * @export
 */
export const AdminCicThermostatDemandEnum = {
  Heat: "heat",
} as const;
export type AdminCicThermostatDemandEnum =
  (typeof AdminCicThermostatDemandEnum)[keyof typeof AdminCicThermostatDemandEnum];

/**
 * @export
 */
export const AdminCicMenderUpdateStateEnum = {
  Idle: "idle",
  Download: "download",
  Install: "install",
} as const;
export type AdminCicMenderUpdateStateEnum =
  (typeof AdminCicMenderUpdateStateEnum)[keyof typeof AdminCicMenderUpdateStateEnum];

/**
 * Check if a given object implements the AdminCic interface.
 */
export function instanceOfAdminCic(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "lteConnectionStatus" in value;
  isInstance = isInstance && "cableConnectionStatus" in value;
  isInstance = isInstance && "wifiConnectionStatus" in value;
  isInstance = isInstance && "wifiSSID" in value;
  isInstance = isInstance && "availableWifiNetworks" in value;
  isInstance = isInstance && "lastScannedForWifi" in value;
  isInstance = isInstance && "isScanningForWifi" in value;
  isInstance = isInstance && "updateStatus" in value;
  isInstance = isInstance && "updateUntil" in value;
  isInstance = isInstance && "boilerDemand" in value;
  isInstance = isInstance && "boilerPower" in value;
  isInstance = isInstance && "boilerWaterTemperatureIn" in value;
  isInstance = isInstance && "boilerWaterTemperatureOut" in value;
  isInstance = isInstance && "boilerPressure" in value;
  isInstance = isInstance && "thermostatDemand" in value;
  isInstance = isInstance && "thermostatRoomTemperature" in value;
  isInstance = isInstance && "thermostatRoomTemperatureSetPoint" in value;
  isInstance = isInstance && "thermostatFlameOn" in value;
  isInstance = isInstance && "showThermostatTemperatures" in value;
  isInstance = isInstance && "boilerOn" in value;
  isInstance = isInstance && "thermostatControlTemperatureSetPoint" in value;
  isInstance = isInstance && "supplyTemperature" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "serial" in value;
  isInstance = isInstance && "numberOfHeatPumps" in value;
  isInstance = isInstance && "flowRate" in value;
  isInstance = isInstance && "electricityPrice" in value;
  isInstance = isInstance && "dayElectricityPrice" in value;
  isInstance = isInstance && "nightElectricityPrice" in value;
  isInstance = isInstance && "gasPrice" in value;
  isInstance = isInstance && "usePricingToLimitHeatPump" in value;
  isInstance = isInstance && "silentMode" in value;
  isInstance = isInstance && "heatPumps" in value;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "zipCode" in value;
  isInstance = isInstance && "orderNumber" in value;
  isInstance = isInstance && "wifiEnabled" in value;
  isInstance = isInstance && "addressStreet" in value;
  isInstance = isInstance && "heatDeliverySystems" in value;
  isInstance = isInstance && "thermostatType" in value;
  isInstance = isInstance && "boilerType" in value;
  isInstance = isInstance && "quattBuild" in value;
  isInstance = isInstance && "quattBuildRequired" in value;
  isInstance = isInstance && "needsUpdate" in value;
  isInstance = isInstance && "menderUpdateState" in value;
  isInstance = isInstance && "ratedMaximumHousePower" in value;
  isInstance = isInstance && "maximumHeatingOutdoorTemperature" in value;
  isInstance = isInstance && "lastCommissioning" in value;
  isInstance = isInstance && "menderId" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "lastConnectionStatusUpdatedAt" in value;

  return isInstance;
}

export function AdminCicFromJSON(json: any): AdminCic {
  return AdminCicFromJSONTyped(json, false);
}

export function AdminCicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminCic {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    lteConnectionStatus: ConnectionStatusFromJSON(json["lteConnectionStatus"]),
    cableConnectionStatus: ConnectionStatusFromJSON(
      json["cableConnectionStatus"],
    ),
    wifiConnectionStatus: ConnectionStatusFromJSON(
      json["wifiConnectionStatus"],
    ),
    wifiSSID: json["wifiSSID"],
    availableWifiNetworks:
      json["availableWifiNetworks"] === null
        ? null
        : (json["availableWifiNetworks"] as Array<any>).map(
            CicAvailableWifiNetworksInnerFromJSON,
          ),
    lastScannedForWifi:
      json["lastScannedForWifi"] === null
        ? null
        : new Date(json["lastScannedForWifi"]),
    isScanningForWifi: json["isScanningForWifi"],
    updateStatus: json["updateStatus"],
    updateUntil:
      json["updateUntil"] === null ? null : new Date(json["updateUntil"]),
    boilerDemand: json["boilerDemand"],
    boilerPower: json["boilerPower"],
    boilerWaterTemperatureIn: json["boilerWaterTemperatureIn"],
    boilerWaterTemperatureOut: json["boilerWaterTemperatureOut"],
    boilerPressure: json["boilerPressure"],
    thermostatDemand: json["thermostatDemand"],
    thermostatRoomTemperature: json["thermostatRoomTemperature"],
    thermostatRoomTemperatureSetPoint:
      json["thermostatRoomTemperatureSetPoint"],
    thermostatFlameOn: json["thermostatFlameOn"],
    showThermostatTemperatures: json["showThermostatTemperatures"],
    boilerOn: json["boilerOn"],
    thermostatControlTemperatureSetPoint:
      json["thermostatControlTemperatureSetPoint"],
    supplyTemperature: json["supplyTemperature"],
    status: CicStatusFromJSON(json["status"]),
    serial: json["serial"],
    numberOfHeatPumps: json["numberOfHeatPumps"],
    flowRate: json["flowRate"],
    electricityPrice: json["electricityPrice"],
    dayElectricityPrice: json["dayElectricityPrice"],
    nightElectricityPrice: json["nightElectricityPrice"],
    gasPrice: json["gasPrice"],
    usePricingToLimitHeatPump: json["usePricingToLimitHeatPump"],
    silentMode: SilentModeFromJSON(json["silentMode"]),
    heatPumps: (json["heatPumps"] as Array<any>).map(HeatPumpFromJSON),
    supervisoryControlMode: !exists(json, "supervisoryControlMode")
      ? undefined
      : json["supervisoryControlMode"],
    isHp1Connected: !exists(json, "isHp1Connected")
      ? undefined
      : json["isHp1Connected"],
    isHp2Connected: !exists(json, "isHp2Connected")
      ? undefined
      : json["isHp2Connected"],
    isThermostatConnected: !exists(json, "isThermostatConnected")
      ? undefined
      : json["isThermostatConnected"],
    isBoilerConnected: !exists(json, "isBoilerConnected")
      ? undefined
      : json["isBoilerConnected"],
    isTemperatureSensorConnected: !exists(json, "isTemperatureSensorConnected")
      ? undefined
      : json["isTemperatureSensorConnected"],
    isControllerAlive: !exists(json, "isControllerAlive")
      ? undefined
      : json["isControllerAlive"],
    name: json["name"],
    zipCode: json["zipCode"],
    orderNumber: json["orderNumber"],
    wifiEnabled: json["wifiEnabled"],
    addressStreet: json["addressStreet"],
    addressNumber: !exists(json, "addressNumber")
      ? undefined
      : json["addressNumber"],
    heatDeliverySystems:
      json["heatDeliverySystems"] === null
        ? null
        : (json["heatDeliverySystems"] as Array<any>).map(
            HeatDeliverySystemFromJSON,
          ),
    thermostatType: ThermostatTypeFromJSON(json["thermostatType"]),
    boilerType: BoilerTypeFromJSON(json["boilerType"]),
    quattBuild: json["quattBuild"],
    quattBuildRequired: json["quattBuildRequired"],
    needsUpdate: json["needsUpdate"],
    menderUpdateState: json["menderUpdateState"],
    ratedMaximumHousePower: json["ratedMaximumHousePower"],
    maximumHeatingOutdoorTemperature: json["maximumHeatingOutdoorTemperature"],
    lastCommissioning: InstallerCicAllOfLastCommissioningFromJSON(
      json["lastCommissioning"],
    ),
    menderId: json["menderId"],
    createdAt: new Date(json["createdAt"]),
    lastConnectionStatusUpdatedAt:
      json["lastConnectionStatusUpdatedAt"] === null
        ? null
        : new Date(json["lastConnectionStatusUpdatedAt"]),
  };
}

export function AdminCicToJSON(value?: AdminCic | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    lteConnectionStatus: ConnectionStatusToJSON(value.lteConnectionStatus),
    cableConnectionStatus: ConnectionStatusToJSON(value.cableConnectionStatus),
    wifiConnectionStatus: ConnectionStatusToJSON(value.wifiConnectionStatus),
    wifiSSID: value.wifiSSID,
    availableWifiNetworks:
      value.availableWifiNetworks === null
        ? null
        : (value.availableWifiNetworks as Array<any>).map(
            CicAvailableWifiNetworksInnerToJSON,
          ),
    lastScannedForWifi:
      value.lastScannedForWifi === null
        ? null
        : value.lastScannedForWifi.toISOString(),
    isScanningForWifi: value.isScanningForWifi,
    updateStatus: value.updateStatus,
    updateUntil:
      value.updateUntil === null ? null : value.updateUntil.toISOString(),
    boilerDemand: value.boilerDemand,
    boilerPower: value.boilerPower,
    boilerWaterTemperatureIn: value.boilerWaterTemperatureIn,
    boilerWaterTemperatureOut: value.boilerWaterTemperatureOut,
    boilerPressure: value.boilerPressure,
    thermostatDemand: value.thermostatDemand,
    thermostatRoomTemperature: value.thermostatRoomTemperature,
    thermostatRoomTemperatureSetPoint: value.thermostatRoomTemperatureSetPoint,
    thermostatFlameOn: value.thermostatFlameOn,
    showThermostatTemperatures: value.showThermostatTemperatures,
    boilerOn: value.boilerOn,
    thermostatControlTemperatureSetPoint:
      value.thermostatControlTemperatureSetPoint,
    supplyTemperature: value.supplyTemperature,
    status: CicStatusToJSON(value.status),
    serial: value.serial,
    numberOfHeatPumps: value.numberOfHeatPumps,
    flowRate: value.flowRate,
    electricityPrice: value.electricityPrice,
    dayElectricityPrice: value.dayElectricityPrice,
    nightElectricityPrice: value.nightElectricityPrice,
    gasPrice: value.gasPrice,
    usePricingToLimitHeatPump: value.usePricingToLimitHeatPump,
    silentMode: SilentModeToJSON(value.silentMode),
    heatPumps: (value.heatPumps as Array<any>).map(HeatPumpToJSON),
    supervisoryControlMode: value.supervisoryControlMode,
    isHp1Connected: value.isHp1Connected,
    isHp2Connected: value.isHp2Connected,
    isThermostatConnected: value.isThermostatConnected,
    isBoilerConnected: value.isBoilerConnected,
    isTemperatureSensorConnected: value.isTemperatureSensorConnected,
    isControllerAlive: value.isControllerAlive,
    name: value.name,
    zipCode: value.zipCode,
    orderNumber: value.orderNumber,
    wifiEnabled: value.wifiEnabled,
    addressStreet: value.addressStreet,
    addressNumber: value.addressNumber,
    heatDeliverySystems:
      value.heatDeliverySystems === null
        ? null
        : (value.heatDeliverySystems as Array<any>).map(
            HeatDeliverySystemToJSON,
          ),
    thermostatType: ThermostatTypeToJSON(value.thermostatType),
    boilerType: BoilerTypeToJSON(value.boilerType),
    quattBuild: value.quattBuild,
    quattBuildRequired: value.quattBuildRequired,
    needsUpdate: value.needsUpdate,
    menderUpdateState: value.menderUpdateState,
    ratedMaximumHousePower: value.ratedMaximumHousePower,
    maximumHeatingOutdoorTemperature: value.maximumHeatingOutdoorTemperature,
    lastCommissioning: InstallerCicAllOfLastCommissioningToJSON(
      value.lastCommissioning,
    ),
    menderId: value.menderId,
    createdAt: value.createdAt.toISOString(),
    lastConnectionStatusUpdatedAt:
      value.lastConnectionStatusUpdatedAt === null
        ? null
        : value.lastConnectionStatusUpdatedAt.toISOString(),
  };
}
