/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AdminReplaceChillInterfaceBoard400ResponseAllOfResult } from "./AdminReplaceChillInterfaceBoard400ResponseAllOfResult";
import {
  AdminReplaceChillInterfaceBoard400ResponseAllOfResultFromJSON,
  AdminReplaceChillInterfaceBoard400ResponseAllOfResultFromJSONTyped,
  AdminReplaceChillInterfaceBoard400ResponseAllOfResultToJSON,
} from "./AdminReplaceChillInterfaceBoard400ResponseAllOfResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface AdminReplaceChillInterfaceBoard400Response
 */
export interface AdminReplaceChillInterfaceBoard400Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof AdminReplaceChillInterfaceBoard400Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {AdminReplaceChillInterfaceBoard400ResponseAllOfResult}
   * @memberof AdminReplaceChillInterfaceBoard400Response
   */
  result: AdminReplaceChillInterfaceBoard400ResponseAllOfResult;
}

/**
 * Check if a given object implements the AdminReplaceChillInterfaceBoard400Response interface.
 */
export function instanceOfAdminReplaceChillInterfaceBoard400Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function AdminReplaceChillInterfaceBoard400ResponseFromJSON(
  json: any,
): AdminReplaceChillInterfaceBoard400Response {
  return AdminReplaceChillInterfaceBoard400ResponseFromJSONTyped(json, false);
}

export function AdminReplaceChillInterfaceBoard400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminReplaceChillInterfaceBoard400Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: AdminReplaceChillInterfaceBoard400ResponseAllOfResultFromJSON(
      json["result"],
    ),
  };
}

export function AdminReplaceChillInterfaceBoard400ResponseToJSON(
  value?: AdminReplaceChillInterfaceBoard400Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: AdminReplaceChillInterfaceBoard400ResponseAllOfResultToJSON(
      value.result,
    ),
  };
}
