/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AdminCreateTariff403ResponseAllOfResult } from "./AdminCreateTariff403ResponseAllOfResult";
import {
  AdminCreateTariff403ResponseAllOfResultFromJSON,
  AdminCreateTariff403ResponseAllOfResultFromJSONTyped,
  AdminCreateTariff403ResponseAllOfResultToJSON,
} from "./AdminCreateTariff403ResponseAllOfResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface AdminCreateTariff403Response
 */
export interface AdminCreateTariff403Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof AdminCreateTariff403Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {AdminCreateTariff403ResponseAllOfResult}
   * @memberof AdminCreateTariff403Response
   */
  result: AdminCreateTariff403ResponseAllOfResult;
}

/**
 * Check if a given object implements the AdminCreateTariff403Response interface.
 */
export function instanceOfAdminCreateTariff403Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function AdminCreateTariff403ResponseFromJSON(
  json: any,
): AdminCreateTariff403Response {
  return AdminCreateTariff403ResponseFromJSONTyped(json, false);
}

export function AdminCreateTariff403ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminCreateTariff403Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: AdminCreateTariff403ResponseAllOfResultFromJSON(json["result"]),
  };
}

export function AdminCreateTariff403ResponseToJSON(
  value?: AdminCreateTariff403Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: AdminCreateTariff403ResponseAllOfResultToJSON(value.result),
  };
}
