/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AdminGetInstallationSnowflakeInfo200ResponseResult } from "./AdminGetInstallationSnowflakeInfo200ResponseResult";
import {
  AdminGetInstallationSnowflakeInfo200ResponseResultFromJSON,
  AdminGetInstallationSnowflakeInfo200ResponseResultFromJSONTyped,
  AdminGetInstallationSnowflakeInfo200ResponseResultToJSON,
} from "./AdminGetInstallationSnowflakeInfo200ResponseResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface AdminGetInstallationSnowflakeInfo200Response
 */
export interface AdminGetInstallationSnowflakeInfo200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof AdminGetInstallationSnowflakeInfo200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {AdminGetInstallationSnowflakeInfo200ResponseResult}
   * @memberof AdminGetInstallationSnowflakeInfo200Response
   */
  result: AdminGetInstallationSnowflakeInfo200ResponseResult;
}

/**
 * Check if a given object implements the AdminGetInstallationSnowflakeInfo200Response interface.
 */
export function instanceOfAdminGetInstallationSnowflakeInfo200Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function AdminGetInstallationSnowflakeInfo200ResponseFromJSON(
  json: any,
): AdminGetInstallationSnowflakeInfo200Response {
  return AdminGetInstallationSnowflakeInfo200ResponseFromJSONTyped(json, false);
}

export function AdminGetInstallationSnowflakeInfo200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminGetInstallationSnowflakeInfo200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: AdminGetInstallationSnowflakeInfo200ResponseResultFromJSON(
      json["result"],
    ),
  };
}

export function AdminGetInstallationSnowflakeInfo200ResponseToJSON(
  value?: AdminGetInstallationSnowflakeInfo200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: AdminGetInstallationSnowflakeInfo200ResponseResultToJSON(
      value.result,
    ),
  };
}
