/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AdminCreateTariff404ResponseAllOfResult } from "./AdminCreateTariff404ResponseAllOfResult";
import {
  AdminCreateTariff404ResponseAllOfResultFromJSON,
  AdminCreateTariff404ResponseAllOfResultFromJSONTyped,
  AdminCreateTariff404ResponseAllOfResultToJSON,
} from "./AdminCreateTariff404ResponseAllOfResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface AdminCreateTariff404Response
 */
export interface AdminCreateTariff404Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof AdminCreateTariff404Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {AdminCreateTariff404ResponseAllOfResult}
   * @memberof AdminCreateTariff404Response
   */
  result: AdminCreateTariff404ResponseAllOfResult;
}

/**
 * Check if a given object implements the AdminCreateTariff404Response interface.
 */
export function instanceOfAdminCreateTariff404Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function AdminCreateTariff404ResponseFromJSON(
  json: any,
): AdminCreateTariff404Response {
  return AdminCreateTariff404ResponseFromJSONTyped(json, false);
}

export function AdminCreateTariff404ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminCreateTariff404Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: AdminCreateTariff404ResponseAllOfResultFromJSON(json["result"]),
  };
}

export function AdminCreateTariff404ResponseToJSON(
  value?: AdminCreateTariff404Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: AdminCreateTariff404ResponseAllOfResultToJSON(value.result),
  };
}
