/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ReplaceChillInterfaceBoardResponse } from "./ReplaceChillInterfaceBoardResponse";
import {
  ReplaceChillInterfaceBoardResponseFromJSON,
  ReplaceChillInterfaceBoardResponseFromJSONTyped,
  ReplaceChillInterfaceBoardResponseToJSON,
} from "./ReplaceChillInterfaceBoardResponse";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface AdminReplaceChillInterfaceBoard200Response
 */
export interface AdminReplaceChillInterfaceBoard200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof AdminReplaceChillInterfaceBoard200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {ReplaceChillInterfaceBoardResponse}
   * @memberof AdminReplaceChillInterfaceBoard200Response
   */
  result: ReplaceChillInterfaceBoardResponse;
}

/**
 * Check if a given object implements the AdminReplaceChillInterfaceBoard200Response interface.
 */
export function instanceOfAdminReplaceChillInterfaceBoard200Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function AdminReplaceChillInterfaceBoard200ResponseFromJSON(
  json: any,
): AdminReplaceChillInterfaceBoard200Response {
  return AdminReplaceChillInterfaceBoard200ResponseFromJSONTyped(json, false);
}

export function AdminReplaceChillInterfaceBoard200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminReplaceChillInterfaceBoard200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: ReplaceChillInterfaceBoardResponseFromJSON(json["result"]),
  };
}

export function AdminReplaceChillInterfaceBoard200ResponseToJSON(
  value?: AdminReplaceChillInterfaceBoard200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: ReplaceChillInterfaceBoardResponseToJSON(value.result),
  };
}
