/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminInstallationDetailAllOfCicCommissioning
 */
export interface AdminInstallationDetailAllOfCicCommissioning {
  /**
   *
   * @type {number}
   * @memberof AdminInstallationDetailAllOfCicCommissioning
   */
  id: number;
  /**
   *
   * @type {boolean}
   * @memberof AdminInstallationDetailAllOfCicCommissioning
   */
  isForced: boolean;
  /**
   *
   * @type {Date}
   * @memberof AdminInstallationDetailAllOfCicCommissioning
   */
  createdAt: Date;
}

/**
 * Check if a given object implements the AdminInstallationDetailAllOfCicCommissioning interface.
 */
export function instanceOfAdminInstallationDetailAllOfCicCommissioning(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "isForced" in value;
  isInstance = isInstance && "createdAt" in value;

  return isInstance;
}

export function AdminInstallationDetailAllOfCicCommissioningFromJSON(
  json: any,
): AdminInstallationDetailAllOfCicCommissioning {
  return AdminInstallationDetailAllOfCicCommissioningFromJSONTyped(json, false);
}

export function AdminInstallationDetailAllOfCicCommissioningFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminInstallationDetailAllOfCicCommissioning {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    isForced: json["isForced"],
    createdAt: new Date(json["createdAt"]),
  };
}

export function AdminInstallationDetailAllOfCicCommissioningToJSON(
  value?: AdminInstallationDetailAllOfCicCommissioning | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    isForced: value.isForced,
    createdAt: value.createdAt.toISOString(),
  };
}
