/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AdminListCics200ResponseResult } from "./AdminListCics200ResponseResult";
import {
  AdminListCics200ResponseResultFromJSON,
  AdminListCics200ResponseResultFromJSONTyped,
  AdminListCics200ResponseResultToJSON,
} from "./AdminListCics200ResponseResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface AdminListCics200Response
 */
export interface AdminListCics200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof AdminListCics200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {AdminListCics200ResponseResult}
   * @memberof AdminListCics200Response
   */
  result: AdminListCics200ResponseResult;
}

/**
 * Check if a given object implements the AdminListCics200Response interface.
 */
export function instanceOfAdminListCics200Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function AdminListCics200ResponseFromJSON(
  json: any,
): AdminListCics200Response {
  return AdminListCics200ResponseFromJSONTyped(json, false);
}

export function AdminListCics200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminListCics200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: AdminListCics200ResponseResultFromJSON(json["result"]),
  };
}

export function AdminListCics200ResponseToJSON(
  value?: AdminListCics200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: AdminListCics200ResponseResultToJSON(value.result),
  };
}
