/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminCreateTariff403ResponseAllOfResult
 */
export interface AdminCreateTariff403ResponseAllOfResult {
  /**
   *
   * @type {string}
   * @memberof AdminCreateTariff403ResponseAllOfResult
   */
  errorCode?: AdminCreateTariff403ResponseAllOfResultErrorCodeEnum;
}

/**
 * @export
 */
export const AdminCreateTariff403ResponseAllOfResultErrorCodeEnum = {
  UserHasNoPairedCic: "USER_HAS_NO_PAIRED_CIC",
} as const;
export type AdminCreateTariff403ResponseAllOfResultErrorCodeEnum =
  (typeof AdminCreateTariff403ResponseAllOfResultErrorCodeEnum)[keyof typeof AdminCreateTariff403ResponseAllOfResultErrorCodeEnum];

/**
 * Check if a given object implements the AdminCreateTariff403ResponseAllOfResult interface.
 */
export function instanceOfAdminCreateTariff403ResponseAllOfResult(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function AdminCreateTariff403ResponseAllOfResultFromJSON(
  json: any,
): AdminCreateTariff403ResponseAllOfResult {
  return AdminCreateTariff403ResponseAllOfResultFromJSONTyped(json, false);
}

export function AdminCreateTariff403ResponseAllOfResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminCreateTariff403ResponseAllOfResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    errorCode: !exists(json, "errorCode") ? undefined : json["errorCode"],
  };
}

export function AdminCreateTariff403ResponseAllOfResultToJSON(
  value?: AdminCreateTariff403ResponseAllOfResult | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    errorCode: value.errorCode,
  };
}
