/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AdminCic } from "./AdminCic";
import {
  AdminCicFromJSON,
  AdminCicFromJSONTyped,
  AdminCicToJSON,
} from "./AdminCic";

/**
 *
 * @export
 * @interface AdminListCics200ResponseResult
 */
export interface AdminListCics200ResponseResult {
  /**
   *
   * @type {Array<AdminCic>}
   * @memberof AdminListCics200ResponseResult
   */
  cics: Array<AdminCic>;
  /**
   *
   * @type {number}
   * @memberof AdminListCics200ResponseResult
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof AdminListCics200ResponseResult
   */
  page: number;
  /**
   *
   * @type {number}
   * @memberof AdminListCics200ResponseResult
   */
  pageSize: number;
  /**
   *
   * @type {number}
   * @memberof AdminListCics200ResponseResult
   */
  totalPages: number;
}

/**
 * Check if a given object implements the AdminListCics200ResponseResult interface.
 */
export function instanceOfAdminListCics200ResponseResult(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "cics" in value;
  isInstance = isInstance && "total" in value;
  isInstance = isInstance && "page" in value;
  isInstance = isInstance && "pageSize" in value;
  isInstance = isInstance && "totalPages" in value;

  return isInstance;
}

export function AdminListCics200ResponseResultFromJSON(
  json: any,
): AdminListCics200ResponseResult {
  return AdminListCics200ResponseResultFromJSONTyped(json, false);
}

export function AdminListCics200ResponseResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminListCics200ResponseResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    cics: (json["cics"] as Array<any>).map(AdminCicFromJSON),
    total: json["total"],
    page: json["page"],
    pageSize: json["pageSize"],
    totalPages: json["totalPages"],
  };
}

export function AdminListCics200ResponseResultToJSON(
  value?: AdminListCics200ResponseResult | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    cics: (value.cics as Array<any>).map(AdminCicToJSON),
    total: value.total,
    page: value.page,
    pageSize: value.pageSize,
    totalPages: value.totalPages,
  };
}
