/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminReplaceChillInterfaceBoard404ResponseAllOfResult
 */
export interface AdminReplaceChillInterfaceBoard404ResponseAllOfResult {
  /**
   *
   * @type {string}
   * @memberof AdminReplaceChillInterfaceBoard404ResponseAllOfResult
   */
  errorCode?: AdminReplaceChillInterfaceBoard404ResponseAllOfResultErrorCodeEnum;
}

/**
 * @export
 */
export const AdminReplaceChillInterfaceBoard404ResponseAllOfResultErrorCodeEnum =
  {
    DeviceNotFound: "CHILL_DEVICE_NOT_FOUND",
    InterfaceBoardNotInInventory: "CHILL_INTERFACE_BOARD_NOT_IN_INVENTORY",
  } as const;
export type AdminReplaceChillInterfaceBoard404ResponseAllOfResultErrorCodeEnum =
  (typeof AdminReplaceChillInterfaceBoard404ResponseAllOfResultErrorCodeEnum)[keyof typeof AdminReplaceChillInterfaceBoard404ResponseAllOfResultErrorCodeEnum];

/**
 * Check if a given object implements the AdminReplaceChillInterfaceBoard404ResponseAllOfResult interface.
 */
export function instanceOfAdminReplaceChillInterfaceBoard404ResponseAllOfResult(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function AdminReplaceChillInterfaceBoard404ResponseAllOfResultFromJSON(
  json: any,
): AdminReplaceChillInterfaceBoard404ResponseAllOfResult {
  return AdminReplaceChillInterfaceBoard404ResponseAllOfResultFromJSONTyped(
    json,
    false,
  );
}

export function AdminReplaceChillInterfaceBoard404ResponseAllOfResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminReplaceChillInterfaceBoard404ResponseAllOfResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    errorCode: !exists(json, "errorCode") ? undefined : json["errorCode"],
  };
}

export function AdminReplaceChillInterfaceBoard404ResponseAllOfResultToJSON(
  value?: AdminReplaceChillInterfaceBoard404ResponseAllOfResult | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    errorCode: value.errorCode,
  };
}
