/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AppCompatibilityGet200ResponseResult
 */
export interface AppCompatibilityGet200ResponseResult {
  /**
   *
   * @type {boolean}
   * @memberof AppCompatibilityGet200ResponseResult
   */
  isCompatible: boolean;
}

/**
 * Check if a given object implements the AppCompatibilityGet200ResponseResult interface.
 */
export function instanceOfAppCompatibilityGet200ResponseResult(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "isCompatible" in value;

  return isInstance;
}

export function AppCompatibilityGet200ResponseResultFromJSON(
  json: any,
): AppCompatibilityGet200ResponseResult {
  return AppCompatibilityGet200ResponseResultFromJSONTyped(json, false);
}

export function AppCompatibilityGet200ResponseResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppCompatibilityGet200ResponseResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    isCompatible: json["isCompatible"],
  };
}

export function AppCompatibilityGet200ResponseResultToJSON(
  value?: AppCompatibilityGet200ResponseResult | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    isCompatible: value.isCompatible,
  };
}
