/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BaseCommissioning
 */
export interface BaseCommissioning {
  /**
   *
   * @type {string}
   * @memberof BaseCommissioning
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof BaseCommissioning
   */
  status: BaseCommissioningStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof BaseCommissioning
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof BaseCommissioning
   */
  endedAt: Date | null;
  /**
   *
   * @type {boolean}
   * @memberof BaseCommissioning
   */
  forced: boolean;
  /**
   *
   * @type {string}
   * @memberof BaseCommissioning
   */
  installationUuid: string;
  /**
   *
   * @type {string}
   * @memberof BaseCommissioning
   */
  installerUuid: string;
}

/**
 * @export
 */
export const BaseCommissioningStatusEnum = {
  Success: "SUCCESS",
  Failed: "FAILED",
  InProgress: "IN_PROGRESS",
  Cancelled: "CANCELLED",
} as const;
export type BaseCommissioningStatusEnum =
  (typeof BaseCommissioningStatusEnum)[keyof typeof BaseCommissioningStatusEnum];

/**
 * Check if a given object implements the BaseCommissioning interface.
 */
export function instanceOfBaseCommissioning(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "endedAt" in value;
  isInstance = isInstance && "forced" in value;
  isInstance = isInstance && "installationUuid" in value;
  isInstance = isInstance && "installerUuid" in value;

  return isInstance;
}

export function BaseCommissioningFromJSON(json: any): BaseCommissioning {
  return BaseCommissioningFromJSONTyped(json, false);
}

export function BaseCommissioningFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BaseCommissioning {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    status: json["status"],
    createdAt: new Date(json["createdAt"]),
    endedAt: json["endedAt"] === null ? null : new Date(json["endedAt"]),
    forced: json["forced"],
    installationUuid: json["installationUuid"],
    installerUuid: json["installerUuid"],
  };
}

export function BaseCommissioningToJSON(value?: BaseCommissioning | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    status: value.status,
    createdAt: value.createdAt.toISOString(),
    endedAt: value.endedAt === null ? null : value.endedAt.toISOString(),
    forced: value.forced,
    installationUuid: value.installationUuid,
    installerUuid: value.installerUuid,
  };
}
