/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { PreHeating } from "./PreHeating";
import {
  PreHeatingFromJSON,
  PreHeatingFromJSONTyped,
  PreHeatingToJSON,
} from "./PreHeating";

/**
 * The live data from the heat charger
 * @export
 * @interface ChargingBoostHeatChargerAllOfLiveData
 */
export interface ChargingBoostHeatChargerAllOfLiveData {
  /**
   *
   * @type {Date}
   * @memberof ChargingBoostHeatChargerAllOfLiveData
   */
  lastUpdatedAt: Date;
  /**
   *
   * @type {PreHeating}
   * @memberof ChargingBoostHeatChargerAllOfLiveData
   */
  preHeating: PreHeating | null;
  /**
   * The battery top temperature in celsius
   * @type {number}
   * @memberof ChargingBoostHeatChargerAllOfLiveData
   */
  heatBatteryTopTemperature: number | null;
}

/**
 * Check if a given object implements the ChargingBoostHeatChargerAllOfLiveData interface.
 */
export function instanceOfChargingBoostHeatChargerAllOfLiveData(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "lastUpdatedAt" in value;
  isInstance = isInstance && "preHeating" in value;
  isInstance = isInstance && "heatBatteryTopTemperature" in value;

  return isInstance;
}

export function ChargingBoostHeatChargerAllOfLiveDataFromJSON(
  json: any,
): ChargingBoostHeatChargerAllOfLiveData {
  return ChargingBoostHeatChargerAllOfLiveDataFromJSONTyped(json, false);
}

export function ChargingBoostHeatChargerAllOfLiveDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChargingBoostHeatChargerAllOfLiveData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    lastUpdatedAt: new Date(json["lastUpdatedAt"]),
    preHeating: PreHeatingFromJSON(json["preHeating"]),
    heatBatteryTopTemperature: json["heatBatteryTopTemperature"],
  };
}

export function ChargingBoostHeatChargerAllOfLiveDataToJSON(
  value?: ChargingBoostHeatChargerAllOfLiveData | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    lastUpdatedAt: value.lastUpdatedAt.toISOString(),
    preHeating: PreHeatingToJSON(value.preHeating),
    heatBatteryTopTemperature: value.heatBatteryTopTemperature,
  };
}
