/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CommissioningTestType } from "./CommissioningTestType";
import {
  CommissioningTestTypeFromJSON,
  CommissioningTestTypeFromJSONTyped,
  CommissioningTestTypeToJSON,
} from "./CommissioningTestType";
import type { FillHeatBatteryAllOfLiveData } from "./FillHeatBatteryAllOfLiveData";
import {
  FillHeatBatteryAllOfLiveDataFromJSON,
  FillHeatBatteryAllOfLiveDataFromJSONTyped,
  FillHeatBatteryAllOfLiveDataToJSON,
} from "./FillHeatBatteryAllOfLiveData";

/**
 *
 * @export
 * @interface CheckHeatBatteryFilled
 */
export interface CheckHeatBatteryFilled {
  /**
   *
   * @type {string}
   * @memberof CheckHeatBatteryFilled
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof CheckHeatBatteryFilled
   */
  status: CheckHeatBatteryFilledStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof CheckHeatBatteryFilled
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof CheckHeatBatteryFilled
   */
  startedAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof CheckHeatBatteryFilled
   */
  updatedAt: Date;
  /**
   *
   * @type {Date}
   * @memberof CheckHeatBatteryFilled
   */
  endedAt: Date | null;
  /**
   *
   * @type {boolean}
   * @memberof CheckHeatBatteryFilled
   */
  forced: boolean;
  /**
   *
   * @type {string}
   * @memberof CheckHeatBatteryFilled
   */
  commissioningUuid: string;
  /**
   *
   * @type {CommissioningTestType}
   * @memberof CheckHeatBatteryFilled
   */
  type: CommissioningTestType;
  /**
   *
   * @type {string}
   * @memberof CheckHeatBatteryFilled
   */
  installerUuid: string;
  /**
   *
   * @type {number}
   * @memberof CheckHeatBatteryFilled
   */
  step: number;
  /**
   *
   * @type {Date}
   * @memberof CheckHeatBatteryFilled
   */
  maximumDatetime: Date;
  /**
   *
   * @type {FillHeatBatteryAllOfLiveData}
   * @memberof CheckHeatBatteryFilled
   */
  liveData: FillHeatBatteryAllOfLiveData | null;
}

/**
 * @export
 */
export const CheckHeatBatteryFilledStatusEnum = {
  Success: "SUCCESS",
  Failed: "FAILED",
  InProgress: "IN_PROGRESS",
  Cancelled: "CANCELLED",
  Waiting: "WAITING",
  Ready: "READY",
  Validated: "VALIDATED",
} as const;
export type CheckHeatBatteryFilledStatusEnum =
  (typeof CheckHeatBatteryFilledStatusEnum)[keyof typeof CheckHeatBatteryFilledStatusEnum];

/**
 * Check if a given object implements the CheckHeatBatteryFilled interface.
 */
export function instanceOfCheckHeatBatteryFilled(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "startedAt" in value;
  isInstance = isInstance && "updatedAt" in value;
  isInstance = isInstance && "endedAt" in value;
  isInstance = isInstance && "forced" in value;
  isInstance = isInstance && "commissioningUuid" in value;
  isInstance = isInstance && "type" in value;
  isInstance = isInstance && "installerUuid" in value;
  isInstance = isInstance && "step" in value;
  isInstance = isInstance && "maximumDatetime" in value;
  isInstance = isInstance && "liveData" in value;

  return isInstance;
}

export function CheckHeatBatteryFilledFromJSON(
  json: any,
): CheckHeatBatteryFilled {
  return CheckHeatBatteryFilledFromJSONTyped(json, false);
}

export function CheckHeatBatteryFilledFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckHeatBatteryFilled {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    status: json["status"],
    createdAt: new Date(json["createdAt"]),
    startedAt: json["startedAt"] === null ? null : new Date(json["startedAt"]),
    updatedAt: new Date(json["updatedAt"]),
    endedAt: json["endedAt"] === null ? null : new Date(json["endedAt"]),
    forced: json["forced"],
    commissioningUuid: json["commissioningUuid"],
    type: CommissioningTestTypeFromJSON(json["type"]),
    installerUuid: json["installerUuid"],
    step: json["step"],
    maximumDatetime: new Date(json["maximumDatetime"]),
    liveData: FillHeatBatteryAllOfLiveDataFromJSON(json["liveData"]),
  };
}

export function CheckHeatBatteryFilledToJSON(
  value?: CheckHeatBatteryFilled | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    status: value.status,
    createdAt: value.createdAt.toISOString(),
    startedAt: value.startedAt === null ? null : value.startedAt.toISOString(),
    updatedAt: value.updatedAt.toISOString(),
    endedAt: value.endedAt === null ? null : value.endedAt.toISOString(),
    forced: value.forced,
    commissioningUuid: value.commissioningUuid,
    type: CommissioningTestTypeToJSON(value.type),
    installerUuid: value.installerUuid,
    step: value.step,
    maximumDatetime: value.maximumDatetime.toISOString(),
    liveData: FillHeatBatteryAllOfLiveDataToJSON(value.liveData),
  };
}
