/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * Chill Interface Board with lifecycle information
 * @export
 * @interface ChillInterfaceBoard
 */
export interface ChillInterfaceBoard {
  /**
   * Unique identifier with CHI- prefix
   * @type {string}
   * @memberof ChillInterfaceBoard
   */
  uuid: string;
  /**
   * Associated CHILL device UUID (NULL = inventory)
   * @type {string}
   * @memberof ChillInterfaceBoard
   */
  chillDeviceUuid?: string | null;
  /**
   * Extended Unique Identifier (ASCII-HEX 8 bytes)
   * @type {string}
   * @memberof ChillInterfaceBoard
   */
  eui64: string;
  /**
   * Thread Pre-Shared Key (ASCII-HEX 32 bytes)
   * @type {string}
   * @memberof ChillInterfaceBoard
   */
  pskThread: string;
  /**
   * DTLS Pre-Shared Key (ASCII-HEX 32 bytes)
   * @type {string}
   * @memberof ChillInterfaceBoard
   */
  pskDTLS: string;
  /**
   * PCB hardware version
   * @type {string}
   * @memberof ChillInterfaceBoard
   */
  pcbHwVersion: string;
  /**
   * Timestamp when board was first activated (NULL = inventory)
   * @type {Date}
   * @memberof ChillInterfaceBoard
   */
  activatedAt?: Date | null;
  /**
   * Timestamp when board was deactivated/replaced (NULL = active)
   * @type {Date}
   * @memberof ChillInterfaceBoard
   */
  deactivatedAt?: Date | null;
  /**
   * Timestamp when board was created in system
   * @type {Date}
   * @memberof ChillInterfaceBoard
   */
  createdAt: Date;
  /**
   * Timestamp when board was last updated
   * @type {Date}
   * @memberof ChillInterfaceBoard
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the ChillInterfaceBoard interface.
 */
export function instanceOfChillInterfaceBoard(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "eui64" in value;
  isInstance = isInstance && "pskThread" in value;
  isInstance = isInstance && "pskDTLS" in value;
  isInstance = isInstance && "pcbHwVersion" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "updatedAt" in value;

  return isInstance;
}

export function ChillInterfaceBoardFromJSON(json: any): ChillInterfaceBoard {
  return ChillInterfaceBoardFromJSONTyped(json, false);
}

export function ChillInterfaceBoardFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChillInterfaceBoard {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    chillDeviceUuid: !exists(json, "chillDeviceUuid")
      ? undefined
      : json["chillDeviceUuid"],
    eui64: json["eui64"],
    pskThread: json["pskThread"],
    pskDTLS: json["pskDTLS"],
    pcbHwVersion: json["pcbHwVersion"],
    activatedAt: !exists(json, "activatedAt")
      ? undefined
      : json["activatedAt"] === null
        ? null
        : new Date(json["activatedAt"]),
    deactivatedAt: !exists(json, "deactivatedAt")
      ? undefined
      : json["deactivatedAt"] === null
        ? null
        : new Date(json["deactivatedAt"]),
    createdAt: new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
  };
}

export function ChillInterfaceBoardToJSON(
  value?: ChillInterfaceBoard | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    chillDeviceUuid: value.chillDeviceUuid,
    eui64: value.eui64,
    pskThread: value.pskThread,
    pskDTLS: value.pskDTLS,
    pcbHwVersion: value.pcbHwVersion,
    activatedAt:
      value.activatedAt === undefined
        ? undefined
        : value.activatedAt === null
          ? null
          : value.activatedAt.toISOString(),
    deactivatedAt:
      value.deactivatedAt === undefined
        ? undefined
        : value.deactivatedAt === null
          ? null
          : value.deactivatedAt.toISOString(),
    createdAt: value.createdAt.toISOString(),
    updatedAt: value.updatedAt.toISOString(),
  };
}
