/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CicAggregate } from "./CicAggregate";
import {
  CicAggregateFromJSON,
  CicAggregateFromJSONTyped,
  CicAggregateToJSON,
} from "./CicAggregate";

/**
 *
 * @export
 * @interface CicAggregateByCategory
 */
export interface CicAggregateByCategory {
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByCategory
   */
  settings: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByCategory
   */
  connectivity: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByCategory
   */
  heatpump: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByCategory
   */
  io_connectivity: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByCategory
   */
  cic_software: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByCategory
   */
  updates: CicAggregate;
  /**
   *
   * @type {CicAggregate}
   * @memberof CicAggregateByCategory
   */
  controller: CicAggregate;
}

/**
 * Check if a given object implements the CicAggregateByCategory interface.
 */
export function instanceOfCicAggregateByCategory(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "settings" in value;
  isInstance = isInstance && "connectivity" in value;
  isInstance = isInstance && "heatpump" in value;
  isInstance = isInstance && "io_connectivity" in value;
  isInstance = isInstance && "cic_software" in value;
  isInstance = isInstance && "updates" in value;
  isInstance = isInstance && "controller" in value;

  return isInstance;
}

export function CicAggregateByCategoryFromJSON(
  json: any,
): CicAggregateByCategory {
  return CicAggregateByCategoryFromJSONTyped(json, false);
}

export function CicAggregateByCategoryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CicAggregateByCategory {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    settings: CicAggregateFromJSON(json["settings"]),
    connectivity: CicAggregateFromJSON(json["connectivity"]),
    heatpump: CicAggregateFromJSON(json["heatpump"]),
    io_connectivity: CicAggregateFromJSON(json["io_connectivity"]),
    cic_software: CicAggregateFromJSON(json["cic_software"]),
    updates: CicAggregateFromJSON(json["updates"]),
    controller: CicAggregateFromJSON(json["controller"]),
  };
}

export function CicAggregateByCategoryToJSON(
  value?: CicAggregateByCategory | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    settings: CicAggregateToJSON(value.settings),
    connectivity: CicAggregateToJSON(value.connectivity),
    heatpump: CicAggregateToJSON(value.heatpump),
    io_connectivity: CicAggregateToJSON(value.io_connectivity),
    cic_software: CicAggregateToJSON(value.cic_software),
    updates: CicAggregateToJSON(value.updates),
    controller: CicAggregateToJSON(value.controller),
  };
}
