/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CicAggregate } from "./CicAggregate";
import {
  CicAggregateFromJSON,
  CicAggregateFromJSONTyped,
  CicAggregateToJSON,
} from "./CicAggregate";
import type { CicAggregateByCategory } from "./CicAggregateByCategory";
import {
  CicAggregateByCategoryFromJSON,
  CicAggregateByCategoryFromJSONTyped,
  CicAggregateByCategoryToJSON,
} from "./CicAggregateByCategory";
import type { CicAggregateByKpi } from "./CicAggregateByKpi";
import {
  CicAggregateByKpiFromJSON,
  CicAggregateByKpiFromJSONTyped,
  CicAggregateByKpiToJSON,
} from "./CicAggregateByKpi";

/**
 *
 * @export
 * @interface CicDashboardAggregate
 */
export interface CicDashboardAggregate {
  /**
   *
   * @type {CicAggregate}
   * @memberof CicDashboardAggregate
   */
  aggregate: CicAggregate;
  /**
   *
   * @type {CicAggregateByCategory}
   * @memberof CicDashboardAggregate
   */
  aggregateByCategory: CicAggregateByCategory;
  /**
   *
   * @type {CicAggregateByKpi}
   * @memberof CicDashboardAggregate
   */
  aggregateByKpi: CicAggregateByKpi;
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof CicDashboardAggregate
   */
  aggregateByVersion: { [key: string]: number };
  /**
   * Latest Quatt build
   * @type {string}
   * @memberof CicDashboardAggregate
   */
  latestVersion?: string;
  /**
   * Minimum required Quatt build
   * @type {string}
   * @memberof CicDashboardAggregate
   */
  requiredVersion?: string;
}

/**
 * Check if a given object implements the CicDashboardAggregate interface.
 */
export function instanceOfCicDashboardAggregate(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "aggregate" in value;
  isInstance = isInstance && "aggregateByCategory" in value;
  isInstance = isInstance && "aggregateByKpi" in value;
  isInstance = isInstance && "aggregateByVersion" in value;

  return isInstance;
}

export function CicDashboardAggregateFromJSON(
  json: any,
): CicDashboardAggregate {
  return CicDashboardAggregateFromJSONTyped(json, false);
}

export function CicDashboardAggregateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CicDashboardAggregate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    aggregate: CicAggregateFromJSON(json["aggregate"]),
    aggregateByCategory: CicAggregateByCategoryFromJSON(
      json["aggregateByCategory"],
    ),
    aggregateByKpi: CicAggregateByKpiFromJSON(json["aggregateByKpi"]),
    aggregateByVersion: json["aggregateByVersion"],
    latestVersion: !exists(json, "latestVersion")
      ? undefined
      : json["latestVersion"],
    requiredVersion: !exists(json, "requiredVersion")
      ? undefined
      : json["requiredVersion"],
  };
}

export function CicDashboardAggregateToJSON(
  value?: CicDashboardAggregate | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    aggregate: CicAggregateToJSON(value.aggregate),
    aggregateByCategory: CicAggregateByCategoryToJSON(
      value.aggregateByCategory,
    ),
    aggregateByKpi: CicAggregateByKpiToJSON(value.aggregateByKpi),
    aggregateByVersion: value.aggregateByVersion,
    latestVersion: value.latestVersion,
    requiredVersion: value.requiredVersion,
  };
}
