/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ClickhouseDataModeReparation } from "./ClickhouseDataModeReparation";
import {
  ClickhouseDataModeReparationFromJSON,
  ClickhouseDataModeReparationFromJSONTyped,
  ClickhouseDataModeReparationToJSON,
} from "./ClickhouseDataModeReparation";

/**
 *
 * @export
 * @interface ClickhouseData
 */
export interface ClickhouseData {
  /**
   *
   * @type {number}
   * @memberof ClickhouseData
   */
  roomTemperature: number | null;
  /**
   *
   * @type {number}
   * @memberof ClickhouseData
   */
  roomSetpoint: number | null;
  /**
   *
   * @type {number}
   * @memberof ClickhouseData
   */
  setpointAdherence: number | null;
  /**
   *
   * @type {ClickhouseDataModeReparation}
   * @memberof ClickhouseData
   */
  modeReparation: ClickhouseDataModeReparation | null;
}

/**
 * Check if a given object implements the ClickhouseData interface.
 */
export function instanceOfClickhouseData(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "roomTemperature" in value;
  isInstance = isInstance && "roomSetpoint" in value;
  isInstance = isInstance && "setpointAdherence" in value;
  isInstance = isInstance && "modeReparation" in value;

  return isInstance;
}

export function ClickhouseDataFromJSON(json: any): ClickhouseData {
  return ClickhouseDataFromJSONTyped(json, false);
}

export function ClickhouseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ClickhouseData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    roomTemperature: json["roomTemperature"],
    roomSetpoint: json["roomSetpoint"],
    setpointAdherence: json["setpointAdherence"],
    modeReparation: ClickhouseDataModeReparationFromJSON(
      json["modeReparation"],
    ),
  };
}

export function ClickhouseDataToJSON(value?: ClickhouseData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    roomTemperature: value.roomTemperature,
    roomSetpoint: value.roomSetpoint,
    setpointAdherence: value.setpointAdherence,
    modeReparation: ClickhouseDataModeReparationToJSON(value.modeReparation),
  };
}
