/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { DeviceType } from "./DeviceType";
import {
  DeviceTypeFromJSON,
  DeviceTypeFromJSONTyped,
  DeviceTypeToJSON,
} from "./DeviceType";

/**
 *
 * @export
 * @interface CommissioningStepDeviceConfiguration
 */
export interface CommissioningStepDeviceConfiguration {
  /**
   *
   * @type {string}
   * @memberof CommissioningStepDeviceConfiguration
   */
  type: CommissioningStepDeviceConfigurationTypeEnum;
  /**
   *
   * @type {DeviceType}
   * @memberof CommissioningStepDeviceConfiguration
   */
  deviceType?: DeviceType;
  /**
   *
   * @type {string}
   * @memberof CommissioningStepDeviceConfiguration
   */
  deviceUuid?: string;
}

/**
 * @export
 */
export const CommissioningStepDeviceConfigurationTypeEnum = {
  DeviceConfiguration: "DEVICE_CONFIGURATION",
} as const;
export type CommissioningStepDeviceConfigurationTypeEnum =
  (typeof CommissioningStepDeviceConfigurationTypeEnum)[keyof typeof CommissioningStepDeviceConfigurationTypeEnum];

/**
 * Check if a given object implements the CommissioningStepDeviceConfiguration interface.
 */
export function instanceOfCommissioningStepDeviceConfiguration(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "type" in value;

  return isInstance;
}

export function CommissioningStepDeviceConfigurationFromJSON(
  json: any,
): CommissioningStepDeviceConfiguration {
  return CommissioningStepDeviceConfigurationFromJSONTyped(json, false);
}

export function CommissioningStepDeviceConfigurationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CommissioningStepDeviceConfiguration {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: json["type"],
    deviceType: !exists(json, "deviceType")
      ? undefined
      : DeviceTypeFromJSON(json["deviceType"]),
    deviceUuid: !exists(json, "deviceUuid") ? undefined : json["deviceUuid"],
  };
}

export function CommissioningStepDeviceConfigurationToJSON(
  value?: CommissioningStepDeviceConfiguration | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    deviceType: DeviceTypeToJSON(value.deviceType),
    deviceUuid: value.deviceUuid,
  };
}
