/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { HybridActiveCommissioningMode } from "./HybridActiveCommissioningMode";
import {
  HybridActiveCommissioningModeFromJSON,
  HybridActiveCommissioningModeFromJSONTyped,
  HybridActiveCommissioningModeToJSON,
} from "./HybridActiveCommissioningMode";

/**
 *
 * @export
 * @interface CommissioningStepTest
 */
export interface CommissioningStepTest {
  /**
   *
   * @type {string}
   * @memberof CommissioningStepTest
   */
  type: CommissioningStepTestTypeEnum;
  /**
   *
   * @type {string}
   * @memberof CommissioningStepTest
   */
  commissioningTestUuid: string | null;
  /**
   *
   * @type {HybridActiveCommissioningMode}
   * @memberof CommissioningStepTest
   */
  hybridCommissioningMode?: HybridActiveCommissioningMode | null;
}

/**
 * @export
 */
export const CommissioningStepTestTypeEnum = {
  Test: "TEST",
} as const;
export type CommissioningStepTestTypeEnum =
  (typeof CommissioningStepTestTypeEnum)[keyof typeof CommissioningStepTestTypeEnum];

/**
 * Check if a given object implements the CommissioningStepTest interface.
 */
export function instanceOfCommissioningStepTest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "type" in value;
  isInstance = isInstance && "commissioningTestUuid" in value;

  return isInstance;
}

export function CommissioningStepTestFromJSON(
  json: any,
): CommissioningStepTest {
  return CommissioningStepTestFromJSONTyped(json, false);
}

export function CommissioningStepTestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CommissioningStepTest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: json["type"],
    commissioningTestUuid: json["commissioningTestUuid"],
    hybridCommissioningMode: !exists(json, "hybridCommissioningMode")
      ? undefined
      : HybridActiveCommissioningModeFromJSON(json["hybridCommissioningMode"]),
  };
}

export function CommissioningStepTestToJSON(
  value?: CommissioningStepTest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    commissioningTestUuid: value.commissioningTestUuid,
    hybridCommissioningMode: HybridActiveCommissioningModeToJSON(
      value.hybridCommissioningMode,
    ),
  };
}
