/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const CommissioningActionType = {
  HomeBatteryBindSystem: "HOME_BATTERY_BIND_SYSTEM",
  HomeBatteryUpdateBatteryInfo: "HOME_BATTERY_UPDATE_BATTERY_INFO",
  EmsCreateDigitalTwin: "EMS_CREATE_DIGITAL_TWIN",
} as const;
export type CommissioningActionType =
  (typeof CommissioningActionType)[keyof typeof CommissioningActionType];

export function CommissioningActionTypeFromJSON(
  json: any,
): CommissioningActionType {
  return CommissioningActionTypeFromJSONTyped(json, false);
}

export function CommissioningActionTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CommissioningActionType {
  return json as CommissioningActionType;
}

export function CommissioningActionTypeToJSON(
  value?: CommissioningActionType | null,
): any {
  return value as any;
}
