/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { BaseCommissioningTest } from "./BaseCommissioningTest";
import {
  BaseCommissioningTestFromJSON,
  BaseCommissioningTestFromJSONTyped,
  BaseCommissioningTestToJSON,
} from "./BaseCommissioningTest";
import type { BaseDevice } from "./BaseDevice";
import {
  BaseDeviceFromJSON,
  BaseDeviceFromJSONTyped,
  BaseDeviceToJSON,
} from "./BaseDevice";
import type { CommissioningInProgressAllOfInstallation } from "./CommissioningInProgressAllOfInstallation";
import {
  CommissioningInProgressAllOfInstallationFromJSON,
  CommissioningInProgressAllOfInstallationFromJSONTyped,
  CommissioningInProgressAllOfInstallationToJSON,
} from "./CommissioningInProgressAllOfInstallation";
import type { CommissioningStep } from "./CommissioningStep";
import {
  CommissioningStepFromJSON,
  CommissioningStepFromJSONTyped,
  CommissioningStepToJSON,
} from "./CommissioningStep";
import type { DevicesConfiguration } from "./DevicesConfiguration";
import {
  DevicesConfigurationFromJSON,
  DevicesConfigurationFromJSONTyped,
  DevicesConfigurationToJSON,
} from "./DevicesConfiguration";

/**
 *
 * @export
 * @interface CommissioningInProgress
 */
export interface CommissioningInProgress {
  /**
   * To allow retro compatibility for CommissioningInProgress we generate a "fake" uuid for the Hybrid commissioning, with format COM-HYBRID-{cicCommissioningId}, the commissioningUuid remains the same.
   * @type {string}
   * @memberof CommissioningInProgress
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof CommissioningInProgress
   */
  status: CommissioningInProgressStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof CommissioningInProgress
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof CommissioningInProgress
   */
  endedAt: Date | null;
  /**
   *
   * @type {boolean}
   * @memberof CommissioningInProgress
   */
  forced: boolean;
  /**
   *
   * @type {string}
   * @memberof CommissioningInProgress
   */
  installationUuid: string;
  /**
   *
   * @type {string}
   * @memberof CommissioningInProgress
   */
  installerUuid: string;
  /**
   *
   * @type {DevicesConfiguration}
   * @memberof CommissioningInProgress
   */
  devicesConfiguration: DevicesConfiguration;
  /**
   *
   * @type {CommissioningInProgressAllOfInstallation}
   * @memberof CommissioningInProgress
   */
  installation: CommissioningInProgressAllOfInstallation;
  /**
   *
   * @type {string}
   * @memberof CommissioningInProgress
   */
  cicUuid: string;
  /**
   *
   * @type {CommissioningStep}
   * @memberof CommissioningInProgress
   */
  step: CommissioningStep;
  /**
   *
   * @type {Array<BaseDevice>}
   * @memberof CommissioningInProgress
   */
  devices: Array<BaseDevice> | null;
  /**
   *
   * @type {Array<BaseCommissioningTest>}
   * @memberof CommissioningInProgress
   */
  tests: Array<BaseCommissioningTest> | null;
}

/**
 * @export
 */
export const CommissioningInProgressStatusEnum = {
  InProgress: "IN_PROGRESS",
} as const;
export type CommissioningInProgressStatusEnum =
  (typeof CommissioningInProgressStatusEnum)[keyof typeof CommissioningInProgressStatusEnum];

/**
 * Check if a given object implements the CommissioningInProgress interface.
 */
export function instanceOfCommissioningInProgress(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "endedAt" in value;
  isInstance = isInstance && "forced" in value;
  isInstance = isInstance && "installationUuid" in value;
  isInstance = isInstance && "installerUuid" in value;
  isInstance = isInstance && "devicesConfiguration" in value;
  isInstance = isInstance && "installation" in value;
  isInstance = isInstance && "cicUuid" in value;
  isInstance = isInstance && "step" in value;
  isInstance = isInstance && "devices" in value;
  isInstance = isInstance && "tests" in value;

  return isInstance;
}

export function CommissioningInProgressFromJSON(
  json: any,
): CommissioningInProgress {
  return CommissioningInProgressFromJSONTyped(json, false);
}

export function CommissioningInProgressFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CommissioningInProgress {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    status: json["status"],
    createdAt: new Date(json["createdAt"]),
    endedAt: json["endedAt"] === null ? null : new Date(json["endedAt"]),
    forced: json["forced"],
    installationUuid: json["installationUuid"],
    installerUuid: json["installerUuid"],
    devicesConfiguration: DevicesConfigurationFromJSON(
      json["devicesConfiguration"],
    ),
    installation: CommissioningInProgressAllOfInstallationFromJSON(
      json["installation"],
    ),
    cicUuid: json["cicUuid"],
    step: CommissioningStepFromJSON(json["step"]),
    devices:
      json["devices"] === null
        ? null
        : (json["devices"] as Array<any>).map(BaseDeviceFromJSON),
    tests:
      json["tests"] === null
        ? null
        : (json["tests"] as Array<any>).map(BaseCommissioningTestFromJSON),
  };
}

export function CommissioningInProgressToJSON(
  value?: CommissioningInProgress | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    status: value.status,
    createdAt: value.createdAt.toISOString(),
    endedAt: value.endedAt === null ? null : value.endedAt.toISOString(),
    forced: value.forced,
    installationUuid: value.installationUuid,
    installerUuid: value.installerUuid,
    devicesConfiguration: DevicesConfigurationToJSON(
      value.devicesConfiguration,
    ),
    installation: CommissioningInProgressAllOfInstallationToJSON(
      value.installation,
    ),
    cicUuid: value.cicUuid,
    step: CommissioningStepToJSON(value.step),
    devices:
      value.devices === null
        ? null
        : (value.devices as Array<any>).map(BaseDeviceToJSON),
    tests:
      value.tests === null
        ? null
        : (value.tests as Array<any>).map(BaseCommissioningTestToJSON),
  };
}
