/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CommissioningStepIdentification
 */
export interface CommissioningStepIdentification {
  /**
   *
   * @type {string}
   * @memberof CommissioningStepIdentification
   */
  type: CommissioningStepIdentificationTypeEnum;
}

/**
 * @export
 */
export const CommissioningStepIdentificationTypeEnum = {
  Identification: "IDENTIFICATION",
} as const;
export type CommissioningStepIdentificationTypeEnum =
  (typeof CommissioningStepIdentificationTypeEnum)[keyof typeof CommissioningStepIdentificationTypeEnum];

/**
 * Check if a given object implements the CommissioningStepIdentification interface.
 */
export function instanceOfCommissioningStepIdentification(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "type" in value;

  return isInstance;
}

export function CommissioningStepIdentificationFromJSON(
  json: any,
): CommissioningStepIdentification {
  return CommissioningStepIdentificationFromJSONTyped(json, false);
}

export function CommissioningStepIdentificationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CommissioningStepIdentification {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: json["type"],
  };
}

export function CommissioningStepIdentificationToJSON(
  value?: CommissioningStepIdentification | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
  };
}
