/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The cic prerequisites to be ready for commissioning
 * @export
 * @interface CommissioningAllOfPrerequisitesCic
 */
export interface CommissioningAllOfPrerequisitesCic {
  /**
   * The version of the cic
   * @type {string}
   * @memberof CommissioningAllOfPrerequisitesCic
   */
  version: string | null;
  /**
   * The minimum required version of the cic to run the commissioning
   * @type {string}
   * @memberof CommissioningAllOfPrerequisitesCic
   */
  minimumRequiredVersion: string;
  /**
   * Whether the cic is ready for commissioning
   * @type {boolean}
   * @memberof CommissioningAllOfPrerequisitesCic
   */
  isReadyForCommissioning: boolean;
  /**
   * The update status of the cic
   * @type {string}
   * @memberof CommissioningAllOfPrerequisitesCic
   */
  updateStatus: CommissioningAllOfPrerequisitesCicUpdateStatusEnum;
  /**
   * The reasons why the cic is not ready for commissioning
   * @type {Array<string>}
   * @memberof CommissioningAllOfPrerequisitesCic
   */
  notReadyReasons: Array<string>;
}

/**
 * @export
 */
export const CommissioningAllOfPrerequisitesCicUpdateStatusEnum = {
  Idle: "IDLE",
  Sync: "SYNC",
  Install: "INSTALL",
  Download: "DOWNLOAD",
  None: "NONE",
} as const;
export type CommissioningAllOfPrerequisitesCicUpdateStatusEnum =
  (typeof CommissioningAllOfPrerequisitesCicUpdateStatusEnum)[keyof typeof CommissioningAllOfPrerequisitesCicUpdateStatusEnum];

/**
 * Check if a given object implements the CommissioningAllOfPrerequisitesCic interface.
 */
export function instanceOfCommissioningAllOfPrerequisitesCic(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "version" in value;
  isInstance = isInstance && "minimumRequiredVersion" in value;
  isInstance = isInstance && "isReadyForCommissioning" in value;
  isInstance = isInstance && "updateStatus" in value;
  isInstance = isInstance && "notReadyReasons" in value;

  return isInstance;
}

export function CommissioningAllOfPrerequisitesCicFromJSON(
  json: any,
): CommissioningAllOfPrerequisitesCic {
  return CommissioningAllOfPrerequisitesCicFromJSONTyped(json, false);
}

export function CommissioningAllOfPrerequisitesCicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CommissioningAllOfPrerequisitesCic {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    version: json["version"],
    minimumRequiredVersion: json["minimumRequiredVersion"],
    isReadyForCommissioning: json["isReadyForCommissioning"],
    updateStatus: json["updateStatus"],
    notReadyReasons: json["notReadyReasons"],
  };
}

export function CommissioningAllOfPrerequisitesCicToJSON(
  value?: CommissioningAllOfPrerequisitesCic | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    version: value.version,
    minimumRequiredVersion: value.minimumRequiredVersion,
    isReadyForCommissioning: value.isReadyForCommissioning,
    updateStatus: value.updateStatus,
    notReadyReasons: value.notReadyReasons,
  };
}
