/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CommissioningTestNotFoundMeta
 */
export interface CommissioningTestNotFoundMeta {
  /**
   *
   * @type {number}
   * @memberof CommissioningTestNotFoundMeta
   */
  status?: number;
}

/**
 * Check if a given object implements the CommissioningTestNotFoundMeta interface.
 */
export function instanceOfCommissioningTestNotFoundMeta(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function CommissioningTestNotFoundMetaFromJSON(
  json: any,
): CommissioningTestNotFoundMeta {
  return CommissioningTestNotFoundMetaFromJSONTyped(json, false);
}

export function CommissioningTestNotFoundMetaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CommissioningTestNotFoundMeta {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    status: !exists(json, "status") ? undefined : json["status"],
  };
}

export function CommissioningTestNotFoundMetaToJSON(
  value?: CommissioningTestNotFoundMeta | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    status: value.status,
  };
}
