/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CommissioningTestNotFoundResult
 */
export interface CommissioningTestNotFoundResult {
  /**
   *
   * @type {string}
   * @memberof CommissioningTestNotFoundResult
   */
  errorCode?: string;
  /**
   *
   * @type {string}
   * @memberof CommissioningTestNotFoundResult
   */
  error?: string;
}

/**
 * Check if a given object implements the CommissioningTestNotFoundResult interface.
 */
export function instanceOfCommissioningTestNotFoundResult(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function CommissioningTestNotFoundResultFromJSON(
  json: any,
): CommissioningTestNotFoundResult {
  return CommissioningTestNotFoundResultFromJSONTyped(json, false);
}

export function CommissioningTestNotFoundResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CommissioningTestNotFoundResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    errorCode: !exists(json, "errorCode") ? undefined : json["errorCode"],
    error: !exists(json, "error") ? undefined : json["error"],
  };
}

export function CommissioningTestNotFoundResultToJSON(
  value?: CommissioningTestNotFoundResult | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    errorCode: value.errorCode,
    error: value.error,
  };
}
