/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CommissioningTestNotFoundMeta } from "./CommissioningTestNotFoundMeta";
import {
  CommissioningTestNotFoundMetaFromJSON,
  CommissioningTestNotFoundMetaFromJSONTyped,
  CommissioningTestNotFoundMetaToJSON,
} from "./CommissioningTestNotFoundMeta";
import type { CommissioningTestNotFoundResult } from "./CommissioningTestNotFoundResult";
import {
  CommissioningTestNotFoundResultFromJSON,
  CommissioningTestNotFoundResultFromJSONTyped,
  CommissioningTestNotFoundResultToJSON,
} from "./CommissioningTestNotFoundResult";

/**
 * Commissioning Test Not Found Error
 * @export
 * @interface CommissioningTestNotFound
 */
export interface CommissioningTestNotFound {
  /**
   *
   * @type {CommissioningTestNotFoundMeta}
   * @memberof CommissioningTestNotFound
   */
  meta?: CommissioningTestNotFoundMeta;
  /**
   *
   * @type {CommissioningTestNotFoundResult}
   * @memberof CommissioningTestNotFound
   */
  result?: CommissioningTestNotFoundResult;
}

/**
 * Check if a given object implements the CommissioningTestNotFound interface.
 */
export function instanceOfCommissioningTestNotFound(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CommissioningTestNotFoundFromJSON(
  json: any,
): CommissioningTestNotFound {
  return CommissioningTestNotFoundFromJSONTyped(json, false);
}

export function CommissioningTestNotFoundFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CommissioningTestNotFound {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: !exists(json, "meta")
      ? undefined
      : CommissioningTestNotFoundMetaFromJSON(json["meta"]),
    result: !exists(json, "result")
      ? undefined
      : CommissioningTestNotFoundResultFromJSON(json["result"]),
  };
}

export function CommissioningTestNotFoundToJSON(
  value?: CommissioningTestNotFound | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: CommissioningTestNotFoundMetaToJSON(value.meta),
    result: CommissioningTestNotFoundResultToJSON(value.result),
  };
}
