/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { DeviceType } from "./DeviceType";
import {
  DeviceTypeFromJSON,
  DeviceTypeFromJSONTyped,
  DeviceTypeToJSON,
} from "./DeviceType";
import type { HeatChargerCommissioningPrerequisiteDetails } from "./HeatChargerCommissioningPrerequisiteDetails";
import {
  HeatChargerCommissioningPrerequisiteDetailsFromJSON,
  HeatChargerCommissioningPrerequisiteDetailsFromJSONTyped,
  HeatChargerCommissioningPrerequisiteDetailsToJSON,
} from "./HeatChargerCommissioningPrerequisiteDetails";

/**
 *
 * @export
 * @interface CommissioningAllOfPrerequisitesDevices
 */
export interface CommissioningAllOfPrerequisitesDevices {
  /**
   *
   * @type {string}
   * @memberof CommissioningAllOfPrerequisitesDevices
   */
  deviceUuid: string;
  /**
   *
   * @type {DeviceType}
   * @memberof CommissioningAllOfPrerequisitesDevices
   */
  type: DeviceType;
  /**
   * The name of the device
   * @type {string}
   * @memberof CommissioningAllOfPrerequisitesDevices
   */
  name?: string | null;
  /**
   * Whether the cic is ready for commissioning
   * @type {boolean}
   * @memberof CommissioningAllOfPrerequisitesDevices
   */
  isReadyForCommissioning: boolean;
  /**
   * The reasons why the cic is not ready for commissioning
   * @type {Array<string>}
   * @memberof CommissioningAllOfPrerequisitesDevices
   */
  notReadyReasons: Array<string>;
  /**
   *
   * @type {HeatChargerCommissioningPrerequisiteDetails}
   * @memberof CommissioningAllOfPrerequisitesDevices
   */
  commissioningPrerequisiteDetails?: HeatChargerCommissioningPrerequisiteDetails | null;
}

/**
 * Check if a given object implements the CommissioningAllOfPrerequisitesDevices interface.
 */
export function instanceOfCommissioningAllOfPrerequisitesDevices(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "deviceUuid" in value;
  isInstance = isInstance && "type" in value;
  isInstance = isInstance && "isReadyForCommissioning" in value;
  isInstance = isInstance && "notReadyReasons" in value;

  return isInstance;
}

export function CommissioningAllOfPrerequisitesDevicesFromJSON(
  json: any,
): CommissioningAllOfPrerequisitesDevices {
  return CommissioningAllOfPrerequisitesDevicesFromJSONTyped(json, false);
}

export function CommissioningAllOfPrerequisitesDevicesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CommissioningAllOfPrerequisitesDevices {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    deviceUuid: json["deviceUuid"],
    type: DeviceTypeFromJSON(json["type"]),
    name: !exists(json, "name") ? undefined : json["name"],
    isReadyForCommissioning: json["isReadyForCommissioning"],
    notReadyReasons: json["notReadyReasons"],
    commissioningPrerequisiteDetails: !exists(
      json,
      "commissioningPrerequisiteDetails",
    )
      ? undefined
      : HeatChargerCommissioningPrerequisiteDetailsFromJSON(
          json["commissioningPrerequisiteDetails"],
        ),
  };
}

export function CommissioningAllOfPrerequisitesDevicesToJSON(
  value?: CommissioningAllOfPrerequisitesDevices | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    deviceUuid: value.deviceUuid,
    type: DeviceTypeToJSON(value.type),
    name: value.name,
    isReadyForCommissioning: value.isReadyForCommissioning,
    notReadyReasons: value.notReadyReasons,
    commissioningPrerequisiteDetails:
      HeatChargerCommissioningPrerequisiteDetailsToJSON(
        value.commissioningPrerequisiteDetails,
      ),
  };
}
