/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateUpdateInstaller
 */
export interface CreateUpdateInstaller {
  /**
   *
   * @type {string}
   * @memberof CreateUpdateInstaller
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateUpdateInstaller
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof CreateUpdateInstaller
   */
  phone: string;
  /**
   *
   * @type {boolean}
   * @memberof CreateUpdateInstaller
   */
  isActive: boolean;
}

/**
 * Check if a given object implements the CreateUpdateInstaller interface.
 */
export function instanceOfCreateUpdateInstaller(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "code" in value;
  isInstance = isInstance && "phone" in value;
  isInstance = isInstance && "isActive" in value;

  return isInstance;
}

export function CreateUpdateInstallerFromJSON(
  json: any,
): CreateUpdateInstaller {
  return CreateUpdateInstallerFromJSONTyped(json, false);
}

export function CreateUpdateInstallerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateUpdateInstaller {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    code: json["code"],
    phone: json["phone"],
    isActive: json["isActive"],
  };
}

export function CreateUpdateInstallerToJSON(
  value?: CreateUpdateInstaller | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    code: value.code,
    phone: value.phone,
    isActive: value.isActive,
  };
}
