/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateUpdateDoubleTariff } from "./CreateUpdateDoubleTariff";
import {
  instanceOfCreateUpdateDoubleTariff,
  CreateUpdateDoubleTariffFromJSON,
  CreateUpdateDoubleTariffFromJSONTyped,
  CreateUpdateDoubleTariffToJSON,
} from "./CreateUpdateDoubleTariff";
import type { CreateUpdateEnergyTariff } from "./CreateUpdateEnergyTariff";
import {
  instanceOfCreateUpdateEnergyTariff,
  CreateUpdateEnergyTariffFromJSON,
  CreateUpdateEnergyTariffFromJSONTyped,
  CreateUpdateEnergyTariffToJSON,
} from "./CreateUpdateEnergyTariff";
import type { CreateUpdateSingleTariff } from "./CreateUpdateSingleTariff";
import {
  instanceOfCreateUpdateSingleTariff,
  CreateUpdateSingleTariffFromJSON,
  CreateUpdateSingleTariffFromJSONTyped,
  CreateUpdateSingleTariffToJSON,
} from "./CreateUpdateSingleTariff";

/**
 * @type CreateTariffRequest
 *
 * @export
 */
export type CreateTariffRequest =
  | CreateUpdateDoubleTariff
  | CreateUpdateEnergyTariff
  | CreateUpdateSingleTariff;

export function CreateTariffRequestFromJSON(json: any): CreateTariffRequest {
  return CreateTariffRequestFromJSONTyped(json, false);
}

export function CreateTariffRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateTariffRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...CreateUpdateDoubleTariffFromJSONTyped(json, true),
    ...CreateUpdateEnergyTariffFromJSONTyped(json, true),
    ...CreateUpdateSingleTariffFromJSONTyped(json, true),
  };
}

export function CreateTariffRequestToJSON(
  value?: CreateTariffRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  if (instanceOfCreateUpdateDoubleTariff(value)) {
    return CreateUpdateDoubleTariffToJSON(value as CreateUpdateDoubleTariff);
  }
  if (instanceOfCreateUpdateEnergyTariff(value)) {
    return CreateUpdateEnergyTariffToJSON(value as CreateUpdateEnergyTariff);
  }
  if (instanceOfCreateUpdateSingleTariff(value)) {
    return CreateUpdateSingleTariffToJSON(value as CreateUpdateSingleTariff);
  }

  return {};
}
