/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CreateTariff400ResponseAllOfResult } from "./CreateTariff400ResponseAllOfResult";
import {
  CreateTariff400ResponseAllOfResultFromJSON,
  CreateTariff400ResponseAllOfResultFromJSONTyped,
  CreateTariff400ResponseAllOfResultToJSON,
} from "./CreateTariff400ResponseAllOfResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface CreateTariff400Response
 */
export interface CreateTariff400Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof CreateTariff400Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {CreateTariff400ResponseAllOfResult}
   * @memberof CreateTariff400Response
   */
  result: CreateTariff400ResponseAllOfResult;
}

/**
 * Check if a given object implements the CreateTariff400Response interface.
 */
export function instanceOfCreateTariff400Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function CreateTariff400ResponseFromJSON(
  json: any,
): CreateTariff400Response {
  return CreateTariff400ResponseFromJSONTyped(json, false);
}

export function CreateTariff400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateTariff400Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: CreateTariff400ResponseAllOfResultFromJSON(json["result"]),
  };
}

export function CreateTariff400ResponseToJSON(
  value?: CreateTariff400Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: CreateTariff400ResponseAllOfResultToJSON(value.result),
  };
}
