/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The values that were used to validate the test and saved in the database
 * @export
 * @interface DeaerationCentralHeatingAllOfValidatedData
 */
export interface DeaerationCentralHeatingAllOfValidatedData {
  /**
   * The flowrate of the central heating system in l/h
   * @type {number}
   * @memberof DeaerationCentralHeatingAllOfValidatedData
   */
  flowrate: number;
}

/**
 * Check if a given object implements the DeaerationCentralHeatingAllOfValidatedData interface.
 */
export function instanceOfDeaerationCentralHeatingAllOfValidatedData(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "flowrate" in value;

  return isInstance;
}

export function DeaerationCentralHeatingAllOfValidatedDataFromJSON(
  json: any,
): DeaerationCentralHeatingAllOfValidatedData {
  return DeaerationCentralHeatingAllOfValidatedDataFromJSONTyped(json, false);
}

export function DeaerationCentralHeatingAllOfValidatedDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeaerationCentralHeatingAllOfValidatedData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    flowrate: json["flowrate"],
  };
}

export function DeaerationCentralHeatingAllOfValidatedDataToJSON(
  value?: DeaerationCentralHeatingAllOfValidatedData | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    flowrate: value.flowrate,
  };
}
