/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { DeleteTariffForInstallation409ResponseAllOfResult } from "./DeleteTariffForInstallation409ResponseAllOfResult";
import {
  DeleteTariffForInstallation409ResponseAllOfResultFromJSON,
  DeleteTariffForInstallation409ResponseAllOfResultFromJSONTyped,
  DeleteTariffForInstallation409ResponseAllOfResultToJSON,
} from "./DeleteTariffForInstallation409ResponseAllOfResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface DeleteTariffForInstallation409Response
 */
export interface DeleteTariffForInstallation409Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof DeleteTariffForInstallation409Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {DeleteTariffForInstallation409ResponseAllOfResult}
   * @memberof DeleteTariffForInstallation409Response
   */
  result: DeleteTariffForInstallation409ResponseAllOfResult;
}

/**
 * Check if a given object implements the DeleteTariffForInstallation409Response interface.
 */
export function instanceOfDeleteTariffForInstallation409Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function DeleteTariffForInstallation409ResponseFromJSON(
  json: any,
): DeleteTariffForInstallation409Response {
  return DeleteTariffForInstallation409ResponseFromJSONTyped(json, false);
}

export function DeleteTariffForInstallation409ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeleteTariffForInstallation409Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: DeleteTariffForInstallation409ResponseAllOfResultFromJSON(
      json["result"],
    ),
  };
}

export function DeleteTariffForInstallation409ResponseToJSON(
  value?: DeleteTariffForInstallation409Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: DeleteTariffForInstallation409ResponseAllOfResultToJSON(
      value.result,
    ),
  };
}
