/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The detailed type of installation
 * @export
 */
export const DetailedInstallationType = {
  HybridSingle: "HYBRID_SINGLE",
  HybridDuo: "HYBRID_DUO",
  AllElectricSingle: "ALL_ELECTRIC_SINGLE",
  AllElectricDuo: "ALL_ELECTRIC_DUO",
  ChillHybridSingle: "CHILL_HYBRID_SINGLE",
  ChillHybridDuo: "CHILL_HYBRID_DUO",
  ChillAllElectricSingle: "CHILL_ALL_ELECTRIC_SINGLE",
  ChillAllElectricDuo: "CHILL_ALL_ELECTRIC_DUO",
  HomeBattery: "HOME_BATTERY",
} as const;
export type DetailedInstallationType =
  (typeof DetailedInstallationType)[keyof typeof DetailedInstallationType];

export function DetailedInstallationTypeFromJSON(
  json: any,
): DetailedInstallationType {
  return DetailedInstallationTypeFromJSONTyped(json, false);
}

export function DetailedInstallationTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DetailedInstallationType {
  return json as DetailedInstallationType;
}

export function DetailedInstallationTypeToJSON(
  value?: DetailedInstallationType | null,
): any {
  return value as any;
}
