/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BoilerDevice } from "./BoilerDevice";
import {
  instanceOfBoilerDevice,
  BoilerDeviceFromJSON,
  BoilerDeviceFromJSONTyped,
  BoilerDeviceToJSON,
} from "./BoilerDevice";
import type { ChillDevice } from "./ChillDevice";
import {
  instanceOfChillDevice,
  ChillDeviceFromJSON,
  ChillDeviceFromJSONTyped,
  ChillDeviceToJSON,
} from "./ChillDevice";
import type { DongleDevice } from "./DongleDevice";
import {
  instanceOfDongleDevice,
  DongleDeviceFromJSON,
  DongleDeviceFromJSONTyped,
  DongleDeviceToJSON,
} from "./DongleDevice";
import type { FlowTemperatureSensorDevice } from "./FlowTemperatureSensorDevice";
import {
  instanceOfFlowTemperatureSensorDevice,
  FlowTemperatureSensorDeviceFromJSON,
  FlowTemperatureSensorDeviceFromJSONTyped,
  FlowTemperatureSensorDeviceToJSON,
} from "./FlowTemperatureSensorDevice";
import type { HeatBatteryDevice } from "./HeatBatteryDevice";
import {
  instanceOfHeatBatteryDevice,
  HeatBatteryDeviceFromJSON,
  HeatBatteryDeviceFromJSONTyped,
  HeatBatteryDeviceToJSON,
} from "./HeatBatteryDevice";
import type { HeatChargerDevice } from "./HeatChargerDevice";
import {
  instanceOfHeatChargerDevice,
  HeatChargerDeviceFromJSON,
  HeatChargerDeviceFromJSONTyped,
  HeatChargerDeviceToJSON,
} from "./HeatChargerDevice";
import type { HomeBatteryDevice } from "./HomeBatteryDevice";
import {
  instanceOfHomeBatteryDevice,
  HomeBatteryDeviceFromJSON,
  HomeBatteryDeviceFromJSONTyped,
  HomeBatteryDeviceToJSON,
} from "./HomeBatteryDevice";
import type { OutDoorUnitDevice } from "./OutDoorUnitDevice";
import {
  instanceOfOutDoorUnitDevice,
  OutDoorUnitDeviceFromJSON,
  OutDoorUnitDeviceFromJSONTyped,
  OutDoorUnitDeviceToJSON,
} from "./OutDoorUnitDevice";
import type { ThermostatDevice } from "./ThermostatDevice";
import {
  instanceOfThermostatDevice,
  ThermostatDeviceFromJSON,
  ThermostatDeviceFromJSONTyped,
  ThermostatDeviceToJSON,
} from "./ThermostatDevice";

/**
 * @type Device
 *
 * @export
 */
export type Device =
  | BoilerDevice
  | ChillDevice
  | DongleDevice
  | FlowTemperatureSensorDevice
  | HeatBatteryDevice
  | HeatChargerDevice
  | HomeBatteryDevice
  | OutDoorUnitDevice
  | ThermostatDevice;

export function DeviceFromJSON(json: any): Device {
  return DeviceFromJSONTyped(json, false);
}

export function DeviceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Device {
  if (json === undefined || json === null) {
    return json;
  }
  // @ts-expect-error - Known OpenAPI Generator bug with union type 'name' property discrimination
  // Type 'string | object | null | undefined' is not assignable to 'object | undefined'
  // This does not affect runtime behavior. See src/api-client/device-type-patch.ts for details.
  return {
    ...BoilerDeviceFromJSONTyped(json, true),
    ...ChillDeviceFromJSONTyped(json, true),
    ...DongleDeviceFromJSONTyped(json, true),
    ...FlowTemperatureSensorDeviceFromJSONTyped(json, true),
    ...HeatBatteryDeviceFromJSONTyped(json, true),
    ...HeatChargerDeviceFromJSONTyped(json, true),
    ...HomeBatteryDeviceFromJSONTyped(json, true),
    ...OutDoorUnitDeviceFromJSONTyped(json, true),
    ...ThermostatDeviceFromJSONTyped(json, true),
  };
}

export function DeviceToJSON(value?: Device | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }

  if (instanceOfBoilerDevice(value)) {
    return BoilerDeviceToJSON(value as BoilerDevice);
  }
  if (instanceOfChillDevice(value)) {
    return ChillDeviceToJSON(value as ChillDevice);
  }
  if (instanceOfDongleDevice(value)) {
    return DongleDeviceToJSON(value as DongleDevice);
  }
  if (instanceOfFlowTemperatureSensorDevice(value)) {
    return FlowTemperatureSensorDeviceToJSON(
      value as FlowTemperatureSensorDevice,
    );
  }
  if (instanceOfHeatBatteryDevice(value)) {
    return HeatBatteryDeviceToJSON(value as HeatBatteryDevice);
  }
  if (instanceOfHeatChargerDevice(value)) {
    return HeatChargerDeviceToJSON(value as HeatChargerDevice);
  }
  if (instanceOfHomeBatteryDevice(value)) {
    return HomeBatteryDeviceToJSON(value as HomeBatteryDevice);
  }
  if (instanceOfOutDoorUnitDevice(value)) {
    return OutDoorUnitDeviceToJSON(value as OutDoorUnitDevice);
  }
  if (instanceOfThermostatDevice(value)) {
    return ThermostatDeviceToJSON(value as ThermostatDevice);
  }

  return {};
}
