/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CicHealthCheckStatus } from "./CicHealthCheckStatus";
import {
  CicHealthCheckStatusFromJSON,
  CicHealthCheckStatusFromJSONTyped,
  CicHealthCheckStatusToJSON,
} from "./CicHealthCheckStatus";

/**
 *
 * @export
 * @interface DeviceConnectionStatuses
 */
export interface DeviceConnectionStatuses {
  /**
   *
   * @type {CicHealthCheckStatus}
   * @memberof DeviceConnectionStatuses
   */
  heatPumpsConnected: CicHealthCheckStatus;
  /**
   *
   * @type {CicHealthCheckStatus}
   * @memberof DeviceConnectionStatuses
   */
  openthermBoilerConnected: CicHealthCheckStatus;
  /**
   *
   * @type {CicHealthCheckStatus}
   * @memberof DeviceConnectionStatuses
   */
  temperatureControlConnected: CicHealthCheckStatus;
  /**
   *
   * @type {CicHealthCheckStatus}
   * @memberof DeviceConnectionStatuses
   */
  thermostatConnected: CicHealthCheckStatus;
}

/**
 * Check if a given object implements the DeviceConnectionStatuses interface.
 */
export function instanceOfDeviceConnectionStatuses(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "heatPumpsConnected" in value;
  isInstance = isInstance && "openthermBoilerConnected" in value;
  isInstance = isInstance && "temperatureControlConnected" in value;
  isInstance = isInstance && "thermostatConnected" in value;

  return isInstance;
}

export function DeviceConnectionStatusesFromJSON(
  json: any,
): DeviceConnectionStatuses {
  return DeviceConnectionStatusesFromJSONTyped(json, false);
}

export function DeviceConnectionStatusesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeviceConnectionStatuses {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    heatPumpsConnected: CicHealthCheckStatusFromJSON(
      json["heatPumpsConnected"],
    ),
    openthermBoilerConnected: CicHealthCheckStatusFromJSON(
      json["openthermBoilerConnected"],
    ),
    temperatureControlConnected: CicHealthCheckStatusFromJSON(
      json["temperatureControlConnected"],
    ),
    thermostatConnected: CicHealthCheckStatusFromJSON(
      json["thermostatConnected"],
    ),
  };
}

export function DeviceConnectionStatusesToJSON(
  value?: DeviceConnectionStatuses | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    heatPumpsConnected: CicHealthCheckStatusToJSON(value.heatPumpsConnected),
    openthermBoilerConnected: CicHealthCheckStatusToJSON(
      value.openthermBoilerConnected,
    ),
    temperatureControlConnected: CicHealthCheckStatusToJSON(
      value.temperatureControlConnected,
    ),
    thermostatConnected: CicHealthCheckStatusToJSON(value.thermostatConnected),
  };
}
