/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const DeviceStatus = {
  Factory: "FACTORY",
  PendingIdentification: "PENDING_IDENTIFICATION",
  Identified: "IDENTIFIED",
  IdentificationFailed: "IDENTIFICATION_FAILED",
  Configured: "CONFIGURED",
  CancelCommissioning: "CANCEL_COMMISSIONING",
  Uninstalled: "UNINSTALLED",
  Active: "ACTIVE",
} as const;
export type DeviceStatus = (typeof DeviceStatus)[keyof typeof DeviceStatus];

export function DeviceStatusFromJSON(json: any): DeviceStatus {
  return DeviceStatusFromJSONTyped(json, false);
}

export function DeviceStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeviceStatus {
  return json as DeviceStatus;
}

export function DeviceStatusToJSON(value?: DeviceStatus | null): any {
  return value as any;
}
