/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { PreHeating } from "./PreHeating";
import {
  PreHeatingFromJSON,
  PreHeatingFromJSONTyped,
  PreHeatingToJSON,
} from "./PreHeating";

/**
 * The live data from the heat charger
 * @export
 * @interface DischargingHeatChargerAllOfLiveData
 */
export interface DischargingHeatChargerAllOfLiveData {
  /**
   *
   * @type {Date}
   * @memberof DischargingHeatChargerAllOfLiveData
   */
  lastUpdatedAt: Date;
  /**
   *
   * @type {PreHeating}
   * @memberof DischargingHeatChargerAllOfLiveData
   */
  preHeating: PreHeating | null;
  /**
   * The power of the heat charger in kwH
   * @type {number}
   * @memberof DischargingHeatChargerAllOfLiveData
   */
  power: number | null;
}

/**
 * Check if a given object implements the DischargingHeatChargerAllOfLiveData interface.
 */
export function instanceOfDischargingHeatChargerAllOfLiveData(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "lastUpdatedAt" in value;
  isInstance = isInstance && "preHeating" in value;
  isInstance = isInstance && "power" in value;

  return isInstance;
}

export function DischargingHeatChargerAllOfLiveDataFromJSON(
  json: any,
): DischargingHeatChargerAllOfLiveData {
  return DischargingHeatChargerAllOfLiveDataFromJSONTyped(json, false);
}

export function DischargingHeatChargerAllOfLiveDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DischargingHeatChargerAllOfLiveData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    lastUpdatedAt: new Date(json["lastUpdatedAt"]),
    preHeating: PreHeatingFromJSON(json["preHeating"]),
    power: json["power"],
  };
}

export function DischargingHeatChargerAllOfLiveDataToJSON(
  value?: DischargingHeatChargerAllOfLiveData | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    lastUpdatedAt: value.lastUpdatedAt.toISOString(),
    preHeating: PreHeatingToJSON(value.preHeating),
    power: value.power,
  };
}
