/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The values that were used to validate the test and saved in the database
 * @export
 * @interface DischargingHeatChargerAllOfValidatedData
 */
export interface DischargingHeatChargerAllOfValidatedData {
  /**
   * The power of the heat charger in kwH
   * @type {number}
   * @memberof DischargingHeatChargerAllOfValidatedData
   */
  power: number;
}

/**
 * Check if a given object implements the DischargingHeatChargerAllOfValidatedData interface.
 */
export function instanceOfDischargingHeatChargerAllOfValidatedData(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "power" in value;

  return isInstance;
}

export function DischargingHeatChargerAllOfValidatedDataFromJSON(
  json: any,
): DischargingHeatChargerAllOfValidatedData {
  return DischargingHeatChargerAllOfValidatedDataFromJSONTyped(json, false);
}

export function DischargingHeatChargerAllOfValidatedDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DischargingHeatChargerAllOfValidatedData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    power: json["power"],
  };
}

export function DischargingHeatChargerAllOfValidatedDataToJSON(
  value?: DischargingHeatChargerAllOfValidatedData | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    power: value.power,
  };
}
