/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CommissioningTestType } from "./CommissioningTestType";
import {
  CommissioningTestTypeFromJSON,
  CommissioningTestTypeFromJSONTyped,
  CommissioningTestTypeToJSON,
} from "./CommissioningTestType";
import type { DischargingHeatChargerAllOfLiveData } from "./DischargingHeatChargerAllOfLiveData";
import {
  DischargingHeatChargerAllOfLiveDataFromJSON,
  DischargingHeatChargerAllOfLiveDataFromJSONTyped,
  DischargingHeatChargerAllOfLiveDataToJSON,
} from "./DischargingHeatChargerAllOfLiveData";
import type { DischargingHeatChargerAllOfValidatedData } from "./DischargingHeatChargerAllOfValidatedData";
import {
  DischargingHeatChargerAllOfValidatedDataFromJSON,
  DischargingHeatChargerAllOfValidatedDataFromJSONTyped,
  DischargingHeatChargerAllOfValidatedDataToJSON,
} from "./DischargingHeatChargerAllOfValidatedData";

/**
 *
 * @export
 * @interface DischargingHeatCharger
 */
export interface DischargingHeatCharger {
  /**
   *
   * @type {string}
   * @memberof DischargingHeatCharger
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof DischargingHeatCharger
   */
  status: DischargingHeatChargerStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof DischargingHeatCharger
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof DischargingHeatCharger
   */
  startedAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof DischargingHeatCharger
   */
  updatedAt: Date;
  /**
   *
   * @type {Date}
   * @memberof DischargingHeatCharger
   */
  endedAt: Date | null;
  /**
   *
   * @type {boolean}
   * @memberof DischargingHeatCharger
   */
  forced: boolean;
  /**
   *
   * @type {string}
   * @memberof DischargingHeatCharger
   */
  commissioningUuid: string;
  /**
   *
   * @type {CommissioningTestType}
   * @memberof DischargingHeatCharger
   */
  type: CommissioningTestType;
  /**
   *
   * @type {string}
   * @memberof DischargingHeatCharger
   */
  installerUuid: string;
  /**
   *
   * @type {number}
   * @memberof DischargingHeatCharger
   */
  step: number;
  /**
   *
   * @type {Date}
   * @memberof DischargingHeatCharger
   */
  maximumDatetime: Date;
  /**
   * The expected pre heating temperature in celsius
   * @type {number}
   * @memberof DischargingHeatCharger
   */
  expectedPreHeatingTemperature: number;
  /**
   * The expected power in kwH
   * @type {number}
   * @memberof DischargingHeatCharger
   */
  expectedPower: number;
  /**
   * The mimimum required power in kwH
   * @type {number}
   * @memberof DischargingHeatCharger
   */
  minimumRequiredPower: number;
  /**
   * The minimum time required to run this test in seconds
   * @type {number}
   * @memberof DischargingHeatCharger
   */
  minimumTimeRequiredInSeconds: number;
  /**
   *
   * @type {DischargingHeatChargerAllOfLiveData}
   * @memberof DischargingHeatCharger
   */
  liveData: DischargingHeatChargerAllOfLiveData | null;
  /**
   *
   * @type {DischargingHeatChargerAllOfValidatedData}
   * @memberof DischargingHeatCharger
   */
  validatedData: DischargingHeatChargerAllOfValidatedData | null;
}

/**
 * @export
 */
export const DischargingHeatChargerStatusEnum = {
  Success: "SUCCESS",
  Failed: "FAILED",
  InProgress: "IN_PROGRESS",
  Cancelled: "CANCELLED",
  Waiting: "WAITING",
  Ready: "READY",
  Validated: "VALIDATED",
} as const;
export type DischargingHeatChargerStatusEnum =
  (typeof DischargingHeatChargerStatusEnum)[keyof typeof DischargingHeatChargerStatusEnum];

/**
 * Check if a given object implements the DischargingHeatCharger interface.
 */
export function instanceOfDischargingHeatCharger(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "startedAt" in value;
  isInstance = isInstance && "updatedAt" in value;
  isInstance = isInstance && "endedAt" in value;
  isInstance = isInstance && "forced" in value;
  isInstance = isInstance && "commissioningUuid" in value;
  isInstance = isInstance && "type" in value;
  isInstance = isInstance && "installerUuid" in value;
  isInstance = isInstance && "step" in value;
  isInstance = isInstance && "maximumDatetime" in value;
  isInstance = isInstance && "expectedPreHeatingTemperature" in value;
  isInstance = isInstance && "expectedPower" in value;
  isInstance = isInstance && "minimumRequiredPower" in value;
  isInstance = isInstance && "minimumTimeRequiredInSeconds" in value;
  isInstance = isInstance && "liveData" in value;
  isInstance = isInstance && "validatedData" in value;

  return isInstance;
}

export function DischargingHeatChargerFromJSON(
  json: any,
): DischargingHeatCharger {
  return DischargingHeatChargerFromJSONTyped(json, false);
}

export function DischargingHeatChargerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DischargingHeatCharger {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    status: json["status"],
    createdAt: new Date(json["createdAt"]),
    startedAt: json["startedAt"] === null ? null : new Date(json["startedAt"]),
    updatedAt: new Date(json["updatedAt"]),
    endedAt: json["endedAt"] === null ? null : new Date(json["endedAt"]),
    forced: json["forced"],
    commissioningUuid: json["commissioningUuid"],
    type: CommissioningTestTypeFromJSON(json["type"]),
    installerUuid: json["installerUuid"],
    step: json["step"],
    maximumDatetime: new Date(json["maximumDatetime"]),
    expectedPreHeatingTemperature: json["expectedPreHeatingTemperature"],
    expectedPower: json["expectedPower"],
    minimumRequiredPower: json["minimumRequiredPower"],
    minimumTimeRequiredInSeconds: json["minimumTimeRequiredInSeconds"],
    liveData: DischargingHeatChargerAllOfLiveDataFromJSON(json["liveData"]),
    validatedData: DischargingHeatChargerAllOfValidatedDataFromJSON(
      json["validatedData"],
    ),
  };
}

export function DischargingHeatChargerToJSON(
  value?: DischargingHeatCharger | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    status: value.status,
    createdAt: value.createdAt.toISOString(),
    startedAt: value.startedAt === null ? null : value.startedAt.toISOString(),
    updatedAt: value.updatedAt.toISOString(),
    endedAt: value.endedAt === null ? null : value.endedAt.toISOString(),
    forced: value.forced,
    commissioningUuid: value.commissioningUuid,
    type: CommissioningTestTypeToJSON(value.type),
    installerUuid: value.installerUuid,
    step: value.step,
    maximumDatetime: value.maximumDatetime.toISOString(),
    expectedPreHeatingTemperature: value.expectedPreHeatingTemperature,
    expectedPower: value.expectedPower,
    minimumRequiredPower: value.minimumRequiredPower,
    minimumTimeRequiredInSeconds: value.minimumTimeRequiredInSeconds,
    liveData: DischargingHeatChargerAllOfLiveDataToJSON(value.liveData),
    validatedData: DischargingHeatChargerAllOfValidatedDataToJSON(
      value.validatedData,
    ),
  };
}
