/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CommissioningTestType } from "./CommissioningTestType";
import {
  CommissioningTestTypeFromJSON,
  CommissioningTestTypeFromJSONTyped,
  CommissioningTestTypeToJSON,
} from "./CommissioningTestType";
import type { DomesticHotWaterTemperatureAllOfLiveData } from "./DomesticHotWaterTemperatureAllOfLiveData";
import {
  DomesticHotWaterTemperatureAllOfLiveDataFromJSON,
  DomesticHotWaterTemperatureAllOfLiveDataFromJSONTyped,
  DomesticHotWaterTemperatureAllOfLiveDataToJSON,
} from "./DomesticHotWaterTemperatureAllOfLiveData";
import type { DomesticHotWaterTemperatureAllOfValidatedData } from "./DomesticHotWaterTemperatureAllOfValidatedData";
import {
  DomesticHotWaterTemperatureAllOfValidatedDataFromJSON,
  DomesticHotWaterTemperatureAllOfValidatedDataFromJSONTyped,
  DomesticHotWaterTemperatureAllOfValidatedDataToJSON,
} from "./DomesticHotWaterTemperatureAllOfValidatedData";

/**
 *
 * @export
 * @interface DomesticHotWaterTemperature
 */
export interface DomesticHotWaterTemperature {
  /**
   *
   * @type {string}
   * @memberof DomesticHotWaterTemperature
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof DomesticHotWaterTemperature
   */
  status: DomesticHotWaterTemperatureStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof DomesticHotWaterTemperature
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof DomesticHotWaterTemperature
   */
  startedAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof DomesticHotWaterTemperature
   */
  updatedAt: Date;
  /**
   *
   * @type {Date}
   * @memberof DomesticHotWaterTemperature
   */
  endedAt: Date | null;
  /**
   *
   * @type {boolean}
   * @memberof DomesticHotWaterTemperature
   */
  forced: boolean;
  /**
   *
   * @type {string}
   * @memberof DomesticHotWaterTemperature
   */
  commissioningUuid: string;
  /**
   *
   * @type {CommissioningTestType}
   * @memberof DomesticHotWaterTemperature
   */
  type: CommissioningTestType;
  /**
   *
   * @type {string}
   * @memberof DomesticHotWaterTemperature
   */
  installerUuid: string;
  /**
   *
   * @type {number}
   * @memberof DomesticHotWaterTemperature
   */
  step: number;
  /**
   *
   * @type {Date}
   * @memberof DomesticHotWaterTemperature
   */
  maximumDatetime: Date;
  /**
   * The expected flow rate in liters per hour.
   * @type {number}
   * @memberof DomesticHotWaterTemperature
   */
  expectedFlowrate: number;
  /**
   * The expected minimum temperature in degrees celsius.
   * @type {number}
   * @memberof DomesticHotWaterTemperature
   */
  expectedMinWaterTemperature: number;
  /**
   * The expected maximum temperature in degrees celsius.
   * @type {number}
   * @memberof DomesticHotWaterTemperature
   */
  expectedMaxWaterTemperature: number;
  /**
   * Indicates whether the user can proceed to the next step in the commissioning process. This becomes true when the test has been successfully validated and the system (liveData) detects that water flow has stopped (i.e., flow rate is zero).
   * @type {boolean}
   * @memberof DomesticHotWaterTemperature
   */
  canProceed?: boolean;
  /**
   *
   * @type {DomesticHotWaterTemperatureAllOfLiveData}
   * @memberof DomesticHotWaterTemperature
   */
  liveData: DomesticHotWaterTemperatureAllOfLiveData | null;
  /**
   *
   * @type {DomesticHotWaterTemperatureAllOfValidatedData}
   * @memberof DomesticHotWaterTemperature
   */
  validatedData?: DomesticHotWaterTemperatureAllOfValidatedData | null;
}

/**
 * @export
 */
export const DomesticHotWaterTemperatureStatusEnum = {
  Success: "SUCCESS",
  Failed: "FAILED",
  InProgress: "IN_PROGRESS",
  Cancelled: "CANCELLED",
  Waiting: "WAITING",
  Ready: "READY",
  Validated: "VALIDATED",
} as const;
export type DomesticHotWaterTemperatureStatusEnum =
  (typeof DomesticHotWaterTemperatureStatusEnum)[keyof typeof DomesticHotWaterTemperatureStatusEnum];

/**
 * Check if a given object implements the DomesticHotWaterTemperature interface.
 */
export function instanceOfDomesticHotWaterTemperature(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "startedAt" in value;
  isInstance = isInstance && "updatedAt" in value;
  isInstance = isInstance && "endedAt" in value;
  isInstance = isInstance && "forced" in value;
  isInstance = isInstance && "commissioningUuid" in value;
  isInstance = isInstance && "type" in value;
  isInstance = isInstance && "installerUuid" in value;
  isInstance = isInstance && "step" in value;
  isInstance = isInstance && "maximumDatetime" in value;
  isInstance = isInstance && "expectedFlowrate" in value;
  isInstance = isInstance && "expectedMinWaterTemperature" in value;
  isInstance = isInstance && "expectedMaxWaterTemperature" in value;
  isInstance = isInstance && "liveData" in value;

  return isInstance;
}

export function DomesticHotWaterTemperatureFromJSON(
  json: any,
): DomesticHotWaterTemperature {
  return DomesticHotWaterTemperatureFromJSONTyped(json, false);
}

export function DomesticHotWaterTemperatureFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DomesticHotWaterTemperature {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    status: json["status"],
    createdAt: new Date(json["createdAt"]),
    startedAt: json["startedAt"] === null ? null : new Date(json["startedAt"]),
    updatedAt: new Date(json["updatedAt"]),
    endedAt: json["endedAt"] === null ? null : new Date(json["endedAt"]),
    forced: json["forced"],
    commissioningUuid: json["commissioningUuid"],
    type: CommissioningTestTypeFromJSON(json["type"]),
    installerUuid: json["installerUuid"],
    step: json["step"],
    maximumDatetime: new Date(json["maximumDatetime"]),
    expectedFlowrate: json["expectedFlowrate"],
    expectedMinWaterTemperature: json["expectedMinWaterTemperature"],
    expectedMaxWaterTemperature: json["expectedMaxWaterTemperature"],
    canProceed: !exists(json, "canProceed") ? undefined : json["canProceed"],
    liveData: DomesticHotWaterTemperatureAllOfLiveDataFromJSON(
      json["liveData"],
    ),
    validatedData: !exists(json, "validatedData")
      ? undefined
      : DomesticHotWaterTemperatureAllOfValidatedDataFromJSON(
          json["validatedData"],
        ),
  };
}

export function DomesticHotWaterTemperatureToJSON(
  value?: DomesticHotWaterTemperature | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    status: value.status,
    createdAt: value.createdAt.toISOString(),
    startedAt: value.startedAt === null ? null : value.startedAt.toISOString(),
    updatedAt: value.updatedAt.toISOString(),
    endedAt: value.endedAt === null ? null : value.endedAt.toISOString(),
    forced: value.forced,
    commissioningUuid: value.commissioningUuid,
    type: CommissioningTestTypeToJSON(value.type),
    installerUuid: value.installerUuid,
    step: value.step,
    maximumDatetime: value.maximumDatetime.toISOString(),
    expectedFlowrate: value.expectedFlowrate,
    expectedMinWaterTemperature: value.expectedMinWaterTemperature,
    expectedMaxWaterTemperature: value.expectedMaxWaterTemperature,
    canProceed: value.canProceed,
    liveData: DomesticHotWaterTemperatureAllOfLiveDataToJSON(value.liveData),
    validatedData: DomesticHotWaterTemperatureAllOfValidatedDataToJSON(
      value.validatedData,
    ),
  };
}
