/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The live data of the central heating system
 * @export
 * @interface DomesticHotWaterTemperatureAllOfLiveData
 */
export interface DomesticHotWaterTemperatureAllOfLiveData {
  /**
   *
   * @type {Date}
   * @memberof DomesticHotWaterTemperatureAllOfLiveData
   */
  lastUpdatedAt: Date;
  /**
   * The flowrate of water
   * @type {number}
   * @memberof DomesticHotWaterTemperatureAllOfLiveData
   */
  flowrate: number | null;
  /**
   * The temperature of the water in degrees celsius
   * @type {number}
   * @memberof DomesticHotWaterTemperatureAllOfLiveData
   */
  waterTemperature: number | null;
}

/**
 * Check if a given object implements the DomesticHotWaterTemperatureAllOfLiveData interface.
 */
export function instanceOfDomesticHotWaterTemperatureAllOfLiveData(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "lastUpdatedAt" in value;
  isInstance = isInstance && "flowrate" in value;
  isInstance = isInstance && "waterTemperature" in value;

  return isInstance;
}

export function DomesticHotWaterTemperatureAllOfLiveDataFromJSON(
  json: any,
): DomesticHotWaterTemperatureAllOfLiveData {
  return DomesticHotWaterTemperatureAllOfLiveDataFromJSONTyped(json, false);
}

export function DomesticHotWaterTemperatureAllOfLiveDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DomesticHotWaterTemperatureAllOfLiveData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    lastUpdatedAt: new Date(json["lastUpdatedAt"]),
    flowrate: json["flowrate"],
    waterTemperature: json["waterTemperature"],
  };
}

export function DomesticHotWaterTemperatureAllOfLiveDataToJSON(
  value?: DomesticHotWaterTemperatureAllOfLiveData | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    lastUpdatedAt: value.lastUpdatedAt.toISOString(),
    flowrate: value.flowrate,
    waterTemperature: value.waterTemperature,
  };
}
