/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The live data of the central heating system
 * @export
 * @interface DomesticHotWaterTemperatureAllOfValidatedData
 */
export interface DomesticHotWaterTemperatureAllOfValidatedData {
  /**
   * The flowrate of water
   * @type {number}
   * @memberof DomesticHotWaterTemperatureAllOfValidatedData
   */
  flowrate: number;
  /**
   * The temperature of the water in degrees celsius
   * @type {number}
   * @memberof DomesticHotWaterTemperatureAllOfValidatedData
   */
  waterTemperature: number;
}

/**
 * Check if a given object implements the DomesticHotWaterTemperatureAllOfValidatedData interface.
 */
export function instanceOfDomesticHotWaterTemperatureAllOfValidatedData(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "flowrate" in value;
  isInstance = isInstance && "waterTemperature" in value;

  return isInstance;
}

export function DomesticHotWaterTemperatureAllOfValidatedDataFromJSON(
  json: any,
): DomesticHotWaterTemperatureAllOfValidatedData {
  return DomesticHotWaterTemperatureAllOfValidatedDataFromJSONTyped(
    json,
    false,
  );
}

export function DomesticHotWaterTemperatureAllOfValidatedDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DomesticHotWaterTemperatureAllOfValidatedData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    flowrate: json["flowrate"],
    waterTemperature: json["waterTemperature"],
  };
}

export function DomesticHotWaterTemperatureAllOfValidatedDataToJSON(
  value?: DomesticHotWaterTemperatureAllOfValidatedData | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    flowrate: value.flowrate,
    waterTemperature: value.waterTemperature,
  };
}
