/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * This object will be used to display the current active prices for electricity and gas in the mobile app.
 * @export
 * @interface DynamicPricesCurrentPrice
 */
export interface DynamicPricesCurrentPrice {
  /**
   * The current active electricity price in EUR/kWh.
   * @type {number}
   * @memberof DynamicPricesCurrentPrice
   */
  electricity: number;
  /**
   * The current active gas price in EUR/m3h.
   * @type {number}
   * @memberof DynamicPricesCurrentPrice
   */
  gas: number;
}

/**
 * Check if a given object implements the DynamicPricesCurrentPrice interface.
 */
export function instanceOfDynamicPricesCurrentPrice(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "electricity" in value;
  isInstance = isInstance && "gas" in value;

  return isInstance;
}

export function DynamicPricesCurrentPriceFromJSON(
  json: any,
): DynamicPricesCurrentPrice {
  return DynamicPricesCurrentPriceFromJSONTyped(json, false);
}

export function DynamicPricesCurrentPriceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DynamicPricesCurrentPrice {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    electricity: json["electricity"],
    gas: json["gas"],
  };
}

export function DynamicPricesCurrentPriceToJSON(
  value?: DynamicPricesCurrentPrice | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    electricity: value.electricity,
    gas: value.gas,
  };
}
