/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ElectricityTariffType = {
  Single: "single",
  Double: "double",
  Dynamic: "dynamic",
} as const;
export type ElectricityTariffType =
  (typeof ElectricityTariffType)[keyof typeof ElectricityTariffType];

export function ElectricityTariffTypeFromJSON(
  json: any,
): ElectricityTariffType {
  return ElectricityTariffTypeFromJSONTyped(json, false);
}

export function ElectricityTariffTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ElectricityTariffType {
  return json as ElectricityTariffType;
}

export function ElectricityTariffTypeToJSON(
  value?: ElectricityTariffType | null,
): any {
  return value as any;
}
