/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ErrorCode } from "./ErrorCode";
import {
  ErrorCodeFromJSON,
  ErrorCodeFromJSONTyped,
  ErrorCodeToJSON,
} from "./ErrorCode";

/**
 *
 * @export
 * @interface ErrorResponseResult
 */
export interface ErrorResponseResult {
  /**
   *
   * @type {string}
   * @memberof ErrorResponseResult
   */
  error: string;
  /**
   *
   * @type {ErrorCode}
   * @memberof ErrorResponseResult
   */
  errorCode: ErrorCode;
}

/**
 * Check if a given object implements the ErrorResponseResult interface.
 */
export function instanceOfErrorResponseResult(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "error" in value;
  isInstance = isInstance && "errorCode" in value;

  return isInstance;
}

export function ErrorResponseResultFromJSON(json: any): ErrorResponseResult {
  return ErrorResponseResultFromJSONTyped(json, false);
}

export function ErrorResponseResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorResponseResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    error: json["error"],
    errorCode: ErrorCodeFromJSON(json["errorCode"]),
  };
}

export function ErrorResponseResultToJSON(
  value?: ErrorResponseResult | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    error: value.error,
    errorCode: ErrorCodeToJSON(value.errorCode),
  };
}
