/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ErrorCode = {
  UserNotAuthorized: "USER_NOT_AUTHORIZED",
  UserNotFound: "USER_NOT_FOUND",
  UserEmailNotVerified: "USER_EMAIL_NOT_VERIFIED",
  UserNoReferral: "USER_NO_REFERRAL",
  UserDuplicateReferral: "USER_DUPLICATE_REFERRAL",
  UserHasNoPairedCic: "USER_HAS_NO_PAIRED_CIC",
  CicNotFound: "CIC_NOT_FOUND",
  CicUpdateError: "CIC_UPDATE_ERROR",
  UserClientDeleteError: "USER_CLIENT_DELETE_ERROR",
  InstallerNotFound: "INSTALLER_NOT_FOUND",
  InstallerWithCodeExists: "INSTALLER_WITH_CODE_EXISTS",
  InstallerWithPhoneExists: "INSTALLER_WITH_PHONE_EXISTS",
  InstallerConnectedToUser: "INSTALLER_CONNECTED_TO_USER",
  UserHasNoPermission: "USER_HAS_NO_PERMISSION",
  OneUserPerInstaller: "ONE_USER_PER_INSTALLER",
  CommissioningNotAllFinished: "COMMISSIONING_NOT_ALL_FINISHED",
  CommissioningFinished: "COMMISSIONING_FINISHED",
  CommissioningInOtherMode: "COMMISSIONING_IN_OTHER_MODE",
  PublishError: "PUBLISH_ERROR",
  CommissioningIdentificationWrongBoilerType:
    "COMMISSIONING_IDENTIFICATION_WRONG_BOILER_TYPE",
  CommissioningIdentificationNoAutoDetectOpenTherm:
    "COMMISSIONING_IDENTIFICATION_NO_AUTO_DETECT_OPEN_THERM",
  CommissioningIdentificationThermostatUnidentified:
    "COMMISSIONING_IDENTIFICATION_THERMOSTAT_UNIDENTIFIED",
  CommissioningIdentificationHeatPumpUnidentified:
    "COMMISSIONING_IDENTIFICATION_HEAT_PUMP_UNIDENTIFIED",
  CommissioningIdentificationOduUnidentified:
    "COMMISSIONING_IDENTIFICATION_ODU_UNIDENTIFIED",
  CommissioningIdentificationFlowTemperatureSensorUnidentified:
    "COMMISSIONING_IDENTIFICATION_FLOW_TEMPERATURE_SENSOR_UNIDENTIFIED",
  CommissioningHeatPumpNotFinished: "COMMISSIONING_HEAT_PUMP_NOT_FINISHED",
  PairingNotPossible: "PAIRING_NOT_POSSIBLE",
  InternalServerError: "INTERNAL_SERVER_ERROR",
  FinishDeaerationNotAllowed: "FINISH_DEAERATION_NOT_ALLOWED",
  FinishFlowRateNotAllowed: "FINISH_FLOW_RATE_NOT_ALLOWED",
  FinishHeatPumpNotAllowed: "FINISH_HEAT_PUMP_NOT_ALLOWED",
  FinishBoilerNotAllowed: "FINISH_BOILER_NOT_ALLOWED",
  CommissioningIdentificationIncorrectThermostatType:
    "COMMISSIONING_IDENTIFICATION_INCORRECT_THERMOSTAT_TYPE",
  MissingRatedMaximumHousePower: "MISSING_RATED_MAXIMUM_HOUSE_POWER",
  MissingMaximumHeatingOutdoorTemperature:
    "MISSING_MAXIMUM_HEATING_OUTDOOR_TEMPERATURE",
  HubspotDealNotFound: "HUBSPOT_DEAL_NOT_FOUND",
  HubspotCicAlreadyLinked: "HUBSPOT_CIC_ALREADY_LINKED",
  ExternalApiError: "EXTERNAL_API_ERROR",
  NotPossibleWith1HeatPump: "NOT_POSSIBLE_WITH_1_HEAT_PUMP",
  CicNeedsUpdate: "CIC_NEEDS_UPDATE",
  MissingCicId: "MISSING_CIC_ID",
  MissingInstallationId: "MISSING_INSTALLATION_ID",
  InstallationInsightsNotAvailable: "INSTALLATION_INSIGHTS_NOT_AVAILABLE",
  MissingDayOrNightElectricityPrice: "MISSING_DAY_OR_NIGHT_ELECTRICITY_PRICE",
  MissingElectricityPrice: "MISSING_ELECTRICITY_PRICE",
  TariffDateAlreadyUsed: "TARIFF_DATE_ALREADY_USED",
  TariffInsertError: "TARIFF_INSERT_ERROR",
  TariffLimitReached: "TARIFF_LIMIT_REACHED",
  TariffNotDeletable: "TARIFF_NOT_DELETABLE",
  TariffNotFound: "TARIFF_NOT_FOUND",
  TariffValidationError: "TARIFF_VALIDATION_ERROR",
  TariffOutOfBounds: "TARIFF_OUT_OF_BOUNDS",
  InstallationDateNotToday: "INSTALLATION_DATE_NOT_TODAY",
  InstallationCountryNotFound: "INSTALLATION_COUNTRY_NOT_FOUND",
  CicNotFactoryOrActive: "CIC_NOT_FACTORY_OR_ACTIVE",
  InstallationNotFound: "INSTALLATION_NOT_FOUND",
  InstallationUpdateError: "INSTALLATION_UPDATE_ERROR",
  InstallationWithNoActiveCic: "INSTALLATION_WITH_NO_ACTIVE_CIC",
  HubspotApiError: "HUBSPOT_API_ERROR",
  ZuperApiError: "ZUPER_API_ERROR",
  OrderNumberNotFound: "ORDER_NUMBER_NOT_FOUND",
  CommissioningNotFound: "COMMISSIONING_NOT_FOUND",
  SettingsUpdateNotFound: "SETTINGS_UPDATE_NOT_FOUND",
  SnowflakeQueryFailed: "SNOWFLAKE_QUERY_FAILED",
  NotesNotFound: "NOTES_NOT_FOUND",
  CommissioningIsForced: "COMMISSIONING_IS_FORCED",
  CommissioningIsCancelled: "COMMISSIONING_IS_CANCELLED",
  ForceCommissioningNotAvailable: "FORCE_COMMISSIONING_NOT_AVAILABLE",
  CancelCommissioningNotAvailable: "CANCEL_COMMISSIONING_NOT_AVAILABLE",
  RebootCicNotAvailable: "REBOOT_CIC_NOT_AVAILABLE",
  RebootHeatchargerNotAvailable: "REBOOT_HEATCHARGER_NOT_AVAILABLE",
  ForgetWifiNotAvailable: "FORGET_WIFI_NOT_AVAILABLE",
  NoInstallationFoundForCic: "NO_INSTALLATION_FOUND_FOR_CIC",
  CicHasAlreadyInstallation: "CIC_HAS_ALREADY_INSTALLATION",
  InstallationCountryNotFound2: "INSTALLATION_COUNTRY_NOT_FOUND",
  DeviceAlreadyConfigured: "DEVICE_ALREADY_CONFIGURED",
  CannotUpdateDevice: "CANNOT_UPDATE_DEVICE",
  CommissioningNotInProgress: "COMMISSIONING_NOT_IN_PROGRESS",
  NotAllDevicesAreReadyForTestCreation:
    "NOT_ALL_DEVICES_ARE_READY_FOR_TEST_CREATION",
  CacheNotFound: "CACHE_NOT_FOUND",
  CommissioningTestNotFound: "COMMISSIONING_TEST_NOT_FOUND",
  CommissioningTestBadRequest: "COMMISSIONING_TEST_BAD_REQUEST",
  CommissioningTestDetailNotFound: "COMMISSIONING_TEST_DETAIL_NOT_FOUND",
  InvalidCommissioningTestStatus: "INVALID_COMMISSIONING_TEST_STATUS",
  DeviceNotFound: "DEVICE_NOT_FOUND",
  InvalidHeatBatterySerialNumber: "INVALID_HEAT_BATTERY_SERIAL_NUMBER",
  InvalidHeatChargerSerialNumber: "INVALID_HEAT_CHARGER_SERIAL_NUMBER",
  NoFailedDevicesFound: "NO_FAILED_DEVICES_FOUND",
  DeviceMetadataNotFound: "DEVICE_METADATA_NOT_FOUND",
  InvalidHeatBatterySize: "INVALID_HEAT_BATTERY_SIZE",
  NoDevicesFound: "NO_DEVICES_FOUND",
  InvalidSoundLevelForAllElectric: "INVALID_SOUND_LEVEL_FOR_ALL_ELECTRIC",
  InvalidAvoidNighttimeChargingForHybrid:
    "INVALID_AVOID_NIGHTTIME_CHARGING_FOR_HYBRID",
  ApiResponseValidationError: "API_RESPONSE_VALIDATION_ERROR",
  InstallationIsNotHybrid: "INSTALLATION_IS_NOT_HYBRID",
  InstallationIsNotAllElectric: "INSTALLATION_IS_NOT_ALL_ELECTRIC",
  OutdoorUnitsNotFound: "OUTDOOR_UNITS_NOT_FOUND",
  UnableToAddDeviceToCommissioning: "UNABLE_TO_ADD_DEVICE_TO_COMMISSIONING",
  CicIsNotReadyForCommissioning: "CIC_IS_NOT_READY_FOR_COMMISSIONING",
  InstallationUuidNotFound: "INSTALLATION_UUID_NOT_FOUND",
  HouseIdNotFound: "HOUSE_ID_NOT_FOUND",
  HubspotQueryError: "HUBSPOT_QUERY_ERROR",
  InvalidZipcodeFormat: "INVALID_ZIPCODE_FORMAT",
  HubspotHouseNotFound: "HUBSPOT_HOUSE_NOT_FOUND",
  FailedToSetRedisKey: "FAILED_TO_SET_REDIS_KEY",
  UnknownOduRevision: "UNKNOWN_ODU_REVISION",
  UnknownPcbFirmwareVersion: "UNKNOWN_PCB_FIRMWARE_VERSION",
  CommissioningStatusNotUpdatable: "COMMISSIONING_STATUS_NOT_UPDATABLE",
  CommissioningNotReady: "COMMISSIONING_NOT_READY",
  DeviceDataNotFoundOnCicStat: "DEVICE_DATA_NOT_FOUND_ON_CIC_STAT",
  UnableToCreateOutdoorUnitDevice: "UNABLE_TO_CREATE_OUTDOOR_UNIT_DEVICE",
  InvalidNumberOfOutdoorUnits: "INVALID_NUMBER_OF_OUTDOOR_UNITS",
  UnableToUpdateOutdoorUnit: "UNABLE_TO_UPDATE_OUTDOOR_UNIT",
  CommissioningIsDone: "COMMISSIONING_IS_DONE",
  DeviceCicNotFound: "DEVICE_CIC_NOT_FOUND",
  UnableToSaveHeatPumpData: "UNABLE_TO_SAVE_HEAT_PUMP_DATA",
  ExternalServiceError: "EXTERNAL_SERVICE_ERROR",
  ThreadDeviceEui64NotFound: "THREAD_DEVICE_EUI64_NOT_FOUND",
  DeviceIsLinkedToAnotherInstallation:
    "DEVICE_IS_LINKED_TO_ANOTHER_INSTALLATION",
  HouseDoesNotHaveHomeBattery: "HOUSE_DOES_NOT_HAVE_HOME_BATTERY",
  ThreadDeviceNotFoundInInstallation: "THREAD_DEVICE_NOT_FOUND_IN_INSTALLATION",
  ThreadDeviceNotFoundInCicStats: "THREAD_DEVICE_NOT_FOUND_IN_CIC_STATS",
  DeviceCredentialsNotFound: "DEVICE_CREDENTIALS_NOT_FOUND",
  NoInstallationFoundForDevice: "NO_INSTALLATION_FOUND_FOR_DEVICE",
  UnknownInstallationType: "UNKNOWN_INSTALLATION_TYPE",
  ThreadDevicesNotSupported: "THREAD_DEVICES_NOT_SUPPORTED",
  HouseNotFound: "HOUSE_NOT_FOUND",
  DeviceAlreadyLinked: "DEVICE_ALREADY_LINKED",
  DeviceNotFoundInSystemList: "DEVICE_NOT_FOUND_IN_SYSTEM_LIST",
  DeviceNameAlreadyTaken: "DEVICE_NAME_ALREADY_TAKEN",
  CommissioningActionNotFound: "COMMISSIONING_ACTION_NOT_FOUND",
  HouseDoesNotHaveRequiredFieldsForHomeBattery:
    "HOUSE_DOES_NOT_HAVE_REQUIRED_FIELDS_FOR_HOME_BATTERY",
  ThreadDeviceRequestedRoleNotSupported:
    "THREAD_DEVICE_REQUESTED_ROLE_NOT_SUPPORTED",
  InstallationNameInvalid: "INSTALLATION_NAME_INVALID",
  CannotRetryIdentificationNoCommissioningUnfinished:
    "CANNOT_RETRY_IDENTIFICATION_NO_COMMISSIONING_UNFINISHED",
  InstallationNotHomeBattery: "INSTALLATION_NOT_HOME_BATTERY",
  InstallationAlreadyHasPairedRcp: "INSTALLATION_ALREADY_HAS_PAIRED_RCP",
  CommissioningActionDetailNotFound: "COMMISSIONING_ACTION_DETAIL_NOT_FOUND",
  DeviceHomeBatteryAlreadyExists: "DEVICE_HOME_BATTERY_ALREADY_EXISTS",
  UnsupportedMediaType: "UNSUPPORTED_MEDIA_TYPE",
  EmptyFileError: "EMPTY_FILE_ERROR",
  MissingRequiredColumns: "MISSING_REQUIRED_COLUMNS",
  NoDynamicEnergyPricingData: "NO_DYNAMIC_ENERGY_PRICING_DATA",
  InsufficientDynamicEnergyPricingData:
    "INSUFFICIENT_DYNAMIC_ENERGY_PRICING_DATA",
  UserAlreadyPairedToHomeBattery: "USER_ALREADY_PAIRED_TO_HOME_BATTERY",
  NoInstalledatFoundForInstallation: "NO_INSTALLEDAT_FOUND_FOR_INSTALLATION",
  InstallationHasNoCicAssociated: "INSTALLATION_HAS_NO_CIC_ASSOCIATED",
  TariffTypeConflict: "TARIFF_TYPE_CONFLICT",
  ElectricityTariffTypeConflict: "ELECTRICITY_TARIFF_TYPE_CONFLICT",
  GasTariffTypeConflict: "GAS_TARIFF_TYPE_CONFLICT",
  TariffDateConflict: "TARIFF_DATE_CONFLICT",
  TariffLimitReached2: "TARIFF_LIMIT_REACHED",
  NoTariffsFound: "NO_TARIFFS_FOUND",
  PricingItemNotFoundForCurrentTime: "PRICING_ITEM_NOT_FOUND_FOR_CURRENT_TIME",
  FeatureNotAvailable: "FEATURE_NOT_AVAILABLE",
  NotImplemented: "NOT_IMPLEMENTED",
  NoLegacyCommissioningHistory: "NO_LEGACY_COMMISSIONING_HISTORY",
  LegacyCommissioningMigrationFailed: "LEGACY_COMMISSIONING_MIGRATION_FAILED",
  InvalidDateFormat: "INVALID_DATE_FORMAT",
  NoCommissioningTestHandlerFound: "NO_COMMISSIONING_TEST_HANDLER_FOUND",
  InvalidWorkflowConfiguration: "INVALID_WORKFLOW_CONFIGURATION",
  CurrentCommissioningTestNotFound: "CURRENT_COMMISSIONING_TEST_NOT_FOUND",
  CannotStartCommissioningTestACommissioningTestIsAlreadyRunning:
    "CANNOT_START_COMMISSIONING_TEST_A_COMMISSIONING_TEST_IS_ALREADY_RUNNING",
  CurrentCommissioningNotFound: "CURRENT_COMMISSIONING_NOT_FOUND",
  CommissioningAlreadyRunningOnInstallation:
    "COMMISSIONING_ALREADY_RUNNING_ON_INSTALLATION",
  NoDevicesConfigurationFound: "NO_DEVICES_CONFIGURATION_FOUND",
  MissingOnFailureConfiguration: "MISSING_ON_FAILURE_CONFIGURATION",
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export function ErrorCodeFromJSON(json: any): ErrorCode {
  return ErrorCodeFromJSONTyped(json, false);
}

export function ErrorCodeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorCode {
  return json as ErrorCode;
}

export function ErrorCodeToJSON(value?: ErrorCode | null): any {
  return value as any;
}
