/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The values that were used to validate the test and saved in the database
 * @export
 * @interface FlowrateOutdoorUnitAllOfValidatedData
 */
export interface FlowrateOutdoorUnitAllOfValidatedData {
  /**
   * The flowrate of the central heating system in l/h
   * @type {number}
   * @memberof FlowrateOutdoorUnitAllOfValidatedData
   */
  flowrate: number | null;
  /**
   * The outdoor unit pump is on or off
   * @type {boolean}
   * @memberof FlowrateOutdoorUnitAllOfValidatedData
   */
  outdoorUnitPumpEnabled: boolean | null;
}

/**
 * Check if a given object implements the FlowrateOutdoorUnitAllOfValidatedData interface.
 */
export function instanceOfFlowrateOutdoorUnitAllOfValidatedData(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "flowrate" in value;
  isInstance = isInstance && "outdoorUnitPumpEnabled" in value;

  return isInstance;
}

export function FlowrateOutdoorUnitAllOfValidatedDataFromJSON(
  json: any,
): FlowrateOutdoorUnitAllOfValidatedData {
  return FlowrateOutdoorUnitAllOfValidatedDataFromJSONTyped(json, false);
}

export function FlowrateOutdoorUnitAllOfValidatedDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowrateOutdoorUnitAllOfValidatedData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    flowrate: json["flowrate"],
    outdoorUnitPumpEnabled: json["outdoorUnitPumpEnabled"],
  };
}

export function FlowrateOutdoorUnitAllOfValidatedDataToJSON(
  value?: FlowrateOutdoorUnitAllOfValidatedData | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    flowrate: value.flowrate,
    outdoorUnitPumpEnabled: value.outdoorUnitPumpEnabled,
  };
}
