/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The live data of the central heating system
 * @export
 * @interface FlowrateOutdoorUnitAllOfLiveData
 */
export interface FlowrateOutdoorUnitAllOfLiveData {
  /**
   *
   * @type {Date}
   * @memberof FlowrateOutdoorUnitAllOfLiveData
   */
  lastUpdatedAt: Date;
  /**
   * Human readable pump level in percentage
   * @type {number}
   * @memberof FlowrateOutdoorUnitAllOfLiveData
   */
  outdoorUnitPumpLevelPercentage: number | null;
  /**
   * The flowrate of the central heating system in l/h
   * @type {number}
   * @memberof FlowrateOutdoorUnitAllOfLiveData
   */
  flowrate: number | null;
}

/**
 * Check if a given object implements the FlowrateOutdoorUnitAllOfLiveData interface.
 */
export function instanceOfFlowrateOutdoorUnitAllOfLiveData(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "lastUpdatedAt" in value;
  isInstance = isInstance && "outdoorUnitPumpLevelPercentage" in value;
  isInstance = isInstance && "flowrate" in value;

  return isInstance;
}

export function FlowrateOutdoorUnitAllOfLiveDataFromJSON(
  json: any,
): FlowrateOutdoorUnitAllOfLiveData {
  return FlowrateOutdoorUnitAllOfLiveDataFromJSONTyped(json, false);
}

export function FlowrateOutdoorUnitAllOfLiveDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowrateOutdoorUnitAllOfLiveData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    lastUpdatedAt: new Date(json["lastUpdatedAt"]),
    outdoorUnitPumpLevelPercentage: json["outdoorUnitPumpLevelPercentage"],
    flowrate: json["flowrate"],
  };
}

export function FlowrateOutdoorUnitAllOfLiveDataToJSON(
  value?: FlowrateOutdoorUnitAllOfLiveData | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    lastUpdatedAt: value.lastUpdatedAt.toISOString(),
    outdoorUnitPumpLevelPercentage: value.outdoorUnitPumpLevelPercentage,
    flowrate: value.flowrate,
  };
}
