/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CommissioningTestType } from "./CommissioningTestType";
import {
  CommissioningTestTypeFromJSON,
  CommissioningTestTypeFromJSONTyped,
  CommissioningTestTypeToJSON,
} from "./CommissioningTestType";
import type { FlowrateAllOutdoorUnitsAllOfLiveData } from "./FlowrateAllOutdoorUnitsAllOfLiveData";
import {
  FlowrateAllOutdoorUnitsAllOfLiveDataFromJSON,
  FlowrateAllOutdoorUnitsAllOfLiveDataFromJSONTyped,
  FlowrateAllOutdoorUnitsAllOfLiveDataToJSON,
} from "./FlowrateAllOutdoorUnitsAllOfLiveData";
import type { FlowrateAllOutdoorUnitsAllOfValidatedData } from "./FlowrateAllOutdoorUnitsAllOfValidatedData";
import {
  FlowrateAllOutdoorUnitsAllOfValidatedDataFromJSON,
  FlowrateAllOutdoorUnitsAllOfValidatedDataFromJSONTyped,
  FlowrateAllOutdoorUnitsAllOfValidatedDataToJSON,
} from "./FlowrateAllOutdoorUnitsAllOfValidatedData";

/**
 *
 * @export
 * @interface FlowrateAllOutdoorUnits
 */
export interface FlowrateAllOutdoorUnits {
  /**
   *
   * @type {string}
   * @memberof FlowrateAllOutdoorUnits
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof FlowrateAllOutdoorUnits
   */
  status: FlowrateAllOutdoorUnitsStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof FlowrateAllOutdoorUnits
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof FlowrateAllOutdoorUnits
   */
  startedAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof FlowrateAllOutdoorUnits
   */
  updatedAt: Date;
  /**
   *
   * @type {Date}
   * @memberof FlowrateAllOutdoorUnits
   */
  endedAt: Date | null;
  /**
   *
   * @type {boolean}
   * @memberof FlowrateAllOutdoorUnits
   */
  forced: boolean;
  /**
   *
   * @type {string}
   * @memberof FlowrateAllOutdoorUnits
   */
  commissioningUuid: string;
  /**
   *
   * @type {CommissioningTestType}
   * @memberof FlowrateAllOutdoorUnits
   */
  type: CommissioningTestType;
  /**
   *
   * @type {string}
   * @memberof FlowrateAllOutdoorUnits
   */
  installerUuid: string;
  /**
   *
   * @type {number}
   * @memberof FlowrateAllOutdoorUnits
   */
  step: number;
  /**
   *
   * @type {Date}
   * @memberof FlowrateAllOutdoorUnits
   */
  maximumDatetime: Date;
  /**
   * The minimum flow rate of the device in liters per hour.
   * @type {number}
   * @memberof FlowrateAllOutdoorUnits
   */
  minimumFlowrate: number;
  /**
   * The expected flow rate of the device in liters per hour.
   * @type {number}
   * @memberof FlowrateAllOutdoorUnits
   */
  expectedFlowrate: number;
  /**
   *
   * @type {FlowrateAllOutdoorUnitsAllOfLiveData}
   * @memberof FlowrateAllOutdoorUnits
   */
  liveData: FlowrateAllOutdoorUnitsAllOfLiveData;
  /**
   *
   * @type {FlowrateAllOutdoorUnitsAllOfValidatedData}
   * @memberof FlowrateAllOutdoorUnits
   */
  validatedData: FlowrateAllOutdoorUnitsAllOfValidatedData | null;
}

/**
 * @export
 */
export const FlowrateAllOutdoorUnitsStatusEnum = {
  Success: "SUCCESS",
  Failed: "FAILED",
  InProgress: "IN_PROGRESS",
  Cancelled: "CANCELLED",
  Waiting: "WAITING",
  Ready: "READY",
  Validated: "VALIDATED",
} as const;
export type FlowrateAllOutdoorUnitsStatusEnum =
  (typeof FlowrateAllOutdoorUnitsStatusEnum)[keyof typeof FlowrateAllOutdoorUnitsStatusEnum];

/**
 * Check if a given object implements the FlowrateAllOutdoorUnits interface.
 */
export function instanceOfFlowrateAllOutdoorUnits(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "startedAt" in value;
  isInstance = isInstance && "updatedAt" in value;
  isInstance = isInstance && "endedAt" in value;
  isInstance = isInstance && "forced" in value;
  isInstance = isInstance && "commissioningUuid" in value;
  isInstance = isInstance && "type" in value;
  isInstance = isInstance && "installerUuid" in value;
  isInstance = isInstance && "step" in value;
  isInstance = isInstance && "maximumDatetime" in value;
  isInstance = isInstance && "minimumFlowrate" in value;
  isInstance = isInstance && "expectedFlowrate" in value;
  isInstance = isInstance && "liveData" in value;
  isInstance = isInstance && "validatedData" in value;

  return isInstance;
}

export function FlowrateAllOutdoorUnitsFromJSON(
  json: any,
): FlowrateAllOutdoorUnits {
  return FlowrateAllOutdoorUnitsFromJSONTyped(json, false);
}

export function FlowrateAllOutdoorUnitsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowrateAllOutdoorUnits {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    status: json["status"],
    createdAt: new Date(json["createdAt"]),
    startedAt: json["startedAt"] === null ? null : new Date(json["startedAt"]),
    updatedAt: new Date(json["updatedAt"]),
    endedAt: json["endedAt"] === null ? null : new Date(json["endedAt"]),
    forced: json["forced"],
    commissioningUuid: json["commissioningUuid"],
    type: CommissioningTestTypeFromJSON(json["type"]),
    installerUuid: json["installerUuid"],
    step: json["step"],
    maximumDatetime: new Date(json["maximumDatetime"]),
    minimumFlowrate: json["minimumFlowrate"],
    expectedFlowrate: json["expectedFlowrate"],
    liveData: FlowrateAllOutdoorUnitsAllOfLiveDataFromJSON(json["liveData"]),
    validatedData: FlowrateAllOutdoorUnitsAllOfValidatedDataFromJSON(
      json["validatedData"],
    ),
  };
}

export function FlowrateAllOutdoorUnitsToJSON(
  value?: FlowrateAllOutdoorUnits | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    status: value.status,
    createdAt: value.createdAt.toISOString(),
    startedAt: value.startedAt === null ? null : value.startedAt.toISOString(),
    updatedAt: value.updatedAt.toISOString(),
    endedAt: value.endedAt === null ? null : value.endedAt.toISOString(),
    forced: value.forced,
    commissioningUuid: value.commissioningUuid,
    type: CommissioningTestTypeToJSON(value.type),
    installerUuid: value.installerUuid,
    step: value.step,
    maximumDatetime: value.maximumDatetime.toISOString(),
    minimumFlowrate: value.minimumFlowrate,
    expectedFlowrate: value.expectedFlowrate,
    liveData: FlowrateAllOutdoorUnitsAllOfLiveDataToJSON(value.liveData),
    validatedData: FlowrateAllOutdoorUnitsAllOfValidatedDataToJSON(
      value.validatedData,
    ),
  };
}
