/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The values that were used to validate the test and saved in the database
 * @export
 * @interface FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedData
 */
export interface FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedData {
  /**
   * The flowrate of the central heating system in l/h
   * @type {number}
   * @memberof FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedData
   */
  flowrate: number;
  /**
   * The outdoor unit 1 pump is on or off
   * @type {boolean}
   * @memberof FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedData
   */
  outdoorUnit1PumpEnabled: boolean;
  /**
   * The outdoor unit 2 pump is on or off
   * @type {boolean}
   * @memberof FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedData
   */
  outdoorUnit2PumpEnabled: boolean;
  /**
   * The heat charger pump is on or off
   * @type {boolean}
   * @memberof FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedData
   */
  heatChargerPumpEnabled: boolean;
}

/**
 * Check if a given object implements the FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedData interface.
 */
export function instanceOfFlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedData(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "flowrate" in value;
  isInstance = isInstance && "outdoorUnit1PumpEnabled" in value;
  isInstance = isInstance && "outdoorUnit2PumpEnabled" in value;
  isInstance = isInstance && "heatChargerPumpEnabled" in value;

  return isInstance;
}

export function FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedDataFromJSON(
  json: any,
): FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedData {
  return FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedDataFromJSONTyped(
    json,
    false,
  );
}

export function FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    flowrate: json["flowrate"],
    outdoorUnit1PumpEnabled: json["outdoorUnit1PumpEnabled"],
    outdoorUnit2PumpEnabled: json["outdoorUnit2PumpEnabled"],
    heatChargerPumpEnabled: json["heatChargerPumpEnabled"],
  };
}

export function FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedDataToJSON(
  value?: FlowrateAllOutdoorUnitsAndHeatChargerAllOfValidatedData | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    flowrate: value.flowrate,
    outdoorUnit1PumpEnabled: value.outdoorUnit1PumpEnabled,
    outdoorUnit2PumpEnabled: value.outdoorUnit2PumpEnabled,
    heatChargerPumpEnabled: value.heatChargerPumpEnabled,
  };
}
