/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface FlowTemperatureSensorDevice
 */
export interface FlowTemperatureSensorDevice {
  /**
   *
   * @type {string}
   * @memberof FlowTemperatureSensorDevice
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof FlowTemperatureSensorDevice
   */
  identificationStatus: FlowTemperatureSensorDeviceIdentificationStatusEnum;
  /**
   *
   * @type {string}
   * @memberof FlowTemperatureSensorDevice
   */
  cicUuid: string;
  /**
   *
   * @type {object}
   * @memberof FlowTemperatureSensorDevice
   */
  name: object;
  /**
   *
   * @type {string}
   * @memberof FlowTemperatureSensorDevice
   */
  type: FlowTemperatureSensorDeviceTypeEnum;
}

/**
 * @export
 */
export const FlowTemperatureSensorDeviceIdentificationStatusEnum = {
  Success: "SUCCESS",
  Failed: "FAILED",
  Unidentified: "UNIDENTIFIED",
} as const;
export type FlowTemperatureSensorDeviceIdentificationStatusEnum =
  (typeof FlowTemperatureSensorDeviceIdentificationStatusEnum)[keyof typeof FlowTemperatureSensorDeviceIdentificationStatusEnum];

/**
 * @export
 */
export const FlowTemperatureSensorDeviceTypeEnum = {
  FlowTemperatureSensor: "FLOW_TEMPERATURE_SENSOR",
} as const;
export type FlowTemperatureSensorDeviceTypeEnum =
  (typeof FlowTemperatureSensorDeviceTypeEnum)[keyof typeof FlowTemperatureSensorDeviceTypeEnum];

/**
 * Check if a given object implements the FlowTemperatureSensorDevice interface.
 */
export function instanceOfFlowTemperatureSensorDevice(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "identificationStatus" in value;
  isInstance = isInstance && "cicUuid" in value;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "type" in value;

  return isInstance;
}

export function FlowTemperatureSensorDeviceFromJSON(
  json: any,
): FlowTemperatureSensorDevice {
  return FlowTemperatureSensorDeviceFromJSONTyped(json, false);
}

export function FlowTemperatureSensorDeviceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowTemperatureSensorDevice {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    identificationStatus: json["identificationStatus"],
    cicUuid: json["cicUuid"],
    name: json["name"],
    type: json["type"],
  };
}

export function FlowTemperatureSensorDeviceToJSON(
  value?: FlowTemperatureSensorDevice | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    identificationStatus: value.identificationStatus,
    cicUuid: value.cicUuid,
    name: value.name,
    type: value.type,
  };
}
