/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CommissioningTestType } from "./CommissioningTestType";
import {
  CommissioningTestTypeFromJSON,
  CommissioningTestTypeFromJSONTyped,
  CommissioningTestTypeToJSON,
} from "./CommissioningTestType";
import type { FlowrateOutdoorUnitAllOfLiveData } from "./FlowrateOutdoorUnitAllOfLiveData";
import {
  FlowrateOutdoorUnitAllOfLiveDataFromJSON,
  FlowrateOutdoorUnitAllOfLiveDataFromJSONTyped,
  FlowrateOutdoorUnitAllOfLiveDataToJSON,
} from "./FlowrateOutdoorUnitAllOfLiveData";
import type { FlowrateOutdoorUnitAllOfValidatedData } from "./FlowrateOutdoorUnitAllOfValidatedData";
import {
  FlowrateOutdoorUnitAllOfValidatedDataFromJSON,
  FlowrateOutdoorUnitAllOfValidatedDataFromJSONTyped,
  FlowrateOutdoorUnitAllOfValidatedDataToJSON,
} from "./FlowrateOutdoorUnitAllOfValidatedData";

/**
 *
 * @export
 * @interface FlowrateOutdoorUnit2
 */
export interface FlowrateOutdoorUnit2 {
  /**
   *
   * @type {string}
   * @memberof FlowrateOutdoorUnit2
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof FlowrateOutdoorUnit2
   */
  status: FlowrateOutdoorUnit2StatusEnum;
  /**
   *
   * @type {Date}
   * @memberof FlowrateOutdoorUnit2
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof FlowrateOutdoorUnit2
   */
  startedAt: Date | null;
  /**
   *
   * @type {Date}
   * @memberof FlowrateOutdoorUnit2
   */
  updatedAt: Date;
  /**
   *
   * @type {Date}
   * @memberof FlowrateOutdoorUnit2
   */
  endedAt: Date | null;
  /**
   *
   * @type {boolean}
   * @memberof FlowrateOutdoorUnit2
   */
  forced: boolean;
  /**
   *
   * @type {string}
   * @memberof FlowrateOutdoorUnit2
   */
  commissioningUuid: string;
  /**
   *
   * @type {CommissioningTestType}
   * @memberof FlowrateOutdoorUnit2
   */
  type: CommissioningTestType;
  /**
   *
   * @type {string}
   * @memberof FlowrateOutdoorUnit2
   */
  installerUuid: string;
  /**
   *
   * @type {number}
   * @memberof FlowrateOutdoorUnit2
   */
  step: number;
  /**
   *
   * @type {Date}
   * @memberof FlowrateOutdoorUnit2
   */
  maximumDatetime: Date;
  /**
   * The expected flow rate of the device in liters per hour.
   * @type {number}
   * @memberof FlowrateOutdoorUnit2
   */
  expectedFlowrate: number;
  /**
   * The minimum flow rate of the device in liters per hour.
   * @type {number}
   * @memberof FlowrateOutdoorUnit2
   */
  minimumFlowrate: number;
  /**
   * The number of the outdoor unit (1 or 2)
   * @type {number}
   * @memberof FlowrateOutdoorUnit2
   */
  outdoorUnitNumber: FlowrateOutdoorUnit2OutdoorUnitNumberEnum;
  /**
   *
   * @type {FlowrateOutdoorUnitAllOfLiveData}
   * @memberof FlowrateOutdoorUnit2
   */
  liveData: FlowrateOutdoorUnitAllOfLiveData;
  /**
   *
   * @type {FlowrateOutdoorUnitAllOfValidatedData}
   * @memberof FlowrateOutdoorUnit2
   */
  validatedData: FlowrateOutdoorUnitAllOfValidatedData | null;
}

/**
 * @export
 */
export const FlowrateOutdoorUnit2StatusEnum = {
  Success: "SUCCESS",
  Failed: "FAILED",
  InProgress: "IN_PROGRESS",
  Cancelled: "CANCELLED",
  Waiting: "WAITING",
  Ready: "READY",
  Validated: "VALIDATED",
} as const;
export type FlowrateOutdoorUnit2StatusEnum =
  (typeof FlowrateOutdoorUnit2StatusEnum)[keyof typeof FlowrateOutdoorUnit2StatusEnum];

/**
 * @export
 */
export const FlowrateOutdoorUnit2OutdoorUnitNumberEnum = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
export type FlowrateOutdoorUnit2OutdoorUnitNumberEnum =
  (typeof FlowrateOutdoorUnit2OutdoorUnitNumberEnum)[keyof typeof FlowrateOutdoorUnit2OutdoorUnitNumberEnum];

/**
 * Check if a given object implements the FlowrateOutdoorUnit2 interface.
 */
export function instanceOfFlowrateOutdoorUnit2(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "createdAt" in value;
  isInstance = isInstance && "startedAt" in value;
  isInstance = isInstance && "updatedAt" in value;
  isInstance = isInstance && "endedAt" in value;
  isInstance = isInstance && "forced" in value;
  isInstance = isInstance && "commissioningUuid" in value;
  isInstance = isInstance && "type" in value;
  isInstance = isInstance && "installerUuid" in value;
  isInstance = isInstance && "step" in value;
  isInstance = isInstance && "maximumDatetime" in value;
  isInstance = isInstance && "expectedFlowrate" in value;
  isInstance = isInstance && "minimumFlowrate" in value;
  isInstance = isInstance && "outdoorUnitNumber" in value;
  isInstance = isInstance && "liveData" in value;
  isInstance = isInstance && "validatedData" in value;

  return isInstance;
}

export function FlowrateOutdoorUnit2FromJSON(json: any): FlowrateOutdoorUnit2 {
  return FlowrateOutdoorUnit2FromJSONTyped(json, false);
}

export function FlowrateOutdoorUnit2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowrateOutdoorUnit2 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    status: json["status"],
    createdAt: new Date(json["createdAt"]),
    startedAt: json["startedAt"] === null ? null : new Date(json["startedAt"]),
    updatedAt: new Date(json["updatedAt"]),
    endedAt: json["endedAt"] === null ? null : new Date(json["endedAt"]),
    forced: json["forced"],
    commissioningUuid: json["commissioningUuid"],
    type: CommissioningTestTypeFromJSON(json["type"]),
    installerUuid: json["installerUuid"],
    step: json["step"],
    maximumDatetime: new Date(json["maximumDatetime"]),
    expectedFlowrate: json["expectedFlowrate"],
    minimumFlowrate: json["minimumFlowrate"],
    outdoorUnitNumber: json["outdoorUnitNumber"],
    liveData: FlowrateOutdoorUnitAllOfLiveDataFromJSON(json["liveData"]),
    validatedData: FlowrateOutdoorUnitAllOfValidatedDataFromJSON(
      json["validatedData"],
    ),
  };
}

export function FlowrateOutdoorUnit2ToJSON(
  value?: FlowrateOutdoorUnit2 | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    status: value.status,
    createdAt: value.createdAt.toISOString(),
    startedAt: value.startedAt === null ? null : value.startedAt.toISOString(),
    updatedAt: value.updatedAt.toISOString(),
    endedAt: value.endedAt === null ? null : value.endedAt.toISOString(),
    forced: value.forced,
    commissioningUuid: value.commissioningUuid,
    type: CommissioningTestTypeToJSON(value.type),
    installerUuid: value.installerUuid,
    step: value.step,
    maximumDatetime: value.maximumDatetime.toISOString(),
    expectedFlowrate: value.expectedFlowrate,
    minimumFlowrate: value.minimumFlowrate,
    outdoorUnitNumber: value.outdoorUnitNumber,
    liveData: FlowrateOutdoorUnitAllOfLiveDataToJSON(value.liveData),
    validatedData: FlowrateOutdoorUnitAllOfValidatedDataToJSON(
      value.validatedData,
    ),
  };
}
