/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { GetAllTariffs403ResponseAllOfResult } from "./GetAllTariffs403ResponseAllOfResult";
import {
  GetAllTariffs403ResponseAllOfResultFromJSON,
  GetAllTariffs403ResponseAllOfResultFromJSONTyped,
  GetAllTariffs403ResponseAllOfResultToJSON,
} from "./GetAllTariffs403ResponseAllOfResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface GetAllTariffs403Response
 */
export interface GetAllTariffs403Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof GetAllTariffs403Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {GetAllTariffs403ResponseAllOfResult}
   * @memberof GetAllTariffs403Response
   */
  result: GetAllTariffs403ResponseAllOfResult;
}

/**
 * Check if a given object implements the GetAllTariffs403Response interface.
 */
export function instanceOfGetAllTariffs403Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function GetAllTariffs403ResponseFromJSON(
  json: any,
): GetAllTariffs403Response {
  return GetAllTariffs403ResponseFromJSONTyped(json, false);
}

export function GetAllTariffs403ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetAllTariffs403Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: GetAllTariffs403ResponseAllOfResultFromJSON(json["result"]),
  };
}

export function GetAllTariffs403ResponseToJSON(
  value?: GetAllTariffs403Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: GetAllTariffs403ResponseAllOfResultToJSON(value.result),
  };
}
