/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { GetAllTariffs400ResponseAllOfResult } from "./GetAllTariffs400ResponseAllOfResult";
import {
  GetAllTariffs400ResponseAllOfResultFromJSON,
  GetAllTariffs400ResponseAllOfResultFromJSONTyped,
  GetAllTariffs400ResponseAllOfResultToJSON,
} from "./GetAllTariffs400ResponseAllOfResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface GetAllTariffs400Response
 */
export interface GetAllTariffs400Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof GetAllTariffs400Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {GetAllTariffs400ResponseAllOfResult}
   * @memberof GetAllTariffs400Response
   */
  result: GetAllTariffs400ResponseAllOfResult;
}

/**
 * Check if a given object implements the GetAllTariffs400Response interface.
 */
export function instanceOfGetAllTariffs400Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function GetAllTariffs400ResponseFromJSON(
  json: any,
): GetAllTariffs400Response {
  return GetAllTariffs400ResponseFromJSONTyped(json, false);
}

export function GetAllTariffs400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetAllTariffs400Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: GetAllTariffs400ResponseAllOfResultFromJSON(json["result"]),
  };
}

export function GetAllTariffs400ResponseToJSON(
  value?: GetAllTariffs400Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: GetAllTariffs400ResponseAllOfResultToJSON(value.result),
  };
}
