/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { GetDynamicPrices400ResponseAllOfResult } from "./GetDynamicPrices400ResponseAllOfResult";
import {
  GetDynamicPrices400ResponseAllOfResultFromJSON,
  GetDynamicPrices400ResponseAllOfResultFromJSONTyped,
  GetDynamicPrices400ResponseAllOfResultToJSON,
} from "./GetDynamicPrices400ResponseAllOfResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface GetDynamicPrices400Response
 */
export interface GetDynamicPrices400Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof GetDynamicPrices400Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {GetDynamicPrices400ResponseAllOfResult}
   * @memberof GetDynamicPrices400Response
   */
  result: GetDynamicPrices400ResponseAllOfResult;
}

/**
 * Check if a given object implements the GetDynamicPrices400Response interface.
 */
export function instanceOfGetDynamicPrices400Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function GetDynamicPrices400ResponseFromJSON(
  json: any,
): GetDynamicPrices400Response {
  return GetDynamicPrices400ResponseFromJSONTyped(json, false);
}

export function GetDynamicPrices400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetDynamicPrices400Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: GetDynamicPrices400ResponseAllOfResultFromJSON(json["result"]),
  };
}

export function GetDynamicPrices400ResponseToJSON(
  value?: GetDynamicPrices400Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: GetDynamicPrices400ResponseAllOfResultToJSON(value.result),
  };
}
