/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { GetDynamicPrices500ResponseAllOfResult } from "./GetDynamicPrices500ResponseAllOfResult";
import {
  GetDynamicPrices500ResponseAllOfResultFromJSON,
  GetDynamicPrices500ResponseAllOfResultFromJSONTyped,
  GetDynamicPrices500ResponseAllOfResultToJSON,
} from "./GetDynamicPrices500ResponseAllOfResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface GetDynamicPrices500Response
 */
export interface GetDynamicPrices500Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof GetDynamicPrices500Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {GetDynamicPrices500ResponseAllOfResult}
   * @memberof GetDynamicPrices500Response
   */
  result: GetDynamicPrices500ResponseAllOfResult;
}

/**
 * Check if a given object implements the GetDynamicPrices500Response interface.
 */
export function instanceOfGetDynamicPrices500Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function GetDynamicPrices500ResponseFromJSON(
  json: any,
): GetDynamicPrices500Response {
  return GetDynamicPrices500ResponseFromJSONTyped(json, false);
}

export function GetDynamicPrices500ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetDynamicPrices500Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: GetDynamicPrices500ResponseAllOfResultFromJSON(json["result"]),
  };
}

export function GetDynamicPrices500ResponseToJSON(
  value?: GetDynamicPrices500Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: GetDynamicPrices500ResponseAllOfResultToJSON(value.result),
  };
}
