/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetDynamicPrices500ResponseAllOfResult
 */
export interface GetDynamicPrices500ResponseAllOfResult {
  /**
   *
   * @type {string}
   * @memberof GetDynamicPrices500ResponseAllOfResult
   */
  errorCode?: GetDynamicPrices500ResponseAllOfResultErrorCodeEnum;
}

/**
 * @export
 */
export const GetDynamicPrices500ResponseAllOfResultErrorCodeEnum = {
  NoDynamicEnergyPricingData: "NO_DYNAMIC_ENERGY_PRICING_DATA",
  InternalServerError: "INTERNAL_SERVER_ERROR",
} as const;
export type GetDynamicPrices500ResponseAllOfResultErrorCodeEnum =
  (typeof GetDynamicPrices500ResponseAllOfResultErrorCodeEnum)[keyof typeof GetDynamicPrices500ResponseAllOfResultErrorCodeEnum];

/**
 * Check if a given object implements the GetDynamicPrices500ResponseAllOfResult interface.
 */
export function instanceOfGetDynamicPrices500ResponseAllOfResult(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function GetDynamicPrices500ResponseAllOfResultFromJSON(
  json: any,
): GetDynamicPrices500ResponseAllOfResult {
  return GetDynamicPrices500ResponseAllOfResultFromJSONTyped(json, false);
}

export function GetDynamicPrices500ResponseAllOfResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetDynamicPrices500ResponseAllOfResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    errorCode: !exists(json, "errorCode") ? undefined : json["errorCode"],
  };
}

export function GetDynamicPrices500ResponseAllOfResultToJSON(
  value?: GetDynamicPrices500ResponseAllOfResult | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    errorCode: value.errorCode,
  };
}
