/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { GetInsights200ResponseResult } from "./GetInsights200ResponseResult";
import {
  GetInsights200ResponseResultFromJSON,
  GetInsights200ResponseResultFromJSONTyped,
  GetInsights200ResponseResultToJSON,
} from "./GetInsights200ResponseResult";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface GetInsights200Response
 */
export interface GetInsights200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof GetInsights200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {GetInsights200ResponseResult}
   * @memberof GetInsights200Response
   */
  result: GetInsights200ResponseResult;
}

/**
 * Check if a given object implements the GetInsights200Response interface.
 */
export function instanceOfGetInsights200Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function GetInsights200ResponseFromJSON(
  json: any,
): GetInsights200Response {
  return GetInsights200ResponseFromJSONTyped(json, false);
}

export function GetInsights200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetInsights200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: GetInsights200ResponseResultFromJSON(json["result"]),
  };
}

export function GetInsights200ResponseToJSON(
  value?: GetInsights200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: GetInsights200ResponseResultToJSON(value.result),
  };
}
