/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetInsights200ResponseResultWaterTemperatureGraphInner
 */
export interface GetInsights200ResponseResultWaterTemperatureGraphInner {
  /**
   *
   * @type {number}
   * @memberof GetInsights200ResponseResultWaterTemperatureGraphInner
   */
  waterTemperature: number | null;
  /**
   *
   * @type {Date}
   * @memberof GetInsights200ResponseResultWaterTemperatureGraphInner
   */
  timestamp: Date;
}

/**
 * Check if a given object implements the GetInsights200ResponseResultWaterTemperatureGraphInner interface.
 */
export function instanceOfGetInsights200ResponseResultWaterTemperatureGraphInner(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "waterTemperature" in value;
  isInstance = isInstance && "timestamp" in value;

  return isInstance;
}

export function GetInsights200ResponseResultWaterTemperatureGraphInnerFromJSON(
  json: any,
): GetInsights200ResponseResultWaterTemperatureGraphInner {
  return GetInsights200ResponseResultWaterTemperatureGraphInnerFromJSONTyped(
    json,
    false,
  );
}

export function GetInsights200ResponseResultWaterTemperatureGraphInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetInsights200ResponseResultWaterTemperatureGraphInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    waterTemperature: json["waterTemperature"],
    timestamp: new Date(json["timestamp"]),
  };
}

export function GetInsights200ResponseResultWaterTemperatureGraphInnerToJSON(
  value?: GetInsights200ResponseResultWaterTemperatureGraphInner | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    waterTemperature: value.waterTemperature,
    timestamp: value.timestamp.toISOString(),
  };
}
