/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Commissioning } from "./Commissioning";
import {
  CommissioningFromJSON,
  CommissioningFromJSONTyped,
  CommissioningToJSON,
} from "./Commissioning";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface GetInstallationCommissionings200Response
 */
export interface GetInstallationCommissionings200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof GetInstallationCommissionings200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {Array<Commissioning>}
   * @memberof GetInstallationCommissionings200Response
   */
  result: Array<Commissioning>;
}

/**
 * Check if a given object implements the GetInstallationCommissionings200Response interface.
 */
export function instanceOfGetInstallationCommissionings200Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function GetInstallationCommissionings200ResponseFromJSON(
  json: any,
): GetInstallationCommissionings200Response {
  return GetInstallationCommissionings200ResponseFromJSONTyped(json, false);
}

export function GetInstallationCommissionings200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetInstallationCommissionings200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: (json["result"] as Array<any>).map(CommissioningFromJSON),
  };
}

export function GetInstallationCommissionings200ResponseToJSON(
  value?: GetInstallationCommissionings200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: (value.result as Array<any>).map(CommissioningToJSON),
  };
}
