/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { GetInstallationInsights200ResponseResultGraphInner } from "./GetInstallationInsights200ResponseResultGraphInner";
import {
  GetInstallationInsights200ResponseResultGraphInnerFromJSON,
  GetInstallationInsights200ResponseResultGraphInnerFromJSONTyped,
  GetInstallationInsights200ResponseResultGraphInnerToJSON,
} from "./GetInstallationInsights200ResponseResultGraphInner";
import type { GetInstallationInsights200ResponseResultOutsideTemperatureGraphInner } from "./GetInstallationInsights200ResponseResultOutsideTemperatureGraphInner";
import {
  GetInstallationInsights200ResponseResultOutsideTemperatureGraphInnerFromJSON,
  GetInstallationInsights200ResponseResultOutsideTemperatureGraphInnerFromJSONTyped,
  GetInstallationInsights200ResponseResultOutsideTemperatureGraphInnerToJSON,
} from "./GetInstallationInsights200ResponseResultOutsideTemperatureGraphInner";
import type { GetInstallationInsights200ResponseResultRoomTemperatureGraphInner } from "./GetInstallationInsights200ResponseResultRoomTemperatureGraphInner";
import {
  GetInstallationInsights200ResponseResultRoomTemperatureGraphInnerFromJSON,
  GetInstallationInsights200ResponseResultRoomTemperatureGraphInnerFromJSONTyped,
  GetInstallationInsights200ResponseResultRoomTemperatureGraphInnerToJSON,
} from "./GetInstallationInsights200ResponseResultRoomTemperatureGraphInner";
import type { GetInstallationInsights200ResponseResultWaterTemperatureGraphInner } from "./GetInstallationInsights200ResponseResultWaterTemperatureGraphInner";
import {
  GetInstallationInsights200ResponseResultWaterTemperatureGraphInnerFromJSON,
  GetInstallationInsights200ResponseResultWaterTemperatureGraphInnerFromJSONTyped,
  GetInstallationInsights200ResponseResultWaterTemperatureGraphInnerToJSON,
} from "./GetInstallationInsights200ResponseResultWaterTemperatureGraphInner";

/**
 *
 * @export
 * @interface GetInstallationInsights200ResponseResult
 */
export interface GetInstallationInsights200ResponseResult {
  /**
   *
   * @type {Date}
   * @memberof GetInstallationInsights200ResponseResult
   */
  from: Date;
  /**
   *
   * @type {Date}
   * @memberof GetInstallationInsights200ResponseResult
   */
  to: Date;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResult
   */
  totalHpHeat: number;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResult
   */
  totalHpElectric: number;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResult
   */
  totalBoilerHeat?: number;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResult
   */
  totalBoilerGas?: number;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResult
   */
  savingsCo2: number;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResult
   */
  savingsGas: number;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResult
   */
  savingsMoney: number | null;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResult
   */
  averageCOP: number | null;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResult
   */
  savingsGasMoney: number | null;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResult
   */
  savingsQuattElectricityCost: number | null;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResult
   */
  co2GasSaved: number | null;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResult
   */
  co2Electricity: number | null;
  /**
   * Whether the user has tarrifs set (otherwise no savings are available)
   * @type {boolean}
   * @memberof GetInstallationInsights200ResponseResult
   */
  hasTarrifs: boolean;
  /**
   *
   * @type {Array<GetInstallationInsights200ResponseResultGraphInner>}
   * @memberof GetInstallationInsights200ResponseResult
   */
  graph?: Array<GetInstallationInsights200ResponseResultGraphInner>;
  /**
   *
   * @type {Array<GetInstallationInsights200ResponseResultOutsideTemperatureGraphInner>}
   * @memberof GetInstallationInsights200ResponseResult
   */
  outsideTemperatureGraph?: Array<GetInstallationInsights200ResponseResultOutsideTemperatureGraphInner> | null;
  /**
   *
   * @type {Array<GetInstallationInsights200ResponseResultWaterTemperatureGraphInner>}
   * @memberof GetInstallationInsights200ResponseResult
   */
  waterTemperatureGraph?: Array<GetInstallationInsights200ResponseResultWaterTemperatureGraphInner> | null;
  /**
   *
   * @type {Array<GetInstallationInsights200ResponseResultRoomTemperatureGraphInner>}
   * @memberof GetInstallationInsights200ResponseResult
   */
  roomTemperatureGraph?: Array<GetInstallationInsights200ResponseResultRoomTemperatureGraphInner> | null;
}

/**
 * Check if a given object implements the GetInstallationInsights200ResponseResult interface.
 */
export function instanceOfGetInstallationInsights200ResponseResult(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "from" in value;
  isInstance = isInstance && "to" in value;
  isInstance = isInstance && "totalHpHeat" in value;
  isInstance = isInstance && "totalHpElectric" in value;
  isInstance = isInstance && "savingsCo2" in value;
  isInstance = isInstance && "savingsGas" in value;
  isInstance = isInstance && "savingsMoney" in value;
  isInstance = isInstance && "averageCOP" in value;
  isInstance = isInstance && "savingsGasMoney" in value;
  isInstance = isInstance && "savingsQuattElectricityCost" in value;
  isInstance = isInstance && "co2GasSaved" in value;
  isInstance = isInstance && "co2Electricity" in value;
  isInstance = isInstance && "hasTarrifs" in value;

  return isInstance;
}

export function GetInstallationInsights200ResponseResultFromJSON(
  json: any,
): GetInstallationInsights200ResponseResult {
  return GetInstallationInsights200ResponseResultFromJSONTyped(json, false);
}

export function GetInstallationInsights200ResponseResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetInstallationInsights200ResponseResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    from: new Date(json["from"]),
    to: new Date(json["to"]),
    totalHpHeat: json["totalHpHeat"],
    totalHpElectric: json["totalHpElectric"],
    totalBoilerHeat: !exists(json, "totalBoilerHeat")
      ? undefined
      : json["totalBoilerHeat"],
    totalBoilerGas: !exists(json, "totalBoilerGas")
      ? undefined
      : json["totalBoilerGas"],
    savingsCo2: json["savingsCo2"],
    savingsGas: json["savingsGas"],
    savingsMoney: json["savingsMoney"],
    averageCOP: json["averageCOP"],
    savingsGasMoney: json["savingsGasMoney"],
    savingsQuattElectricityCost: json["savingsQuattElectricityCost"],
    co2GasSaved: json["co2GasSaved"],
    co2Electricity: json["co2Electricity"],
    hasTarrifs: json["hasTarrifs"],
    graph: !exists(json, "graph")
      ? undefined
      : (json["graph"] as Array<any>).map(
          GetInstallationInsights200ResponseResultGraphInnerFromJSON,
        ),
    outsideTemperatureGraph: !exists(json, "outsideTemperatureGraph")
      ? undefined
      : json["outsideTemperatureGraph"] === null
        ? null
        : (json["outsideTemperatureGraph"] as Array<any>).map(
            GetInstallationInsights200ResponseResultOutsideTemperatureGraphInnerFromJSON,
          ),
    waterTemperatureGraph: !exists(json, "waterTemperatureGraph")
      ? undefined
      : json["waterTemperatureGraph"] === null
        ? null
        : (json["waterTemperatureGraph"] as Array<any>).map(
            GetInstallationInsights200ResponseResultWaterTemperatureGraphInnerFromJSON,
          ),
    roomTemperatureGraph: !exists(json, "roomTemperatureGraph")
      ? undefined
      : json["roomTemperatureGraph"] === null
        ? null
        : (json["roomTemperatureGraph"] as Array<any>).map(
            GetInstallationInsights200ResponseResultRoomTemperatureGraphInnerFromJSON,
          ),
  };
}

export function GetInstallationInsights200ResponseResultToJSON(
  value?: GetInstallationInsights200ResponseResult | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    from: value.from.toISOString(),
    to: value.to.toISOString(),
    totalHpHeat: value.totalHpHeat,
    totalHpElectric: value.totalHpElectric,
    totalBoilerHeat: value.totalBoilerHeat,
    totalBoilerGas: value.totalBoilerGas,
    savingsCo2: value.savingsCo2,
    savingsGas: value.savingsGas,
    savingsMoney: value.savingsMoney,
    averageCOP: value.averageCOP,
    savingsGasMoney: value.savingsGasMoney,
    savingsQuattElectricityCost: value.savingsQuattElectricityCost,
    co2GasSaved: value.co2GasSaved,
    co2Electricity: value.co2Electricity,
    hasTarrifs: value.hasTarrifs,
    graph:
      value.graph === undefined
        ? undefined
        : (value.graph as Array<any>).map(
            GetInstallationInsights200ResponseResultGraphInnerToJSON,
          ),
    outsideTemperatureGraph:
      value.outsideTemperatureGraph === undefined
        ? undefined
        : value.outsideTemperatureGraph === null
          ? null
          : (value.outsideTemperatureGraph as Array<any>).map(
              GetInstallationInsights200ResponseResultOutsideTemperatureGraphInnerToJSON,
            ),
    waterTemperatureGraph:
      value.waterTemperatureGraph === undefined
        ? undefined
        : value.waterTemperatureGraph === null
          ? null
          : (value.waterTemperatureGraph as Array<any>).map(
              GetInstallationInsights200ResponseResultWaterTemperatureGraphInnerToJSON,
            ),
    roomTemperatureGraph:
      value.roomTemperatureGraph === undefined
        ? undefined
        : value.roomTemperatureGraph === null
          ? null
          : (value.roomTemperatureGraph as Array<any>).map(
              GetInstallationInsights200ResponseResultRoomTemperatureGraphInnerToJSON,
            ),
  };
}
