/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetInstallationInsights200ResponseResultRoomTemperatureGraphInner
 */
export interface GetInstallationInsights200ResponseResultRoomTemperatureGraphInner {
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResultRoomTemperatureGraphInner
   */
  roomTemperature: number | null;
  /**
   *
   * @type {number}
   * @memberof GetInstallationInsights200ResponseResultRoomTemperatureGraphInner
   */
  roomSetpoint: number | null;
  /**
   *
   * @type {Date}
   * @memberof GetInstallationInsights200ResponseResultRoomTemperatureGraphInner
   */
  timestamp: Date;
}

/**
 * Check if a given object implements the GetInstallationInsights200ResponseResultRoomTemperatureGraphInner interface.
 */
export function instanceOfGetInstallationInsights200ResponseResultRoomTemperatureGraphInner(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "roomTemperature" in value;
  isInstance = isInstance && "roomSetpoint" in value;
  isInstance = isInstance && "timestamp" in value;

  return isInstance;
}

export function GetInstallationInsights200ResponseResultRoomTemperatureGraphInnerFromJSON(
  json: any,
): GetInstallationInsights200ResponseResultRoomTemperatureGraphInner {
  return GetInstallationInsights200ResponseResultRoomTemperatureGraphInnerFromJSONTyped(
    json,
    false,
  );
}

export function GetInstallationInsights200ResponseResultRoomTemperatureGraphInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetInstallationInsights200ResponseResultRoomTemperatureGraphInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    roomTemperature: json["roomTemperature"],
    roomSetpoint: json["roomSetpoint"],
    timestamp: new Date(json["timestamp"]),
  };
}

export function GetInstallationInsights200ResponseResultRoomTemperatureGraphInnerToJSON(
  value?: GetInstallationInsights200ResponseResultRoomTemperatureGraphInner | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    roomTemperature: value.roomTemperature,
    roomSetpoint: value.roomSetpoint,
    timestamp: value.timestamp.toISOString(),
  };
}
