/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ReferralMember } from "./ReferralMember";
import {
  ReferralMemberFromJSON,
  ReferralMemberFromJSONTyped,
  ReferralMemberToJSON,
} from "./ReferralMember";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";

/**
 *
 * @export
 * @interface GetReferral200Response
 */
export interface GetReferral200Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof GetReferral200Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {ReferralMember}
   * @memberof GetReferral200Response
   */
  result: ReferralMember;
}

/**
 * Check if a given object implements the GetReferral200Response interface.
 */
export function instanceOfGetReferral200Response(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function GetReferral200ResponseFromJSON(
  json: any,
): GetReferral200Response {
  return GetReferral200ResponseFromJSONTyped(json, false);
}

export function GetReferral200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetReferral200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: ReferralMemberFromJSON(json["result"]),
  };
}

export function GetReferral200ResponseToJSON(
  value?: GetReferral200Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: ReferralMemberToJSON(value.result),
  };
}
