/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { DeviceStatus } from "./DeviceStatus";
import {
  DeviceStatusFromJSON,
  DeviceStatusFromJSONTyped,
  DeviceStatusToJSON,
} from "./DeviceStatus";
import type { HeatChargerDeviceAllOfFirmware } from "./HeatChargerDeviceAllOfFirmware";
import {
  HeatChargerDeviceAllOfFirmwareFromJSON,
  HeatChargerDeviceAllOfFirmwareFromJSONTyped,
  HeatChargerDeviceAllOfFirmwareToJSON,
} from "./HeatChargerDeviceAllOfFirmware";

/**
 *
 * @export
 * @interface HeatChargerDevice
 */
export interface HeatChargerDevice {
  /**
   *
   * @type {string}
   * @memberof HeatChargerDevice
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof HeatChargerDevice
   */
  cicUuid?: string | null;
  /**
   *
   * @type {object}
   * @memberof HeatChargerDevice
   */
  name?: object;
  /**
   *
   * @type {DeviceStatus}
   * @memberof HeatChargerDevice
   */
  status: DeviceStatus;
  /**
   *
   * @type {string}
   * @memberof HeatChargerDevice
   */
  installationUuid?: string | null;
  /**
   *
   * @type {string}
   * @memberof HeatChargerDevice
   */
  type: HeatChargerDeviceTypeEnum;
  /**
   *
   * @type {number}
   * @memberof HeatChargerDevice
   */
  revisionId: number | null;
  /**
   *
   * @type {HeatChargerDeviceAllOfFirmware}
   * @memberof HeatChargerDevice
   */
  firmware?: HeatChargerDeviceAllOfFirmware;
}

/**
 * @export
 */
export const HeatChargerDeviceTypeEnum = {
  HeatCharger: "HEAT_CHARGER",
} as const;
export type HeatChargerDeviceTypeEnum =
  (typeof HeatChargerDeviceTypeEnum)[keyof typeof HeatChargerDeviceTypeEnum];

/**
 * Check if a given object implements the HeatChargerDevice interface.
 */
export function instanceOfHeatChargerDevice(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "type" in value;
  isInstance = isInstance && "revisionId" in value;

  return isInstance;
}

export function HeatChargerDeviceFromJSON(json: any): HeatChargerDevice {
  return HeatChargerDeviceFromJSONTyped(json, false);
}

export function HeatChargerDeviceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HeatChargerDevice {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    cicUuid: !exists(json, "cicUuid") ? undefined : json["cicUuid"],
    name: !exists(json, "name") ? undefined : json["name"],
    status: DeviceStatusFromJSON(json["status"]),
    installationUuid: !exists(json, "installationUuid")
      ? undefined
      : json["installationUuid"],
    type: json["type"],
    revisionId: json["revisionId"],
    firmware: !exists(json, "firmware")
      ? undefined
      : HeatChargerDeviceAllOfFirmwareFromJSON(json["firmware"]),
  };
}

export function HeatChargerDeviceToJSON(value?: HeatChargerDevice | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    cicUuid: value.cicUuid,
    name: value.name,
    status: DeviceStatusToJSON(value.status),
    installationUuid: value.installationUuid,
    type: value.type,
    revisionId: value.revisionId,
    firmware: HeatChargerDeviceAllOfFirmwareToJSON(value.firmware),
  };
}
