/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { DeviceStatus } from "./DeviceStatus";
import {
  DeviceStatusFromJSON,
  DeviceStatusFromJSONTyped,
  DeviceStatusToJSON,
} from "./DeviceStatus";
import type { HeatBatterySize } from "./HeatBatterySize";
import {
  HeatBatterySizeFromJSON,
  HeatBatterySizeFromJSONTyped,
  HeatBatterySizeToJSON,
} from "./HeatBatterySize";

/**
 *
 * @export
 * @interface HeatBatteryDevice
 */
export interface HeatBatteryDevice {
  /**
   *
   * @type {string}
   * @memberof HeatBatteryDevice
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof HeatBatteryDevice
   */
  cicUuid?: string | null;
  /**
   *
   * @type {object}
   * @memberof HeatBatteryDevice
   */
  name?: object;
  /**
   *
   * @type {DeviceStatus}
   * @memberof HeatBatteryDevice
   */
  status: DeviceStatus;
  /**
   *
   * @type {string}
   * @memberof HeatBatteryDevice
   */
  installationUuid?: string | null;
  /**
   *
   * @type {HeatBatterySize}
   * @memberof HeatBatteryDevice
   */
  size?: HeatBatterySize;
  /**
   *
   * @type {string}
   * @memberof HeatBatteryDevice
   */
  type: HeatBatteryDeviceTypeEnum;
}

/**
 * @export
 */
export const HeatBatteryDeviceTypeEnum = {
  HeatBattery: "HEAT_BATTERY",
} as const;
export type HeatBatteryDeviceTypeEnum =
  (typeof HeatBatteryDeviceTypeEnum)[keyof typeof HeatBatteryDeviceTypeEnum];

/**
 * Check if a given object implements the HeatBatteryDevice interface.
 */
export function instanceOfHeatBatteryDevice(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "type" in value;

  return isInstance;
}

export function HeatBatteryDeviceFromJSON(json: any): HeatBatteryDevice {
  return HeatBatteryDeviceFromJSONTyped(json, false);
}

export function HeatBatteryDeviceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HeatBatteryDevice {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    cicUuid: !exists(json, "cicUuid") ? undefined : json["cicUuid"],
    name: !exists(json, "name") ? undefined : json["name"],
    status: DeviceStatusFromJSON(json["status"]),
    installationUuid: !exists(json, "installationUuid")
      ? undefined
      : json["installationUuid"],
    size: !exists(json, "size")
      ? undefined
      : HeatBatterySizeFromJSON(json["size"]),
    type: json["type"],
  };
}

export function HeatBatteryDeviceToJSON(value?: HeatBatteryDevice | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    cicUuid: value.cicUuid,
    name: value.name,
    status: DeviceStatusToJSON(value.status),
    installationUuid: value.installationUuid,
    size: HeatBatterySizeToJSON(value.size),
    type: value.type,
  };
}
