/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const HybridCommissioningMode = {
  Identification: "identification",
  Deaeration: "deaeration",
  FlowRate: "flow_rate",
  FlowRateHp1: "flow_rate_hp1",
  FlowRateHp2: "flow_rate_hp2",
  FlowRateAll: "flow_rate_all",
  HeatPump: "heat_pump",
  Boiler: "boiler",
  None: "none",
} as const;
export type HybridCommissioningMode =
  (typeof HybridCommissioningMode)[keyof typeof HybridCommissioningMode];

export function HybridCommissioningModeFromJSON(
  json: any,
): HybridCommissioningMode {
  return HybridCommissioningModeFromJSONTyped(json, false);
}

export function HybridCommissioningModeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HybridCommissioningMode {
  return json as HybridCommissioningMode;
}

export function HybridCommissioningModeToJSON(
  value?: HybridCommissioningMode | null,
): any {
  return value as any;
}
