/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const IdentificationTestStatus = {
  Running: "running",
  Finished: "finished",
  Null: "null",
} as const;
export type IdentificationTestStatus =
  (typeof IdentificationTestStatus)[keyof typeof IdentificationTestStatus];

export function IdentificationTestStatusFromJSON(
  json: any,
): IdentificationTestStatus {
  return IdentificationTestStatusFromJSONTyped(json, false);
}

export function IdentificationTestStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IdentificationTestStatus {
  return json as IdentificationTestStatus;
}

export function IdentificationTestStatusToJSON(
  value?: IdentificationTestStatus | null,
): any {
  return value as any;
}
