/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const InstallationType = {
  Hybrid: "hybrid",
  HybridDuo: "hybrid_duo",
} as const;
export type InstallationType =
  (typeof InstallationType)[keyof typeof InstallationType];

export function InstallationTypeFromJSON(json: any): InstallationType {
  return InstallationTypeFromJSONTyped(json, false);
}

export function InstallationTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InstallationType {
  return json as InstallationType;
}

export function InstallationTypeToJSON(value?: InstallationType | null): any {
  return value as any;
}
