/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { AllEStatus } from "./AllEStatus";
import {
  AllEStatusFromJSON,
  AllEStatusFromJSONTyped,
  AllEStatusToJSON,
} from "./AllEStatus";
import type { BoilerType } from "./BoilerType";
import {
  BoilerTypeFromJSON,
  BoilerTypeFromJSONTyped,
  BoilerTypeToJSON,
} from "./BoilerType";
import type { CicAvailableWifiNetworksInner } from "./CicAvailableWifiNetworksInner";
import {
  CicAvailableWifiNetworksInnerFromJSON,
  CicAvailableWifiNetworksInnerFromJSONTyped,
  CicAvailableWifiNetworksInnerToJSON,
} from "./CicAvailableWifiNetworksInner";
import type { CicCommissioning } from "./CicCommissioning";
import {
  CicCommissioningFromJSON,
  CicCommissioningFromJSONTyped,
  CicCommissioningToJSON,
} from "./CicCommissioning";
import type { CicStatus } from "./CicStatus";
import {
  CicStatusFromJSON,
  CicStatusFromJSONTyped,
  CicStatusToJSON,
} from "./CicStatus";
import type { ConnectionStatus } from "./ConnectionStatus";
import {
  ConnectionStatusFromJSON,
  ConnectionStatusFromJSONTyped,
  ConnectionStatusToJSON,
} from "./ConnectionStatus";
import type { Country } from "./Country";
import {
  CountryFromJSON,
  CountryFromJSONTyped,
  CountryToJSON,
} from "./Country";
import type { HeatDeliverySystem } from "./HeatDeliverySystem";
import {
  HeatDeliverySystemFromJSON,
  HeatDeliverySystemFromJSONTyped,
  HeatDeliverySystemToJSON,
} from "./HeatDeliverySystem";
import type { HeatPump } from "./HeatPump";
import {
  HeatPumpFromJSON,
  HeatPumpFromJSONTyped,
  HeatPumpToJSON,
} from "./HeatPump";
import type { MaxSoundLevel } from "./MaxSoundLevel";
import {
  MaxSoundLevelFromJSON,
  MaxSoundLevelFromJSONTyped,
  MaxSoundLevelToJSON,
} from "./MaxSoundLevel";
import type { SilentMode } from "./SilentMode";
import {
  SilentModeFromJSON,
  SilentModeFromJSONTyped,
  SilentModeToJSON,
} from "./SilentMode";
import type { TariffType } from "./TariffType";
import {
  TariffTypeFromJSON,
  TariffTypeFromJSONTyped,
  TariffTypeToJSON,
} from "./TariffType";
import type { ThermostatType } from "./ThermostatType";
import {
  ThermostatTypeFromJSON,
  ThermostatTypeFromJSONTyped,
  ThermostatTypeToJSON,
} from "./ThermostatType";

/**
 *
 * @export
 * @interface InstallerCic
 */
export interface InstallerCic {
  /**
   *
   * @type {string}
   * @memberof InstallerCic
   */
  id: string;
  /**
   *
   * @type {ConnectionStatus}
   * @memberof InstallerCic
   */
  lteConnectionStatus: ConnectionStatus | null;
  /**
   *
   * @type {ConnectionStatus}
   * @memberof InstallerCic
   */
  cableConnectionStatus: ConnectionStatus | null;
  /**
   *
   * @type {ConnectionStatus}
   * @memberof InstallerCic
   */
  wifiConnectionStatus: ConnectionStatus | null;
  /**
   * The SSID of the WiFi network the CIC is connected to. (human readable)
   * @type {string}
   * @memberof InstallerCic
   */
  wifiSSID: string | null;
  /**
   *
   * @type {Array<CicAvailableWifiNetworksInner>}
   * @memberof InstallerCic
   */
  availableWifiNetworks: Array<CicAvailableWifiNetworksInner> | null;
  /**
   *
   * @type {Date}
   * @memberof InstallerCic
   */
  lastScannedForWifi: Date | null;
  /**
   *
   * @type {boolean}
   * @memberof InstallerCic
   */
  isScanningForWifi: boolean;
  /**
   *
   * @type {string}
   * @memberof InstallerCic
   */
  boilerDemand?: InstallerCicBoilerDemandEnum;
  /**
   * Amount of power in watt
   * @type {number}
   * @memberof InstallerCic
   */
  boilerPower?: number | null;
  /**
   * Temperature in degrees celcius of the water flowing in. Use heatingWaterTemperatureIn instead
   * @type {number}
   * @memberof InstallerCic
   * @deprecated
   */
  boilerWaterTemperatureIn?: number | null;
  /**
   * Temperature in degrees celcius of the water flowing out. Use heatingWaterTemperatureOut instead
   * @type {number}
   * @memberof InstallerCic
   * @deprecated
   */
  boilerWaterTemperatureOut?: number | null;
  /**
   * Temperature in degrees celcius of the water flowing in
   * @type {number}
   * @memberof InstallerCic
   */
  heatingWaterTemperatureIn?: number | null;
  /**
   * Temperature in degrees celcius of the water flowing out
   * @type {number}
   * @memberof InstallerCic
   */
  heatingWaterTemperatureOut?: number | null;
  /**
   * Boiler pressure in bar
   * @type {number}
   * @memberof InstallerCic
   */
  boilerPressure?: number | null;
  /**
   *
   * @type {string}
   * @memberof InstallerCic
   */
  thermostatDemand: InstallerCicThermostatDemandEnum;
  /**
   * Temperature in degrees celcius of the room
   * @type {number}
   * @memberof InstallerCic
   */
  thermostatRoomTemperature: number | null;
  /**
   * Temperature in degrees celcius set point of the room
   * @type {number}
   * @memberof InstallerCic
   */
  thermostatRoomTemperatureSetPoint: number | null;
  /**
   * If the flame symbol is on on the thermostat
   * @type {boolean}
   * @memberof InstallerCic
   */
  thermostatFlameOn: boolean | null;
  /**
   * If the live temperature is shown on the app
   * @type {boolean}
   * @memberof InstallerCic
   */
  showThermostatTemperatures: boolean | null;
  /**
   * If the boiler is on
   * @type {boolean}
   * @memberof InstallerCic
   */
  boilerOn?: boolean;
  /**
   * Temperature in degrees celcius set point of the control
   * @type {number}
   * @memberof InstallerCic
   */
  thermostatControlTemperatureSetPoint: number | null;
  /**
   *
   * @type {CicStatus}
   * @memberof InstallerCic
   */
  status: CicStatus;
  /**
   * The cic serial number
   * @type {string}
   * @memberof InstallerCic
   */
  serial: string | null;
  /**
   *
   * @type {number}
   * @memberof InstallerCic
   */
  numberOfHeatPumps: number | null;
  /**
   * The image version of the cic
   * @type {string}
   * @memberof InstallerCic
   */
  quattBuild: string | null;
  /**
   * The (external) installationId - starts with INS-
   * @type {string}
   * @memberof InstallerCic
   */
  installationId: string;
  /**
   *
   * @type {Date}
   * @memberof InstallerCic
   */
  installedAt: Date | null;
  /**
   * The amount (liter) of water flowing per hour
   * @type {number}
   * @memberof InstallerCic
   */
  flowRate: number | null;
  /**
   * Electricity price for single tariff
   * @type {number}
   * @memberof InstallerCic
   */
  electricityPrice: number | null;
  /**
   * Day electricity price for double tariff
   * @type {number}
   * @memberof InstallerCic
   */
  dayElectricityPrice: number | null;
  /**
   * Night electricity price for double tariff
   * @type {number}
   * @memberof InstallerCic
   */
  nightElectricityPrice: number | null;
  /**
   * Night time start hour for double tariff (weekdays)
   * @type {number}
   * @memberof InstallerCic
   */
  electricityNightTimeStartHour: number;
  /**
   * Night time end hour for double tariff (weekdays)
   * @type {number}
   * @memberof InstallerCic
   */
  electricityNightTimeEndHour: number;
  /**
   * Night time quiet hour start value for the sound slider
   * @type {number}
   * @memberof InstallerCic
   */
  soundNightTimeStartHour: number;
  /**
   * Night time quiet hour end value for the sound slider
   * @type {number}
   * @memberof InstallerCic
   */
  soundNightTimeEndHour: number;
  /**
   * Night time quiet minute start value for the sound slider
   * @type {number}
   * @memberof InstallerCic
   */
  soundNightTimeStartMin: number;
  /**
   * Night time quiet minute end value for the sound slider
   * @type {number}
   * @memberof InstallerCic
   */
  soundNightTimeEndMin: number;
  /**
   * Gas price
   * @type {number}
   * @memberof InstallerCic
   */
  gasPrice: number | null;
  /**
   * When false, send default prices to not limit the heat pump
   * @type {boolean}
   * @memberof InstallerCic
   */
  usePricingToLimitHeatPump: boolean;
  /**
   *
   * @type {SilentMode}
   * @memberof InstallerCic
   */
  silentMode: SilentMode;
  /**
   *
   * @type {Array<HeatPump>}
   * @memberof InstallerCic
   */
  heatPumps: Array<HeatPump>;
  /**
   *
   * @type {number}
   * @memberof InstallerCic
   */
  supervisoryControlMode?: number | null;
  /**
   *
   * @type {boolean}
   * @memberof InstallerCic
   */
  isHp1Connected?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof InstallerCic
   */
  isHp2Connected?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof InstallerCic
   */
  isThermostatConnected?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof InstallerCic
   */
  isBoilerConnected?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof InstallerCic
   */
  isTemperatureSensorConnected?: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof InstallerCic
   */
  isControllerAlive?: boolean | null;
  /**
   * The name of the CIC/house
   * @type {string}
   * @memberof InstallerCic
   */
  name: string | null;
  /**
   *
   * @type {string}
   * @memberof InstallerCic
   */
  zipCode: string | null;
  /**
   *
   * @type {Country}
   * @memberof InstallerCic
   */
  country: Country;
  /**
   * The supported tariff types
   * @type {Set<TariffType>}
   * @memberof InstallerCic
   */
  supportedTariffTypes: Set<TariffType>;
  /**
   *
   * @type {string}
   * @memberof InstallerCic
   */
  orderNumber: string | null;
  /**
   *
   * @type {boolean}
   * @memberof InstallerCic
   */
  wifiEnabled: boolean;
  /**
   *
   * @type {Date}
   * @memberof InstallerCic
   */
  insightsStartAt: Date | null;
  /**
   *
   * @type {boolean}
   * @memberof InstallerCic
   */
  hasSoundSlider: boolean;
  /**
   *
   * @type {MaxSoundLevel}
   * @memberof InstallerCic
   */
  dayMaxSoundLevel: MaxSoundLevel;
  /**
   *
   * @type {MaxSoundLevel}
   * @memberof InstallerCic
   */
  nightMaxSoundLevel: MaxSoundLevel;
  /**
   * Outside temperature in degrees celcius
   * @type {number}
   * @memberof InstallerCic
   */
  temperatureOutside: number | null;
  /**
   * Water temperature in degrees celcius
   * @type {number}
   * @memberof InstallerCic
   */
  waterTemperature: number | null;
  /**
   * CIC supports the forget wifi feature
   * @type {boolean}
   * @memberof InstallerCic
   */
  supportsForgetWifi: boolean;
  /**
   * Is the Quatt Hybrid or All-E currently heating the house
   * @type {boolean}
   * @memberof InstallerCic
   */
  isCentralHeatingOn: boolean | null;
  /**
   * The amount of heat currently produced by the Quatt Hybrid or All-E, in watts
   * @type {number}
   * @memberof InstallerCic
   */
  quattHeatingProductionAmount: number | null;
  /**
   * The amount of electricity currently consumed by the Quatt Hybrid or All-E, in watts
   * @type {number}
   * @memberof InstallerCic
   */
  electricityConsumptionAmount: number | null;
  /**
   *
   * @type {AllEStatus}
   * @memberof InstallerCic
   */
  allEStatus: AllEStatus | null;
  /**
   *
   * @type {Array<HeatDeliverySystem>}
   * @memberof InstallerCic
   */
  heatDeliverySystems: Array<HeatDeliverySystem> | null;
  /**
   *
   * @type {ThermostatType}
   * @memberof InstallerCic
   */
  thermostatType: ThermostatType | null;
  /**
   *
   * @type {BoilerType}
   * @memberof InstallerCic
   */
  boilerType?: BoilerType | null;
  /**
   * The minimal image version the CIC needs to be updated to to install
   * @type {string}
   * @memberof InstallerCic
   */
  quattBuildRequired: string | null;
  /**
   * If the cic needs an update, null if unknown
   * @type {boolean}
   * @memberof InstallerCic
   */
  needsUpdate: boolean | null;
  /**
   * The state of the mender update
   * @type {string}
   * @memberof InstallerCic
   */
  menderUpdateState: InstallerCicMenderUpdateStateEnum;
  /**
   * Rated maximum house power in watt
   * @type {number}
   * @memberof InstallerCic
   */
  ratedMaximumHousePower: number | null;
  /**
   * Temperature in degrees celcius
   * @type {number}
   * @memberof InstallerCic
   */
  maximumHeatingOutdoorTemperature: number | null;
  /**
   *
   * @type {CicCommissioning}
   * @memberof InstallerCic
   */
  lastCommissioning: CicCommissioning;
  /**
   * ISO timestamp of last stat update
   * @type {string}
   * @memberof InstallerCic
   */
  lastStatUpdate?: string | null;
  /**
   * Whether the cic can start commissioning. Not application for the identification test
   * @type {boolean}
   * @memberof InstallerCic
   */
  canStartCommissioning: boolean;
}

/**
 * @export
 */
export const InstallerCicBoilerDemandEnum = {
  Heat: "heat",
} as const;
export type InstallerCicBoilerDemandEnum =
  (typeof InstallerCicBoilerDemandEnum)[keyof typeof InstallerCicBoilerDemandEnum];

/**
 * @export
 */
export const InstallerCicThermostatDemandEnum = {
  Heat: "heat",
} as const;
export type InstallerCicThermostatDemandEnum =
  (typeof InstallerCicThermostatDemandEnum)[keyof typeof InstallerCicThermostatDemandEnum];

/**
 * @export
 */
export const InstallerCicMenderUpdateStateEnum = {
  Idle: "idle",
  Download: "download",
  Install: "install",
} as const;
export type InstallerCicMenderUpdateStateEnum =
  (typeof InstallerCicMenderUpdateStateEnum)[keyof typeof InstallerCicMenderUpdateStateEnum];

/**
 * Check if a given object implements the InstallerCic interface.
 */
export function instanceOfInstallerCic(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "lteConnectionStatus" in value;
  isInstance = isInstance && "cableConnectionStatus" in value;
  isInstance = isInstance && "wifiConnectionStatus" in value;
  isInstance = isInstance && "wifiSSID" in value;
  isInstance = isInstance && "availableWifiNetworks" in value;
  isInstance = isInstance && "lastScannedForWifi" in value;
  isInstance = isInstance && "isScanningForWifi" in value;
  isInstance = isInstance && "thermostatDemand" in value;
  isInstance = isInstance && "thermostatRoomTemperature" in value;
  isInstance = isInstance && "thermostatRoomTemperatureSetPoint" in value;
  isInstance = isInstance && "thermostatFlameOn" in value;
  isInstance = isInstance && "showThermostatTemperatures" in value;
  isInstance = isInstance && "thermostatControlTemperatureSetPoint" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "serial" in value;
  isInstance = isInstance && "numberOfHeatPumps" in value;
  isInstance = isInstance && "quattBuild" in value;
  isInstance = isInstance && "installationId" in value;
  isInstance = isInstance && "installedAt" in value;
  isInstance = isInstance && "flowRate" in value;
  isInstance = isInstance && "electricityPrice" in value;
  isInstance = isInstance && "dayElectricityPrice" in value;
  isInstance = isInstance && "nightElectricityPrice" in value;
  isInstance = isInstance && "electricityNightTimeStartHour" in value;
  isInstance = isInstance && "electricityNightTimeEndHour" in value;
  isInstance = isInstance && "soundNightTimeStartHour" in value;
  isInstance = isInstance && "soundNightTimeEndHour" in value;
  isInstance = isInstance && "soundNightTimeStartMin" in value;
  isInstance = isInstance && "soundNightTimeEndMin" in value;
  isInstance = isInstance && "gasPrice" in value;
  isInstance = isInstance && "usePricingToLimitHeatPump" in value;
  isInstance = isInstance && "silentMode" in value;
  isInstance = isInstance && "heatPumps" in value;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "zipCode" in value;
  isInstance = isInstance && "country" in value;
  isInstance = isInstance && "supportedTariffTypes" in value;
  isInstance = isInstance && "orderNumber" in value;
  isInstance = isInstance && "wifiEnabled" in value;
  isInstance = isInstance && "insightsStartAt" in value;
  isInstance = isInstance && "hasSoundSlider" in value;
  isInstance = isInstance && "dayMaxSoundLevel" in value;
  isInstance = isInstance && "nightMaxSoundLevel" in value;
  isInstance = isInstance && "temperatureOutside" in value;
  isInstance = isInstance && "waterTemperature" in value;
  isInstance = isInstance && "supportsForgetWifi" in value;
  isInstance = isInstance && "isCentralHeatingOn" in value;
  isInstance = isInstance && "quattHeatingProductionAmount" in value;
  isInstance = isInstance && "electricityConsumptionAmount" in value;
  isInstance = isInstance && "allEStatus" in value;
  isInstance = isInstance && "heatDeliverySystems" in value;
  isInstance = isInstance && "thermostatType" in value;
  isInstance = isInstance && "quattBuildRequired" in value;
  isInstance = isInstance && "needsUpdate" in value;
  isInstance = isInstance && "menderUpdateState" in value;
  isInstance = isInstance && "ratedMaximumHousePower" in value;
  isInstance = isInstance && "maximumHeatingOutdoorTemperature" in value;
  isInstance = isInstance && "lastCommissioning" in value;
  isInstance = isInstance && "canStartCommissioning" in value;

  return isInstance;
}

export function InstallerCicFromJSON(json: any): InstallerCic {
  return InstallerCicFromJSONTyped(json, false);
}

export function InstallerCicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InstallerCic {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    lteConnectionStatus: ConnectionStatusFromJSON(json["lteConnectionStatus"]),
    cableConnectionStatus: ConnectionStatusFromJSON(
      json["cableConnectionStatus"],
    ),
    wifiConnectionStatus: ConnectionStatusFromJSON(
      json["wifiConnectionStatus"],
    ),
    wifiSSID: json["wifiSSID"],
    availableWifiNetworks:
      json["availableWifiNetworks"] === null
        ? null
        : (json["availableWifiNetworks"] as Array<any>).map(
            CicAvailableWifiNetworksInnerFromJSON,
          ),
    lastScannedForWifi:
      json["lastScannedForWifi"] === null
        ? null
        : new Date(json["lastScannedForWifi"]),
    isScanningForWifi: json["isScanningForWifi"],
    boilerDemand: !exists(json, "boilerDemand")
      ? undefined
      : json["boilerDemand"],
    boilerPower: !exists(json, "boilerPower") ? undefined : json["boilerPower"],
    boilerWaterTemperatureIn: !exists(json, "boilerWaterTemperatureIn")
      ? undefined
      : json["boilerWaterTemperatureIn"],
    boilerWaterTemperatureOut: !exists(json, "boilerWaterTemperatureOut")
      ? undefined
      : json["boilerWaterTemperatureOut"],
    heatingWaterTemperatureIn: !exists(json, "heatingWaterTemperatureIn")
      ? undefined
      : json["heatingWaterTemperatureIn"],
    heatingWaterTemperatureOut: !exists(json, "heatingWaterTemperatureOut")
      ? undefined
      : json["heatingWaterTemperatureOut"],
    boilerPressure: !exists(json, "boilerPressure")
      ? undefined
      : json["boilerPressure"],
    thermostatDemand: json["thermostatDemand"],
    thermostatRoomTemperature: json["thermostatRoomTemperature"],
    thermostatRoomTemperatureSetPoint:
      json["thermostatRoomTemperatureSetPoint"],
    thermostatFlameOn: json["thermostatFlameOn"],
    showThermostatTemperatures: json["showThermostatTemperatures"],
    boilerOn: !exists(json, "boilerOn") ? undefined : json["boilerOn"],
    thermostatControlTemperatureSetPoint:
      json["thermostatControlTemperatureSetPoint"],
    status: CicStatusFromJSON(json["status"]),
    serial: json["serial"],
    numberOfHeatPumps: json["numberOfHeatPumps"],
    quattBuild: json["quattBuild"],
    installationId: json["installationId"],
    installedAt:
      json["installedAt"] === null ? null : new Date(json["installedAt"]),
    flowRate: json["flowRate"],
    electricityPrice: json["electricityPrice"],
    dayElectricityPrice: json["dayElectricityPrice"],
    nightElectricityPrice: json["nightElectricityPrice"],
    electricityNightTimeStartHour: json["electricityNightTimeStartHour"],
    electricityNightTimeEndHour: json["electricityNightTimeEndHour"],
    soundNightTimeStartHour: json["soundNightTimeStartHour"],
    soundNightTimeEndHour: json["soundNightTimeEndHour"],
    soundNightTimeStartMin: json["soundNightTimeStartMin"],
    soundNightTimeEndMin: json["soundNightTimeEndMin"],
    gasPrice: json["gasPrice"],
    usePricingToLimitHeatPump: json["usePricingToLimitHeatPump"],
    silentMode: SilentModeFromJSON(json["silentMode"]),
    heatPumps: (json["heatPumps"] as Array<any>).map(HeatPumpFromJSON),
    supervisoryControlMode: !exists(json, "supervisoryControlMode")
      ? undefined
      : json["supervisoryControlMode"],
    isHp1Connected: !exists(json, "isHp1Connected")
      ? undefined
      : json["isHp1Connected"],
    isHp2Connected: !exists(json, "isHp2Connected")
      ? undefined
      : json["isHp2Connected"],
    isThermostatConnected: !exists(json, "isThermostatConnected")
      ? undefined
      : json["isThermostatConnected"],
    isBoilerConnected: !exists(json, "isBoilerConnected")
      ? undefined
      : json["isBoilerConnected"],
    isTemperatureSensorConnected: !exists(json, "isTemperatureSensorConnected")
      ? undefined
      : json["isTemperatureSensorConnected"],
    isControllerAlive: !exists(json, "isControllerAlive")
      ? undefined
      : json["isControllerAlive"],
    name: json["name"],
    zipCode: json["zipCode"],
    country: CountryFromJSON(json["country"]),
    supportedTariffTypes: new Set(
      (json["supportedTariffTypes"] as Array<any>).map(TariffTypeFromJSON),
    ),
    orderNumber: json["orderNumber"],
    wifiEnabled: json["wifiEnabled"],
    insightsStartAt:
      json["insightsStartAt"] === null
        ? null
        : new Date(json["insightsStartAt"]),
    hasSoundSlider: json["hasSoundSlider"],
    dayMaxSoundLevel: MaxSoundLevelFromJSON(json["dayMaxSoundLevel"]),
    nightMaxSoundLevel: MaxSoundLevelFromJSON(json["nightMaxSoundLevel"]),
    temperatureOutside: json["temperatureOutside"],
    waterTemperature: json["waterTemperature"],
    supportsForgetWifi: json["supportsForgetWifi"],
    isCentralHeatingOn: json["isCentralHeatingOn"],
    quattHeatingProductionAmount: json["quattHeatingProductionAmount"],
    electricityConsumptionAmount: json["electricityConsumptionAmount"],
    allEStatus: AllEStatusFromJSON(json["allEStatus"]),
    heatDeliverySystems:
      json["heatDeliverySystems"] === null
        ? null
        : (json["heatDeliverySystems"] as Array<any>).map(
            HeatDeliverySystemFromJSON,
          ),
    thermostatType: ThermostatTypeFromJSON(json["thermostatType"]),
    boilerType: !exists(json, "boilerType")
      ? undefined
      : BoilerTypeFromJSON(json["boilerType"]),
    quattBuildRequired: json["quattBuildRequired"],
    needsUpdate: json["needsUpdate"],
    menderUpdateState: json["menderUpdateState"],
    ratedMaximumHousePower: json["ratedMaximumHousePower"],
    maximumHeatingOutdoorTemperature: json["maximumHeatingOutdoorTemperature"],
    lastCommissioning: CicCommissioningFromJSON(json["lastCommissioning"]),
    lastStatUpdate: !exists(json, "lastStatUpdate")
      ? undefined
      : json["lastStatUpdate"],
    canStartCommissioning: json["canStartCommissioning"],
  };
}

export function InstallerCicToJSON(value?: InstallerCic | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    lteConnectionStatus: ConnectionStatusToJSON(value.lteConnectionStatus),
    cableConnectionStatus: ConnectionStatusToJSON(value.cableConnectionStatus),
    wifiConnectionStatus: ConnectionStatusToJSON(value.wifiConnectionStatus),
    wifiSSID: value.wifiSSID,
    availableWifiNetworks:
      value.availableWifiNetworks === null
        ? null
        : (value.availableWifiNetworks as Array<any>).map(
            CicAvailableWifiNetworksInnerToJSON,
          ),
    lastScannedForWifi:
      value.lastScannedForWifi === null
        ? null
        : value.lastScannedForWifi.toISOString(),
    isScanningForWifi: value.isScanningForWifi,
    boilerDemand: value.boilerDemand,
    boilerPower: value.boilerPower,
    boilerWaterTemperatureIn: value.boilerWaterTemperatureIn,
    boilerWaterTemperatureOut: value.boilerWaterTemperatureOut,
    heatingWaterTemperatureIn: value.heatingWaterTemperatureIn,
    heatingWaterTemperatureOut: value.heatingWaterTemperatureOut,
    boilerPressure: value.boilerPressure,
    thermostatDemand: value.thermostatDemand,
    thermostatRoomTemperature: value.thermostatRoomTemperature,
    thermostatRoomTemperatureSetPoint: value.thermostatRoomTemperatureSetPoint,
    thermostatFlameOn: value.thermostatFlameOn,
    showThermostatTemperatures: value.showThermostatTemperatures,
    boilerOn: value.boilerOn,
    thermostatControlTemperatureSetPoint:
      value.thermostatControlTemperatureSetPoint,
    status: CicStatusToJSON(value.status),
    serial: value.serial,
    numberOfHeatPumps: value.numberOfHeatPumps,
    quattBuild: value.quattBuild,
    installationId: value.installationId,
    installedAt:
      value.installedAt === null ? null : value.installedAt.toISOString(),
    flowRate: value.flowRate,
    electricityPrice: value.electricityPrice,
    dayElectricityPrice: value.dayElectricityPrice,
    nightElectricityPrice: value.nightElectricityPrice,
    electricityNightTimeStartHour: value.electricityNightTimeStartHour,
    electricityNightTimeEndHour: value.electricityNightTimeEndHour,
    soundNightTimeStartHour: value.soundNightTimeStartHour,
    soundNightTimeEndHour: value.soundNightTimeEndHour,
    soundNightTimeStartMin: value.soundNightTimeStartMin,
    soundNightTimeEndMin: value.soundNightTimeEndMin,
    gasPrice: value.gasPrice,
    usePricingToLimitHeatPump: value.usePricingToLimitHeatPump,
    silentMode: SilentModeToJSON(value.silentMode),
    heatPumps: (value.heatPumps as Array<any>).map(HeatPumpToJSON),
    supervisoryControlMode: value.supervisoryControlMode,
    isHp1Connected: value.isHp1Connected,
    isHp2Connected: value.isHp2Connected,
    isThermostatConnected: value.isThermostatConnected,
    isBoilerConnected: value.isBoilerConnected,
    isTemperatureSensorConnected: value.isTemperatureSensorConnected,
    isControllerAlive: value.isControllerAlive,
    name: value.name,
    zipCode: value.zipCode,
    country: CountryToJSON(value.country),
    supportedTariffTypes: Array.from(
      value.supportedTariffTypes as Set<any>,
    ).map(TariffTypeToJSON),
    orderNumber: value.orderNumber,
    wifiEnabled: value.wifiEnabled,
    insightsStartAt:
      value.insightsStartAt === null
        ? null
        : value.insightsStartAt.toISOString(),
    hasSoundSlider: value.hasSoundSlider,
    dayMaxSoundLevel: MaxSoundLevelToJSON(value.dayMaxSoundLevel),
    nightMaxSoundLevel: MaxSoundLevelToJSON(value.nightMaxSoundLevel),
    temperatureOutside: value.temperatureOutside,
    waterTemperature: value.waterTemperature,
    supportsForgetWifi: value.supportsForgetWifi,
    isCentralHeatingOn: value.isCentralHeatingOn,
    quattHeatingProductionAmount: value.quattHeatingProductionAmount,
    electricityConsumptionAmount: value.electricityConsumptionAmount,
    allEStatus: AllEStatusToJSON(value.allEStatus),
    heatDeliverySystems:
      value.heatDeliverySystems === null
        ? null
        : (value.heatDeliverySystems as Array<any>).map(
            HeatDeliverySystemToJSON,
          ),
    thermostatType: ThermostatTypeToJSON(value.thermostatType),
    boilerType: BoilerTypeToJSON(value.boilerType),
    quattBuildRequired: value.quattBuildRequired,
    needsUpdate: value.needsUpdate,
    menderUpdateState: value.menderUpdateState,
    ratedMaximumHousePower: value.ratedMaximumHousePower,
    maximumHeatingOutdoorTemperature: value.maximumHeatingOutdoorTemperature,
    lastCommissioning: CicCommissioningToJSON(value.lastCommissioning),
    lastStatUpdate: value.lastStatUpdate,
    canStartCommissioning: value.canStartCommissioning,
  };
}
