/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { InstallationHealthCheckModeReparation } from "./InstallationHealthCheckModeReparation";
import {
  InstallationHealthCheckModeReparationFromJSON,
  InstallationHealthCheckModeReparationFromJSONTyped,
  InstallationHealthCheckModeReparationToJSON,
} from "./InstallationHealthCheckModeReparation";

/**
 *
 * @export
 * @interface InstallationHealthCheck
 */
export interface InstallationHealthCheck {
  /**
   *
   * @type {number}
   * @memberof InstallationHealthCheck
   */
  roomTemperature: number | null;
  /**
   *
   * @type {number}
   * @memberof InstallationHealthCheck
   */
  roomSetpoint: number | null;
  /**
   *
   * @type {number}
   * @memberof InstallationHealthCheck
   */
  setpointAdherence: number | null;
  /**
   *
   * @type {InstallationHealthCheckModeReparation}
   * @memberof InstallationHealthCheck
   */
  modeReparation: InstallationHealthCheckModeReparation | null;
  /**
   *
   * @type {string}
   * @memberof InstallationHealthCheck
   */
  supervisoryControlMode: string;
}

/**
 * Check if a given object implements the InstallationHealthCheck interface.
 */
export function instanceOfInstallationHealthCheck(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "roomTemperature" in value;
  isInstance = isInstance && "roomSetpoint" in value;
  isInstance = isInstance && "setpointAdherence" in value;
  isInstance = isInstance && "modeReparation" in value;
  isInstance = isInstance && "supervisoryControlMode" in value;

  return isInstance;
}

export function InstallationHealthCheckFromJSON(
  json: any,
): InstallationHealthCheck {
  return InstallationHealthCheckFromJSONTyped(json, false);
}

export function InstallationHealthCheckFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InstallationHealthCheck {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    roomTemperature: json["roomTemperature"],
    roomSetpoint: json["roomSetpoint"],
    setpointAdherence: json["setpointAdherence"],
    modeReparation: InstallationHealthCheckModeReparationFromJSON(
      json["modeReparation"],
    ),
    supervisoryControlMode: json["supervisoryControlMode"],
  };
}

export function InstallationHealthCheckToJSON(
  value?: InstallationHealthCheck | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    roomTemperature: value.roomTemperature,
    roomSetpoint: value.roomSetpoint,
    setpointAdherence: value.setpointAdherence,
    modeReparation: InstallationHealthCheckModeReparationToJSON(
      value.modeReparation,
    ),
    supervisoryControlMode: value.supervisoryControlMode,
  };
}
