/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InstallationHealthCheckModeReparation
 */
export interface InstallationHealthCheckModeReparation {
  /**
   *
   * @type {number}
   * @memberof InstallationHealthCheckModeReparation
   */
  idle: number;
  /**
   *
   * @type {number}
   * @memberof InstallationHealthCheckModeReparation
   */
  quatt: number;
  /**
   *
   * @type {number}
   * @memberof InstallationHealthCheckModeReparation
   */
  combo: number;
  /**
   *
   * @type {number}
   * @memberof InstallationHealthCheckModeReparation
   */
  boiler: number;
  /**
   *
   * @type {number}
   * @memberof InstallationHealthCheckModeReparation
   */
  antiFreezeProtection: number;
}

/**
 * Check if a given object implements the InstallationHealthCheckModeReparation interface.
 */
export function instanceOfInstallationHealthCheckModeReparation(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "idle" in value;
  isInstance = isInstance && "quatt" in value;
  isInstance = isInstance && "combo" in value;
  isInstance = isInstance && "boiler" in value;
  isInstance = isInstance && "antiFreezeProtection" in value;

  return isInstance;
}

export function InstallationHealthCheckModeReparationFromJSON(
  json: any,
): InstallationHealthCheckModeReparation {
  return InstallationHealthCheckModeReparationFromJSONTyped(json, false);
}

export function InstallationHealthCheckModeReparationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InstallationHealthCheckModeReparation {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    idle: json["idle"],
    quatt: json["quatt"],
    combo: json["combo"],
    boiler: json["boiler"],
    antiFreezeProtection: json["antiFreezeProtection"],
  };
}

export function InstallationHealthCheckModeReparationToJSON(
  value?: InstallationHealthCheckModeReparation | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    idle: value.idle,
    quatt: value.quatt,
    combo: value.combo,
    boiler: value.boiler,
    antiFreezeProtection: value.antiFreezeProtection,
  };
}
