/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface LinkInstallerRequest
 */
export interface LinkInstallerRequest {
  /**
   *
   * @type {string}
   * @memberof LinkInstallerRequest
   */
  installerCode: string;
}

/**
 * Check if a given object implements the LinkInstallerRequest interface.
 */
export function instanceOfLinkInstallerRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "installerCode" in value;

  return isInstance;
}

export function LinkInstallerRequestFromJSON(json: any): LinkInstallerRequest {
  return LinkInstallerRequestFromJSONTyped(json, false);
}

export function LinkInstallerRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LinkInstallerRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    installerCode: json["installerCode"],
  };
}

export function LinkInstallerRequestToJSON(
  value?: LinkInstallerRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    installerCode: value.installerCode,
  };
}
