/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface LinkHubspotInstallerCicRequest
 */
export interface LinkHubspotInstallerCicRequest {
  /**
   *
   * @type {string}
   * @memberof LinkHubspotInstallerCicRequest
   */
  orderNumber: string;
  /**
   *
   * @type {string}
   * @memberof LinkHubspotInstallerCicRequest
   */
  zipCode: string;
  /**
   * Check if install is for today
   * @type {boolean}
   * @memberof LinkHubspotInstallerCicRequest
   */
  checkScheduledInstallationDate?: boolean;
  /**
   * Allow install date to be in the past
   * @type {boolean}
   * @memberof LinkHubspotInstallerCicRequest
   */
  allowWrongInstallationDate?: boolean;
}

/**
 * Check if a given object implements the LinkHubspotInstallerCicRequest interface.
 */
export function instanceOfLinkHubspotInstallerCicRequest(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "orderNumber" in value;
  isInstance = isInstance && "zipCode" in value;

  return isInstance;
}

export function LinkHubspotInstallerCicRequestFromJSON(
  json: any,
): LinkHubspotInstallerCicRequest {
  return LinkHubspotInstallerCicRequestFromJSONTyped(json, false);
}

export function LinkHubspotInstallerCicRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LinkHubspotInstallerCicRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    orderNumber: json["orderNumber"],
    zipCode: json["zipCode"],
    checkScheduledInstallationDate: !exists(
      json,
      "checkScheduledInstallationDate",
    )
      ? undefined
      : json["checkScheduledInstallationDate"],
    allowWrongInstallationDate: !exists(json, "allowWrongInstallationDate")
      ? undefined
      : json["allowWrongInstallationDate"],
  };
}

export function LinkHubspotInstallerCicRequestToJSON(
  value?: LinkHubspotInstallerCicRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    orderNumber: value.orderNumber,
    zipCode: value.zipCode,
    checkScheduledInstallationDate: value.checkScheduledInstallationDate,
    allowWrongInstallationDate: value.allowWrongInstallationDate,
  };
}
