/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface NamedPumpPower
 */
export interface NamedPumpPower {
  /**
   * The power of the pump of the unit in kwH
   * @type {number}
   * @memberof NamedPumpPower
   */
  power: number | null;
  /**
   * The temperature coming in the pump of the unit in celsius
   * @type {number}
   * @memberof NamedPumpPower
   */
  inletTemperature: number | null;
  /**
   * The temperature going out of the pump of the unit in celsius
   * @type {number}
   * @memberof NamedPumpPower
   */
  outletTemperature: number | null;
  /**
   * The name of the outdoor unit
   * @type {string}
   * @memberof NamedPumpPower
   */
  name: string;
}

/**
 * Check if a given object implements the NamedPumpPower interface.
 */
export function instanceOfNamedPumpPower(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "power" in value;
  isInstance = isInstance && "inletTemperature" in value;
  isInstance = isInstance && "outletTemperature" in value;
  isInstance = isInstance && "name" in value;

  return isInstance;
}

export function NamedPumpPowerFromJSON(json: any): NamedPumpPower {
  return NamedPumpPowerFromJSONTyped(json, false);
}

export function NamedPumpPowerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NamedPumpPower {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    power: json["power"],
    inletTemperature: json["inletTemperature"],
    outletTemperature: json["outletTemperature"],
    name: json["name"],
  };
}

export function NamedPumpPowerToJSON(value?: NamedPumpPower | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    power: value.power,
    inletTemperature: value.inletTemperature,
    outletTemperature: value.outletTemperature,
    name: value.name,
  };
}
