/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface NullableTariff
 */
export interface NullableTariff {
  /**
   *
   * @type {string}
   * @memberof NullableTariff
   */
  id?: string;
  /**
   * Electricity price for single tariff
   * @type {number}
   * @memberof NullableTariff
   */
  electricityPrice?: number | null;
  /**
   * Day electricity price for double tariff
   * @type {number}
   * @memberof NullableTariff
   */
  dayElectricityPrice?: number | null;
  /**
   * Night electricity price for double tariff
   * @type {number}
   * @memberof NullableTariff
   */
  nightElectricityPrice?: number | null;
  /**
   * Gas price
   * @type {number}
   * @memberof NullableTariff
   */
  gasPrice: number;
  /**
   * The date in ISO 8601 format (YYYY-MM-DD). This schema is used to represent dates in various contexts, such as event dates, deadlines, or any other date-related information.
   *
   * @type {Date}
   * @memberof NullableTariff
   */
  validFrom: Date;
  /**
   * If the tariff can be deleted
   * @type {boolean}
   * @memberof NullableTariff
   */
  isDeletable: boolean;
  /**
   * If the date can be edited
   * @type {boolean}
   * @memberof NullableTariff
   */
  isDateEditable: boolean;
}

/**
 * Check if a given object implements the NullableTariff interface.
 */
export function instanceOfNullableTariff(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "gasPrice" in value;
  isInstance = isInstance && "validFrom" in value;
  isInstance = isInstance && "isDeletable" in value;
  isInstance = isInstance && "isDateEditable" in value;

  return isInstance;
}

export function NullableTariffFromJSON(json: any): NullableTariff {
  return NullableTariffFromJSONTyped(json, false);
}

export function NullableTariffFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NullableTariff {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    electricityPrice: !exists(json, "electricityPrice")
      ? undefined
      : json["electricityPrice"],
    dayElectricityPrice: !exists(json, "dayElectricityPrice")
      ? undefined
      : json["dayElectricityPrice"],
    nightElectricityPrice: !exists(json, "nightElectricityPrice")
      ? undefined
      : json["nightElectricityPrice"],
    gasPrice: json["gasPrice"],
    validFrom: new Date(json["validFrom"]),
    isDeletable: json["isDeletable"],
    isDateEditable: json["isDateEditable"],
  };
}

export function NullableTariffToJSON(value?: NullableTariff | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    electricityPrice: value.electricityPrice,
    dayElectricityPrice: value.dayElectricityPrice,
    nightElectricityPrice: value.nightElectricityPrice,
    gasPrice: value.gasPrice,
    validFrom: value.validFrom.toISOString().substring(0, 10),
    isDeletable: value.isDeletable,
    isDateEditable: value.isDateEditable,
  };
}
