/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { DeviceStatus } from "./DeviceStatus";
import {
  DeviceStatusFromJSON,
  DeviceStatusFromJSONTyped,
  DeviceStatusToJSON,
} from "./DeviceStatus";

/**
 *
 * @export
 * @interface OutDoorUnitDevice
 */
export interface OutDoorUnitDevice {
  /**
   *
   * @type {string}
   * @memberof OutDoorUnitDevice
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof OutDoorUnitDevice
   */
  cicUuid?: string | null;
  /**
   *
   * @type {string}
   * @memberof OutDoorUnitDevice
   */
  name?: string | null;
  /**
   *
   * @type {DeviceStatus}
   * @memberof OutDoorUnitDevice
   */
  status: DeviceStatus;
  /**
   *
   * @type {string}
   * @memberof OutDoorUnitDevice
   */
  installationUuid?: string | null;
  /**
   *
   * @type {string}
   * @memberof OutDoorUnitDevice
   */
  type: OutDoorUnitDeviceTypeEnum;
  /**
   *
   * @type {number}
   * @memberof OutDoorUnitDevice
   */
  revisionId: number | null;
  /**
   *
   * @type {string}
   * @memberof OutDoorUnitDevice
   */
  oduType?: string | null;
}

/**
 * @export
 */
export const OutDoorUnitDeviceTypeEnum = {
  OutdoorUnit: "OUTDOOR_UNIT",
} as const;
export type OutDoorUnitDeviceTypeEnum =
  (typeof OutDoorUnitDeviceTypeEnum)[keyof typeof OutDoorUnitDeviceTypeEnum];

/**
 * Check if a given object implements the OutDoorUnitDevice interface.
 */
export function instanceOfOutDoorUnitDevice(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "type" in value;
  isInstance = isInstance && "revisionId" in value;

  return isInstance;
}

export function OutDoorUnitDeviceFromJSON(json: any): OutDoorUnitDevice {
  return OutDoorUnitDeviceFromJSONTyped(json, false);
}

export function OutDoorUnitDeviceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OutDoorUnitDevice {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    cicUuid: !exists(json, "cicUuid") ? undefined : json["cicUuid"],
    name: !exists(json, "name") ? undefined : json["name"],
    status: DeviceStatusFromJSON(json["status"]),
    installationUuid: !exists(json, "installationUuid")
      ? undefined
      : json["installationUuid"],
    type: json["type"],
    revisionId: json["revisionId"],
    oduType: !exists(json, "oduType") ? undefined : json["oduType"],
  };
}

export function OutDoorUnitDeviceToJSON(value?: OutDoorUnitDevice | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    cicUuid: value.cicUuid,
    name: value.name,
    status: DeviceStatusToJSON(value.status),
    installationUuid: value.installationUuid,
    type: value.type,
    revisionId: value.revisionId,
    oduType: value.oduType,
  };
}
