/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface OutDoorUnitDevice
 */
export interface OutDoorUnitDevice {
  /**
   *
   * @type {string}
   * @memberof OutDoorUnitDevice
   */
  uuid: string;
  /**
   *
   * @type {string}
   * @memberof OutDoorUnitDevice
   */
  identificationStatus: OutDoorUnitDeviceIdentificationStatusEnum;
  /**
   *
   * @type {string}
   * @memberof OutDoorUnitDevice
   */
  cicUuid: string;
  /**
   *
   * @type {string}
   * @memberof OutDoorUnitDevice
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof OutDoorUnitDevice
   */
  type: OutDoorUnitDeviceTypeEnum;
  /**
   *
   * @type {number}
   * @memberof OutDoorUnitDevice
   */
  revisionId: number | null;
}

/**
 * @export
 */
export const OutDoorUnitDeviceIdentificationStatusEnum = {
  Success: "SUCCESS",
  Failed: "FAILED",
  Unidentified: "UNIDENTIFIED",
} as const;
export type OutDoorUnitDeviceIdentificationStatusEnum =
  (typeof OutDoorUnitDeviceIdentificationStatusEnum)[keyof typeof OutDoorUnitDeviceIdentificationStatusEnum];

/**
 * @export
 */
export const OutDoorUnitDeviceTypeEnum = {
  OutdoorUnit: "OUTDOOR_UNIT",
} as const;
export type OutDoorUnitDeviceTypeEnum =
  (typeof OutDoorUnitDeviceTypeEnum)[keyof typeof OutDoorUnitDeviceTypeEnum];

/**
 * Check if a given object implements the OutDoorUnitDevice interface.
 */
export function instanceOfOutDoorUnitDevice(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "uuid" in value;
  isInstance = isInstance && "identificationStatus" in value;
  isInstance = isInstance && "cicUuid" in value;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "type" in value;
  isInstance = isInstance && "revisionId" in value;

  return isInstance;
}

export function OutDoorUnitDeviceFromJSON(json: any): OutDoorUnitDevice {
  return OutDoorUnitDeviceFromJSONTyped(json, false);
}

export function OutDoorUnitDeviceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OutDoorUnitDevice {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: json["uuid"],
    identificationStatus: json["identificationStatus"],
    cicUuid: json["cicUuid"],
    name: json["name"],
    type: json["type"],
    revisionId: json["revisionId"],
  };
}

export function OutDoorUnitDeviceToJSON(value?: OutDoorUnitDevice | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    identificationStatus: value.identificationStatus,
    cicUuid: value.cicUuid,
    name: value.name,
    type: value.type,
    revisionId: value.revisionId,
  };
}
