/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PumpPower
 */
export interface PumpPower {
  /**
   * The power of the pump of the unit in kwH
   * @type {number}
   * @memberof PumpPower
   */
  power: number | null;
  /**
   * The temperature coming in the pump of the unit in celsius
   * @type {number}
   * @memberof PumpPower
   */
  inletTemperature: number | null;
  /**
   * The temperature going out of the pump of the unit in celsius
   * @type {number}
   * @memberof PumpPower
   */
  outletTemperature: number | null;
}

/**
 * Check if a given object implements the PumpPower interface.
 */
export function instanceOfPumpPower(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "power" in value;
  isInstance = isInstance && "inletTemperature" in value;
  isInstance = isInstance && "outletTemperature" in value;

  return isInstance;
}

export function PumpPowerFromJSON(json: any): PumpPower {
  return PumpPowerFromJSONTyped(json, false);
}

export function PumpPowerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PumpPower {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    power: json["power"],
    inletTemperature: json["inletTemperature"],
    outletTemperature: json["outletTemperature"],
  };
}

export function PumpPowerToJSON(value?: PumpPower | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    power: value.power,
    inletTemperature: value.inletTemperature,
    outletTemperature: value.outletTemperature,
  };
}
