/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ReferralMember
 */
export interface ReferralMember {
  /**
   *
   * @type {string}
   * @memberof ReferralMember
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ReferralMember
   */
  referralUrl: string;
  /**
   *
   * @type {string}
   * @memberof ReferralMember
   */
  email: string;
}

/**
 * Check if a given object implements the ReferralMember interface.
 */
export function instanceOfReferralMember(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "referralUrl" in value;
  isInstance = isInstance && "email" in value;

  return isInstance;
}

export function ReferralMemberFromJSON(json: any): ReferralMember {
  return ReferralMemberFromJSONTyped(json, false);
}

export function ReferralMemberFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReferralMember {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    referralUrl: json["referralUrl"],
    email: json["email"],
  };
}

export function ReferralMemberToJSON(value?: ReferralMember | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    referralUrl: value.referralUrl,
    email: value.email,
  };
}
