/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ChillInterfaceBoard } from "./ChillInterfaceBoard";
import {
  ChillInterfaceBoardFromJSON,
  ChillInterfaceBoardFromJSONTyped,
  ChillInterfaceBoardToJSON,
} from "./ChillInterfaceBoard";

/**
 * Response containing both deactivated and activated boards
 * @export
 * @interface ReplaceChillInterfaceBoardResponse
 */
export interface ReplaceChillInterfaceBoardResponse {
  /**
   *
   * @type {ChillInterfaceBoard}
   * @memberof ReplaceChillInterfaceBoardResponse
   */
  oldBoard: ChillInterfaceBoard;
  /**
   *
   * @type {ChillInterfaceBoard}
   * @memberof ReplaceChillInterfaceBoardResponse
   */
  newBoard: ChillInterfaceBoard;
}

/**
 * Check if a given object implements the ReplaceChillInterfaceBoardResponse interface.
 */
export function instanceOfReplaceChillInterfaceBoardResponse(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "oldBoard" in value;
  isInstance = isInstance && "newBoard" in value;

  return isInstance;
}

export function ReplaceChillInterfaceBoardResponseFromJSON(
  json: any,
): ReplaceChillInterfaceBoardResponse {
  return ReplaceChillInterfaceBoardResponseFromJSONTyped(json, false);
}

export function ReplaceChillInterfaceBoardResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReplaceChillInterfaceBoardResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    oldBoard: ChillInterfaceBoardFromJSON(json["oldBoard"]),
    newBoard: ChillInterfaceBoardFromJSON(json["newBoard"]),
  };
}

export function ReplaceChillInterfaceBoardResponseToJSON(
  value?: ReplaceChillInterfaceBoardResponse | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    oldBoard: ChillInterfaceBoardToJSON(value.oldBoard),
    newBoard: ChillInterfaceBoardToJSON(value.newBoard),
  };
}
