/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RequestPairInstallerCicRequest
 */
export interface RequestPairInstallerCicRequest {
  /**
   *
   * @type {string}
   * @memberof RequestPairInstallerCicRequest
   */
  orderNumber?: string;
}

/**
 * Check if a given object implements the RequestPairInstallerCicRequest interface.
 */
export function instanceOfRequestPairInstallerCicRequest(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function RequestPairInstallerCicRequestFromJSON(
  json: any,
): RequestPairInstallerCicRequest {
  return RequestPairInstallerCicRequestFromJSONTyped(json, false);
}

export function RequestPairInstallerCicRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RequestPairInstallerCicRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    orderNumber: !exists(json, "orderNumber") ? undefined : json["orderNumber"],
  };
}

export function RequestPairInstallerCicRequestToJSON(
  value?: RequestPairInstallerCicRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    orderNumber: value.orderNumber,
  };
}
