/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * Information about this response (response time and status)
 * @export
 * @interface ResponseMeta
 */
export interface ResponseMeta {
  /**
   *
   * @type {number}
   * @memberof ResponseMeta
   */
  status: number;
  /**
   *
   * @type {number}
   * @memberof ResponseMeta
   */
  took: number;
}

/**
 * Check if a given object implements the ResponseMeta interface.
 */
export function instanceOfResponseMeta(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "status" in value;
  isInstance = isInstance && "took" in value;

  return isInstance;
}

export function ResponseMetaFromJSON(json: any): ResponseMeta {
  return ResponseMetaFromJSONTyped(json, false);
}

export function ResponseMetaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponseMeta {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    status: json["status"],
    took: json["took"],
  };
}

export function ResponseMetaToJSON(value?: ResponseMeta | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    status: value.status,
    took: value.took,
  };
}
