/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { CommandType } from "./CommandType";
import {
  CommandTypeFromJSON,
  CommandTypeFromJSONTyped,
  CommandTypeToJSON,
} from "./CommandType";

/**
 *
 * @export
 * @interface SendCommandToCICRequest
 */
export interface SendCommandToCICRequest {
  /**
   *
   * @type {CommandType}
   * @memberof SendCommandToCICRequest
   */
  type: CommandType;
}

/**
 * Check if a given object implements the SendCommandToCICRequest interface.
 */
export function instanceOfSendCommandToCICRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "type" in value;

  return isInstance;
}

export function SendCommandToCICRequestFromJSON(
  json: any,
): SendCommandToCICRequest {
  return SendCommandToCICRequestFromJSONTyped(json, false);
}

export function SendCommandToCICRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendCommandToCICRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: CommandTypeFromJSON(json["type"]),
  };
}

export function SendCommandToCICRequestToJSON(
  value?: SendCommandToCICRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: CommandTypeToJSON(value.type),
  };
}
