/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { BoilerType } from "./BoilerType";
import {
  BoilerTypeFromJSON,
  BoilerTypeFromJSONTyped,
  BoilerTypeToJSON,
} from "./BoilerType";

/**
 *
 * @export
 * @interface StopIdentificationTestRequest
 */
export interface StopIdentificationTestRequest {
  /**
   *
   * @type {BoilerType}
   * @memberof StopIdentificationTestRequest
   */
  boilerType: BoilerType | null;
}

/**
 * Check if a given object implements the StopIdentificationTestRequest interface.
 */
export function instanceOfStopIdentificationTestRequest(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "boilerType" in value;

  return isInstance;
}

export function StopIdentificationTestRequestFromJSON(
  json: any,
): StopIdentificationTestRequest {
  return StopIdentificationTestRequestFromJSONTyped(json, false);
}

export function StopIdentificationTestRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StopIdentificationTestRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    boilerType: BoilerTypeFromJSON(json["boilerType"]),
  };
}

export function StopIdentificationTestRequestToJSON(
  value?: StopIdentificationTestRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    boilerType: BoilerTypeToJSON(value.boilerType),
  };
}
