/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Tariff } from "./Tariff";
import { TariffFromJSON, TariffFromJSONTyped, TariffToJSON } from "./Tariff";

/**
 *
 * @export
 * @interface TariffsResult
 */
export interface TariffsResult {
  /**
   *
   * @type {Tariff}
   * @memberof TariffsResult
   */
  currentTariff: Tariff | null;
  /**
   *
   * @type {Array<Tariff>}
   * @memberof TariffsResult
   */
  pastTariffs: Array<Tariff>;
  /**
   *
   * @type {Array<Tariff>}
   * @memberof TariffsResult
   */
  futureTariffs: Array<Tariff>;
}

/**
 * Check if a given object implements the TariffsResult interface.
 */
export function instanceOfTariffsResult(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "currentTariff" in value;
  isInstance = isInstance && "pastTariffs" in value;
  isInstance = isInstance && "futureTariffs" in value;

  return isInstance;
}

export function TariffsResultFromJSON(json: any): TariffsResult {
  return TariffsResultFromJSONTyped(json, false);
}

export function TariffsResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TariffsResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    currentTariff: TariffFromJSON(json["currentTariff"]),
    pastTariffs: (json["pastTariffs"] as Array<any>).map(TariffFromJSON),
    futureTariffs: (json["futureTariffs"] as Array<any>).map(TariffFromJSON),
  };
}

export function TariffsResultToJSON(value?: TariffsResult | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    currentTariff: TariffToJSON(value.currentTariff),
    pastTariffs: (value.pastTariffs as Array<any>).map(TariffToJSON),
    futureTariffs: (value.futureTariffs as Array<any>).map(TariffToJSON),
  };
}
