/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const TariffType = {
  Single: "single",
  Double: "double",
  Dynamic: "dynamic",
} as const;
export type TariffType = (typeof TariffType)[keyof typeof TariffType];

export function TariffTypeFromJSON(json: any): TariffType {
  return TariffTypeFromJSONTyped(json, false);
}

export function TariffTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TariffType {
  return json as TariffType;
}

export function TariffTypeToJSON(value?: TariffType | null): any {
  return value as any;
}
