/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { TicketHsPipelineStage } from "./TicketHsPipelineStage";
import {
  TicketHsPipelineStageFromJSON,
  TicketHsPipelineStageFromJSONTyped,
  TicketHsPipelineStageToJSON,
} from "./TicketHsPipelineStage";
import type { TicketHubspotOwnerId } from "./TicketHubspotOwnerId";
import {
  TicketHubspotOwnerIdFromJSON,
  TicketHubspotOwnerIdFromJSONTyped,
  TicketHubspotOwnerIdToJSON,
} from "./TicketHubspotOwnerId";

/**
 *
 * @export
 * @interface Ticket
 */
export interface Ticket {
  /**
   *
   * @type {string}
   * @memberof Ticket
   */
  order_number: string;
  /**
   *
   * @type {TicketHsPipelineStage}
   * @memberof Ticket
   */
  hs_pipeline_stage: TicketHsPipelineStage;
  /**
   *
   * @type {string}
   * @memberof Ticket
   */
  subject: string;
  /**
   *
   * @type {TicketHubspotOwnerId}
   * @memberof Ticket
   */
  hubspot_owner_id: TicketHubspotOwnerId;
  /**
   *
   * @type {number}
   * @memberof Ticket
   */
  hs_object_id: number;
  /**
   *
   * @type {Date}
   * @memberof Ticket
   */
  createdate: Date;
}

/**
 * Check if a given object implements the Ticket interface.
 */
export function instanceOfTicket(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "order_number" in value;
  isInstance = isInstance && "hs_pipeline_stage" in value;
  isInstance = isInstance && "subject" in value;
  isInstance = isInstance && "hubspot_owner_id" in value;
  isInstance = isInstance && "hs_object_id" in value;
  isInstance = isInstance && "createdate" in value;

  return isInstance;
}

export function TicketFromJSON(json: any): Ticket {
  return TicketFromJSONTyped(json, false);
}

export function TicketFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Ticket {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    order_number: json["order_number"],
    hs_pipeline_stage: TicketHsPipelineStageFromJSON(json["hs_pipeline_stage"]),
    subject: json["subject"],
    hubspot_owner_id: TicketHubspotOwnerIdFromJSON(json["hubspot_owner_id"]),
    hs_object_id: json["hs_object_id"],
    createdate: new Date(json["createdate"]),
  };
}

export function TicketToJSON(value?: Ticket | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    order_number: value.order_number,
    hs_pipeline_stage: TicketHsPipelineStageToJSON(value.hs_pipeline_stage),
    subject: value.subject,
    hubspot_owner_id: TicketHubspotOwnerIdToJSON(value.hubspot_owner_id),
    hs_object_id: value.hs_object_id,
    createdate: value.createdate.toISOString(),
  };
}
