/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateHeatBattery
 */
export interface UpdateHeatBattery {
  /**
   *
   * @type {string}
   * @memberof UpdateHeatBattery
   */
  serialNumber: string;
}

/**
 * Check if a given object implements the UpdateHeatBattery interface.
 */
export function instanceOfUpdateHeatBattery(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "serialNumber" in value;

  return isInstance;
}

export function UpdateHeatBatteryFromJSON(json: any): UpdateHeatBattery {
  return UpdateHeatBatteryFromJSONTyped(json, false);
}

export function UpdateHeatBatteryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateHeatBattery {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    serialNumber: json["serialNumber"],
  };
}

export function UpdateHeatBatteryToJSON(value?: UpdateHeatBattery | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    serialNumber: value.serialNumber,
  };
}
