/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateTariffForInstallation404ResponseAllOfResult
 */
export interface UpdateTariffForInstallation404ResponseAllOfResult {
  /**
   *
   * @type {string}
   * @memberof UpdateTariffForInstallation404ResponseAllOfResult
   */
  errorCode?: UpdateTariffForInstallation404ResponseAllOfResultErrorCodeEnum;
}

/**
 * @export
 */
export const UpdateTariffForInstallation404ResponseAllOfResultErrorCodeEnum = {
  InstallationNotFound: "INSTALLATION_NOT_FOUND",
  TariffNotFound: "TARIFF_NOT_FOUND",
  CicNotFound: "CIC_NOT_FOUND",
  UserNotFound: "USER_NOT_FOUND",
} as const;
export type UpdateTariffForInstallation404ResponseAllOfResultErrorCodeEnum =
  (typeof UpdateTariffForInstallation404ResponseAllOfResultErrorCodeEnum)[keyof typeof UpdateTariffForInstallation404ResponseAllOfResultErrorCodeEnum];

/**
 * Check if a given object implements the UpdateTariffForInstallation404ResponseAllOfResult interface.
 */
export function instanceOfUpdateTariffForInstallation404ResponseAllOfResult(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateTariffForInstallation404ResponseAllOfResultFromJSON(
  json: any,
): UpdateTariffForInstallation404ResponseAllOfResult {
  return UpdateTariffForInstallation404ResponseAllOfResultFromJSONTyped(
    json,
    false,
  );
}

export function UpdateTariffForInstallation404ResponseAllOfResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateTariffForInstallation404ResponseAllOfResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    errorCode: !exists(json, "errorCode") ? undefined : json["errorCode"],
  };
}

export function UpdateTariffForInstallation404ResponseAllOfResultToJSON(
  value?: UpdateTariffForInstallation404ResponseAllOfResult | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    errorCode: value.errorCode,
  };
}
