/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateHeatCharger
 */
export interface UpdateHeatCharger {
  /**
   *
   * @type {string}
   * @memberof UpdateHeatCharger
   */
  serialNumber: string;
}

/**
 * Check if a given object implements the UpdateHeatCharger interface.
 */
export function instanceOfUpdateHeatCharger(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "serialNumber" in value;

  return isInstance;
}

export function UpdateHeatChargerFromJSON(json: any): UpdateHeatCharger {
  return UpdateHeatChargerFromJSONTyped(json, false);
}

export function UpdateHeatChargerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateHeatCharger {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    serialNumber: json["serialNumber"],
  };
}

export function UpdateHeatChargerToJSON(value?: UpdateHeatCharger | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    serialNumber: value.serialNumber,
  };
}
