/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateCommissioningTest
 */
export interface UpdateCommissioningTest {
  /**
   *
   * @type {string}
   * @memberof UpdateCommissioningTest
   */
  status?: UpdateCommissioningTestStatusEnum;
  /**
   *
   * @type {boolean}
   * @memberof UpdateCommissioningTest
   */
  forced?: boolean;
}

/**
 * @export
 */
export const UpdateCommissioningTestStatusEnum = {
  Success: "SUCCESS",
  Cancelled: "CANCELLED",
  InProgress: "IN_PROGRESS",
} as const;
export type UpdateCommissioningTestStatusEnum =
  (typeof UpdateCommissioningTestStatusEnum)[keyof typeof UpdateCommissioningTestStatusEnum];

/**
 * Check if a given object implements the UpdateCommissioningTest interface.
 */
export function instanceOfUpdateCommissioningTest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateCommissioningTestFromJSON(
  json: any,
): UpdateCommissioningTest {
  return UpdateCommissioningTestFromJSONTyped(json, false);
}

export function UpdateCommissioningTestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateCommissioningTest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    status: !exists(json, "status") ? undefined : json["status"],
    forced: !exists(json, "forced") ? undefined : json["forced"],
  };
}

export function UpdateCommissioningTestToJSON(
  value?: UpdateCommissioningTest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    status: value.status,
    forced: value.forced,
  };
}
