/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateUserClient404ResponseAllOfResult
 */
export interface UpdateUserClient404ResponseAllOfResult {
  /**
   *
   * @type {object}
   * @memberof UpdateUserClient404ResponseAllOfResult
   */
  errorCode?: object;
  /**
   *
   * @type {object}
   * @memberof UpdateUserClient404ResponseAllOfResult
   */
  error?: object;
}

/**
 * Check if a given object implements the UpdateUserClient404ResponseAllOfResult interface.
 */
export function instanceOfUpdateUserClient404ResponseAllOfResult(
  value: object,
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateUserClient404ResponseAllOfResultFromJSON(
  json: any,
): UpdateUserClient404ResponseAllOfResult {
  return UpdateUserClient404ResponseAllOfResultFromJSONTyped(json, false);
}

export function UpdateUserClient404ResponseAllOfResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateUserClient404ResponseAllOfResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    errorCode: !exists(json, "errorCode") ? undefined : json["errorCode"],
    error: !exists(json, "error") ? undefined : json["error"],
  };
}

export function UpdateUserClient404ResponseAllOfResultToJSON(
  value?: UpdateUserClient404ResponseAllOfResult | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    errorCode: value.errorCode,
    error: value.error,
  };
}
