/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ResponseMeta } from "./ResponseMeta";
import {
  ResponseMetaFromJSON,
  ResponseMetaFromJSONTyped,
  ResponseMetaToJSON,
} from "./ResponseMeta";
import type { UpdateCommissioningTest409ResponseAllOfResult } from "./UpdateCommissioningTest409ResponseAllOfResult";
import {
  UpdateCommissioningTest409ResponseAllOfResultFromJSON,
  UpdateCommissioningTest409ResponseAllOfResultFromJSONTyped,
  UpdateCommissioningTest409ResponseAllOfResultToJSON,
} from "./UpdateCommissioningTest409ResponseAllOfResult";

/**
 *
 * @export
 * @interface UpdateCommissioningTest409Response
 */
export interface UpdateCommissioningTest409Response {
  /**
   *
   * @type {ResponseMeta}
   * @memberof UpdateCommissioningTest409Response
   */
  meta: ResponseMeta;
  /**
   *
   * @type {UpdateCommissioningTest409ResponseAllOfResult}
   * @memberof UpdateCommissioningTest409Response
   */
  result: UpdateCommissioningTest409ResponseAllOfResult;
}

/**
 * Check if a given object implements the UpdateCommissioningTest409Response interface.
 */
export function instanceOfUpdateCommissioningTest409Response(
  value: object,
): boolean {
  let isInstance = true;
  isInstance = isInstance && "meta" in value;
  isInstance = isInstance && "result" in value;

  return isInstance;
}

export function UpdateCommissioningTest409ResponseFromJSON(
  json: any,
): UpdateCommissioningTest409Response {
  return UpdateCommissioningTest409ResponseFromJSONTyped(json, false);
}

export function UpdateCommissioningTest409ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateCommissioningTest409Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    meta: ResponseMetaFromJSON(json["meta"]),
    result: UpdateCommissioningTest409ResponseAllOfResultFromJSON(
      json["result"],
    ),
  };
}

export function UpdateCommissioningTest409ResponseToJSON(
  value?: UpdateCommissioningTest409Response | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    meta: ResponseMetaToJSON(value.meta),
    result: UpdateCommissioningTest409ResponseAllOfResultToJSON(value.result),
  };
}
