/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateCicWifiProperties
 */
export interface UpdateCicWifiProperties {
  /**
   *
   * @type {string}
   * @memberof UpdateCicWifiProperties
   */
  wifiSSID?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateCicWifiProperties
   */
  wifiPassword?: string;
}

/**
 * Check if a given object implements the UpdateCicWifiProperties interface.
 */
export function instanceOfUpdateCicWifiProperties(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateCicWifiPropertiesFromJSON(
  json: any,
): UpdateCicWifiProperties {
  return UpdateCicWifiPropertiesFromJSONTyped(json, false);
}

export function UpdateCicWifiPropertiesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateCicWifiProperties {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    wifiSSID: !exists(json, "wifiSSID") ? undefined : json["wifiSSID"],
    wifiPassword: !exists(json, "wifiPassword")
      ? undefined
      : json["wifiPassword"],
  };
}

export function UpdateCicWifiPropertiesToJSON(
  value?: UpdateCicWifiProperties | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    wifiSSID: value.wifiSSID,
    wifiPassword: value.wifiPassword,
  };
}
