/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { MaxSoundLevel } from "./MaxSoundLevel";
import {
  MaxSoundLevelFromJSON,
  MaxSoundLevelFromJSONTyped,
  MaxSoundLevelToJSON,
} from "./MaxSoundLevel";
import type { SilentMode } from "./SilentMode";
import {
  SilentModeFromJSON,
  SilentModeFromJSONTyped,
  SilentModeToJSON,
} from "./SilentMode";

/**
 *
 * @export
 * @interface UpdateCicSharedProperties
 */
export interface UpdateCicSharedProperties {
  /**
   * Electricity price for single tariff
   * @type {number}
   * @memberof UpdateCicSharedProperties
   */
  electricityPrice?: number | null;
  /**
   * Day electricity price for double tariff
   * @type {number}
   * @memberof UpdateCicSharedProperties
   */
  dayElectricityPrice?: number | null;
  /**
   * Night electricity price for double tariff
   * @type {number}
   * @memberof UpdateCicSharedProperties
   */
  nightElectricityPrice?: number | null;
  /**
   * Gas price
   * @type {number}
   * @memberof UpdateCicSharedProperties
   */
  gasPrice?: number | null;
  /**
   * When false, send default prices to not limit the heat pump
   * @type {boolean}
   * @memberof UpdateCicSharedProperties
   */
  usePricingToLimitHeatPump?: boolean;
  /**
   *
   * @type {SilentMode}
   * @memberof UpdateCicSharedProperties
   */
  silentMode?: SilentMode;
  /**
   *
   * @type {MaxSoundLevel}
   * @memberof UpdateCicSharedProperties
   */
  dayMaxSoundLevel?: MaxSoundLevel;
  /**
   *
   * @type {MaxSoundLevel}
   * @memberof UpdateCicSharedProperties
   */
  nightMaxSoundLevel?: MaxSoundLevel;
}

/**
 * Check if a given object implements the UpdateCicSharedProperties interface.
 */
export function instanceOfUpdateCicSharedProperties(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateCicSharedPropertiesFromJSON(
  json: any,
): UpdateCicSharedProperties {
  return UpdateCicSharedPropertiesFromJSONTyped(json, false);
}

export function UpdateCicSharedPropertiesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateCicSharedProperties {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    electricityPrice: !exists(json, "electricityPrice")
      ? undefined
      : json["electricityPrice"],
    dayElectricityPrice: !exists(json, "dayElectricityPrice")
      ? undefined
      : json["dayElectricityPrice"],
    nightElectricityPrice: !exists(json, "nightElectricityPrice")
      ? undefined
      : json["nightElectricityPrice"],
    gasPrice: !exists(json, "gasPrice") ? undefined : json["gasPrice"],
    usePricingToLimitHeatPump: !exists(json, "usePricingToLimitHeatPump")
      ? undefined
      : json["usePricingToLimitHeatPump"],
    silentMode: !exists(json, "silentMode")
      ? undefined
      : SilentModeFromJSON(json["silentMode"]),
    dayMaxSoundLevel: !exists(json, "dayMaxSoundLevel")
      ? undefined
      : MaxSoundLevelFromJSON(json["dayMaxSoundLevel"]),
    nightMaxSoundLevel: !exists(json, "nightMaxSoundLevel")
      ? undefined
      : MaxSoundLevelFromJSON(json["nightMaxSoundLevel"]),
  };
}

export function UpdateCicSharedPropertiesToJSON(
  value?: UpdateCicSharedProperties | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    electricityPrice: value.electricityPrice,
    dayElectricityPrice: value.dayElectricityPrice,
    nightElectricityPrice: value.nightElectricityPrice,
    gasPrice: value.gasPrice,
    usePricingToLimitHeatPump: value.usePricingToLimitHeatPump,
    silentMode: SilentModeToJSON(value.silentMode),
    dayMaxSoundLevel: MaxSoundLevelToJSON(value.dayMaxSoundLevel),
    nightMaxSoundLevel: MaxSoundLevelToJSON(value.nightMaxSoundLevel),
  };
}
