/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ZuperJob
 */
export interface ZuperJob {
  /**
   *
   * @type {string}
   * @memberof ZuperJob
   */
  job_uid: string;
  /**
   *
   * @type {string}
   * @memberof ZuperJob
   */
  job_title: string;
  /**
   *
   * @type {string}
   * @memberof ZuperJob
   */
  installer: string | null;
  /**
   *
   * @type {string}
   * @memberof ZuperJob
   */
  status_name: string;
  /**
   *
   * @type {Date}
   * @memberof ZuperJob
   */
  updated_at: Date;
  /**
   *
   * @type {Array<ZuperJob>}
   * @memberof ZuperJob
   */
  services: Array<ZuperJob>;
}

/**
 * Check if a given object implements the ZuperJob interface.
 */
export function instanceOfZuperJob(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "job_uid" in value;
  isInstance = isInstance && "job_title" in value;
  isInstance = isInstance && "installer" in value;
  isInstance = isInstance && "status_name" in value;
  isInstance = isInstance && "updated_at" in value;
  isInstance = isInstance && "services" in value;

  return isInstance;
}

export function ZuperJobFromJSON(json: any): ZuperJob {
  return ZuperJobFromJSONTyped(json, false);
}

export function ZuperJobFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ZuperJob {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    job_uid: json["job_uid"],
    job_title: json["job_title"],
    installer: json["installer"],
    status_name: json["status_name"],
    updated_at: new Date(json["updated_at"]),
    services: (json["services"] as Array<any>).map(ZuperJobFromJSON),
  };
}

export function ZuperJobToJSON(value?: ZuperJob | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    job_uid: value.job_uid,
    job_title: value.job_title,
    installer: value.installer,
    status_name: value.status_name,
    updated_at: value.updated_at.toISOString(),
    services: (value.services as Array<any>).map(ZuperJobToJSON),
  };
}
