/* tslint:disable */
/* eslint-disable */
/**
 * Quatt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ZuperService } from "./ZuperService";
import {
  ZuperServiceFromJSON,
  ZuperServiceFromJSONTyped,
  ZuperServiceToJSON,
} from "./ZuperService";

/**
 *
 * @export
 * @interface ZuperJobs
 */
export interface ZuperJobs {
  /**
   *
   * @type {Array<ZuperService>}
   * @memberof ZuperJobs
   */
  installations: Array<ZuperService>;
  /**
   *
   * @type {Array<ZuperService>}
   * @memberof ZuperJobs
   */
  services: Array<ZuperService>;
}

/**
 * Check if a given object implements the ZuperJobs interface.
 */
export function instanceOfZuperJobs(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "installations" in value;
  isInstance = isInstance && "services" in value;

  return isInstance;
}

export function ZuperJobsFromJSON(json: any): ZuperJobs {
  return ZuperJobsFromJSONTyped(json, false);
}

export function ZuperJobsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ZuperJobs {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    installations: (json["installations"] as Array<any>).map(
      ZuperServiceFromJSON,
    ),
    services: (json["services"] as Array<any>).map(ZuperServiceFromJSON),
  };
}

export function ZuperJobsToJSON(value?: ZuperJobs | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    installations: (value.installations as Array<any>).map(ZuperServiceToJSON),
    services: (value.services as Array<any>).map(ZuperServiceToJSON),
  };
}
